### ISSUE TITLE
how to get the embedding matrix result following the example.py

### ISSUE THREAD

**Issue by leeyifu** [thunlp/OpenKE#10]
following the example.py, the result is saved in './res/model.vec'
I wonder how to get the embedding results? for example, how to get the numpy array for each entity?

**Comment by THUCSTHanxu13** [comment]
(1) Set import files and OpenKE will automatically load models via tf.Saver().

	con = config.Config()
	con.set_in_path("./benchmarks/FB15K/")
	con.set_test_flag(True)
	con.set_work_threads(4)
	con.set_dimension(50)
	con.set_import_files("./res/model.vec.tf")
	con.init()
	con.set_model(models.TransE)
	# Get the embeddings (numpy.array)
	embeddings = con.get_parameters("numpy")
	# Get the embeddings (python list)
	embeddings = con.get_parameters()

(2) Read model parameters from json files and manually load parameters.

	con = config.Config()
	con.set_in_path("./benchmarks/FB15K/")
	con.set_test_flag(True)
	con.set_work_threads(4)
	con.set_dimension(50)
	con.init()
	con.set_model(models.TransE)
	f = open("./res/embedding.vec.json", "r")
	embeddings = json.loads(f.read())
	f.close()

(3) Manually load models via tf.Saver().

	con = config.Config()
	con.set_in_path("./benchmarks/FB15K/")
	con.set_test_flag(True)
	con.set_work_threads(4)
	con.set_dimension(50)
	con.init()
	con.set_model(models.TransE)
	con.import_variables("./res/model.vec.tf")
	# Get the embeddings (numpy.array)
	embeddings = con.get_parameters("numpy")
	# Get the embeddings (python list)
	embeddings = con.get_parameters()

(4) You can also immediately get the embeddings after train the model as follows,
	...
	...
	...
	#Models will be exported via tf.Saver() automatically.
	con.set_export_files("./res/model.vec.tf", 0)
	#Model parameters will be exported to json files automatically.
	con.set_out_files("./res/embedding.vec.json")
	#Initialize experimental settings.
	con.init()
	#Set the knowledge embedding model
	con.set_model(models.TransE)
	#Train the model.
	con.run()
	#Get the embeddings (numpy.array)
	embeddings = con.get_parameters("numpy")
	#Get the embeddings (python list)
	embeddings = con.get_parameters()

**Comment by vlainic** [comment]
Are these solutions still valid, due to the TF -> PyTorch change? Also, there is no config.Config() in the repo.

**Comment by isspek** [comment]
I am interested in the answer of the question by @vlainic. How can we get the embeddings file from a model trained with PyTorch. Could it be an example for showing this usecase?
