### ISSUE TITLE
Hyperparam tuning

### ISSUE THREAD

**Issue by mattivi** [thunlp/OpenKE#102]
Hi, awesome work with OpenKE. I am wondering if there is any already available procedure to choose the best parameters for a given model? 
E.g. set_nbatches, set_alpha, set_lmbda, etc..
This would help to easily use OpenKE I think.
Many thanks!

**Comment by ShulinCao** [comment]
Thank you for your advice! We will consider incorporating the procedure into OpenKE.

**Comment by mattivi** [comment]
Can you give me a hint of which library you used for the hyperparam tuning?

**Comment by ShulinCao** [comment]
We didn't use any library for hyperparam tuning.  We set them according to the optimal hypeparam from original papers.
