### ISSUE TITLE
Negative sampling

### ISSUE THREAD

**Issue by Saatviga** [thunlp/OpenKE#106]
Hi,

Can you please let me know what is the purpose of,
con.set_ent_neg_rate(1)
con.set_rel_neg_rate(0)

during the training phase? I understant con.set_bern(0) uses the traditional sampling method for corrupt cases. What is the purpose of these 2 lines? I also found that test_neg and valid_neg files are generated in the test phase. Is the valid2id.txt used in the training phase to stop the training process? 

Thanks

**Comment by UditGupta10** [comment]
con.set_ent_neg_rate(1): Number of negative samples to be generated per instance in which either the head or tail is corrupted. (=1)
con.set_rel_neg_rate(0): Number of negative samples to be generated per instance in which the relation is corrupted. (=0).
valid2id.txt is not used for early stopping. Only purpose as of now is to do 'test_triple_classification' in test phase which requires a threshold. This threshold is learnt using valid.txt.

**Comment by ShulinCao** [comment]
Early stopping is supported now. Valid2id.txt is used for both early stopping and triple classification.
