### ISSUE TITLE
self.sess.run(self.trainModel.parameter_lists[var_name])时被kill掉

### ISSUE THREAD

**Issue by xuwuW** [thunlp/OpenKE#110]
您好，我的数据集中实体的数目有1000w+（100维），导致在读取embedding的时候，到了get_parameters_by_name(self, var_name)下的self.sess.run(self.trainModel.parameter_lists[var_name])就会卡住，然后被kill掉。请问有没有什么解决的建议吗？

**Comment by THUCSTHanxu13** [comment]
你这个可能是爆显存了吧，你可以改下config.py里面的set_model处，或者到model里面，把参数放到cpu上
