### ISSUE TITLE
请问train2id.txt里的数据必须是不能重复的吗？

### ISSUE THREAD

**Issue by penelope24** [thunlp/OpenKE#115]
大神您好！
我看了一下bash.h里的代码，训练集中重复的数据貌似会在排序过程中被覆盖掉。
我试了一下自己构造的数据也的确是这样的。
是否TransE这类的方法并没有考虑到边的频数对于最终embedding结果的影响呢？
谢谢！

**Comment by THUCSTHanxu13** [comment]
这些模型是没有考虑边的频数的，对于模型来说，同一个(h,r,t)在数据中出现多次意义并不大。如果你想要考虑每一个(h,r,t)的权重，你可以改loss function，给每个(h,r,t)在计算loss的时候赋不同的权重。
