### ISSUE TITLE
请问该如何读取model.vec.tf？

### ISSUE THREAD

**Issue by penelope24** [thunlp/OpenKE#117]
您好，请问读取训练好的embedding除了直接读取JSON以外是否还可以通过model.vec.tf呢？
如果可以的话，我该如何通过tensorflow来读取.tf文件呢，谢谢！

**Comment by THUCSTHanxu13** [comment]
你可以看下样例代码，里面有三段程序分别以不同的方式读入文件，（1）代码是直接读入tensorflow的存储结果的（2）代码是读入json格式的。
