### ISSUE TITLE
[feature request] re-load pre-trained entity embeddings to finetune

### ISSUE THREAD

**Issue by yuchenlin** [thunlp/OpenKE#123]
Currently, all embeddings [entity/relation] are randomly initialized. It would be very helpful if we can reload the pre-trained embeddings and then finetune them.

**Comment by ShulinCao** [comment]
You can refer to **models/TransR.py** and **examples/train_transR.py**, pre-training embeddings are used to initialize the parameters.

**Comment by yuchenlin** [comment]
Hi Shulin, 

Thanks so much! It seems that the input should also be the embeddings and model parameters that are pre-trained by OpenKE. However, my case is like, I have some entity-embeddings and relation-embeddings that are obtained from other resources (like word embeddings from google word2vec). Is that also possible to be reloaded to OpenKE? 

Thanks, Bill

**Comment by ShulinCao** [comment]
https://github.com/thunlp/OpenKE/blob/498b5fd86ecf8a035f96b9092db6b0bf2cf4637b/models/TransR.py#L20
You can modify the init_weights function. For example, if you have some numpy array entity-embeddings, you can use
```
self.ent_embeddings.weight.data.copy_(torch.from_numpy(your embeddings))
```
