### ISSUE TITLE
Obtaining parameters is broken in PyTorch branch

### ISSUE THREAD

**Issue by villmow** [thunlp/OpenKE#124]
I used to obtain the parameters (weight matrices) of the model as explained [here](https://github.com/thunlp/OpenKE/issues/84#issuecomment-424329635) with a call to `con.get_parameters()`. It appears that the interface to `get_parameters()` has changed since the update in this commit: https://github.com/thunlp/OpenKE/commit/aa17828b585522bad1236fc0e027d0a58de1762 

The method used to look like this:
```python
def get_parameters(self, mode = "numpy"):
	res = {}
	lists = self.get_parameter_lists()
	for var_name in lists:
		if mode == "numpy":
			res[var_name] = self.get_parameters_by_name(var_name)
		else:
			res[var_name] = self.get_parameters_by_name(var_name).tolist()
	return res
```

Now a `param_dict` is required and the method actually does nothing except copying the contents of `param_dict` in a specific format (numpy, list) to a new dictionary `res`: 

```python
    def get_parameters(self, param_dict, mode="numpy"):
        for param in param_dict:
            param_dict[param] = param_dict[param].cpu()
        res = {}
        for param in param_dict:
            if mode == "numpy":
                res[param] = param_dict[param].numpy()
            elif mode == "list":
                res[param] = param_dict[param].numpy().tolist()
            else:
                res[param] = param_dict[param]
        return res
```

How should I now obtain the weight matrices of the model, or will this method be fixed?

**Comment by ShulinCao** [comment]
Say your model is trainModel, you can use **get_parameters(trainModel.state_dict())** to get the parameters.
