### ISSUE TITLE
HoLE implementation in pytorch

### ISSUE THREAD

**Issue by svjan5** [thunlp/OpenKE#125]
Hi,
Is it possible to implement HoLE (holographic embeddings) in pytorch? You have not included the code for that. 

Thanks in advance

**Comment by THUCSTHanxu13** [comment]
As Pytorch has released the code for fft and ifft, we thus implement HolE recently. Although the current pytorch versions (1.2 1.3 1.4) cannot well support the calculation of imaginary numbers (e.g., torch.conj() cannot work on GPUs), we thus implement some operations by ourselves. We suggest to check the code before using HolE.

**Comment by THUCSTHanxu13** [comment]
As the hyper-parameters in the original paper of HolE cannot reproduce the experimental results of the paper (https://github.com/mnick/holographic-embeddings/issues/5), the hyper-parameters in our example code for using HolE are not effective enough.
