### ISSUE TITLE
.Model import in TransE

### ISSUE THREAD

**Issue by trbn** [thunlp/OpenKE#127]
Hi,
I have tried to run TransE model. 
At the first, I compiled C++ files. and installed TensorFlow.
Next, I run TransE. But I got this error:
      from .Model import Model
      ModuleNotFoundError: No module named '__main__.Model'; '__main__' is not a package

Please let me know what I should do to run this model.
Many thanks in advance.
Najmeh

**Comment by arsenious** [comment]
Try to clone the entire repository as it is and run "example_test_transe.py" .
I think you are trying to run the model file directly. That won't work.

**Comment by trbn** [comment]
Hi arsenious
I have run "example_test_transe.py" and there is the result of it:
`Traceback (most recent call last):
  File "C:/Users/Narges/OpenKE-master/example_test_transe.py", line 9, in <module>
    con = config.Config()
  File "C:\Users\Narges\OpenKE-master\config\Config.py", line 16, in __init__
    self.lib = ctypes.cdll.LoadLibrary(base_file)
  File "C:\Users\Narges\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Narges\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

Process finished with exit code 1`

**Comment by arsenious** [comment]
You're using Windows, which can cause issues. This issue is probably being caused due to Win32 dlls being run with Python 64-bit.
OpenKE works really well on Ubuntu Linux. I would strongly recommend you start using Linux for Deep Learning/AI applications as a long term measure. My opinion is that Windows is not that good for open source deep learning codes, as they are usually optimized for Linux.

**Comment by trbn** [comment]
Many thanks arsenious for the recommendation. I will test it on Ubuntu and tell you the results.

**Comment by arsenious** [comment]
Sure, I'd be happy to help. All the best!
Also, use Anaconda for Python and create a conda env as well .

Check out these posts before installing to get an idea:
https://medium.com/@adeshg7/easy-setup-a-python-deep-learning-environment-67febf66f3bf
https://github.com/floydhub/dl-setup

**Comment by trbn** [comment]
Dear arsenious,
I have done.
Many thanks for your help.

**Comment by arsenious** [comment]
> Dear arsenious,
> I have done.
> Many thanks for your help.

Hi, good to hear that. Were you able to run the example code end-to-end? These benchmark datasets are relatively large. Do you have a GPU to run them?

**Comment by trbn** [comment]
I could run example code on free15k completely. In fact, some others are large. Maybe I can ask our admin lab to give me an account of GPU. Do you have any suggestion?

**Comment by arsenious** [comment]
[umls.zip](https://github.com/thunlp/OpenKE/files/2922438/umls.zip)
I've attached UMLS (medical) dataset which I had converted from https://github.com/fanyangxyz/Neural-LP/tree/master/datasets  
I have concatenated the train and facts file from Neural LP, to form the train2id file. 
This is a much smaller dataset but is often used.

Yes GPU would be a good idea. Be careful with the con class of OPENKE as it caused issues with GPU detection. Try using the GPU.
What are you trying to do btw?

**Comment by trbn** [comment]
Thank you very much. I am going to run examples on umls dataset and will text you the result. 
That was a great  guidance for using the GPU.
I'm trying to test a knowledge graph embedding model which I think will improve the results but I am not sure yet.

**Comment by arsenious** [comment]
> Thank you very much. I am going to run examples on umls dataset and will text you the result.
> That was a great guidance for using the GPU.
> I'm trying to test a knowledge graph embedding model which I think will improve the results but I am not sure yet.

Sure, thanks. It would be better if we continued on your GitHub, as this issue is resolved.
