### ISSUE TITLE
model can not be exported

### ISSUE THREAD

**Issue by zhouhoo** [thunlp/OpenKE#13]
Hi, I clone the code, and run the example, it seems good and print the log. but I can not get model.vec.tf file in res folder. 
it only contain some files like this:
![55](https://user-images.githubusercontent.com/5432592/34324104-97b9cfb8-e89f-11e7-8f87-ac5cef8575f8.png)

**Comment by THUCSTHanxu13** [comment]
Could you tell me your tensorflow version?

**Comment by zhouhoo** [comment]
I got the idea, It is ok that there are three files.  My tf version is different from yours.
