### ISSUE TITLE
Example is broken with new version of tensorflow

### ISSUE THREAD

**Issue by aspanghe** [thunlp/OpenKE#132]
Hi guys,

Thanks for the great library.

One comment. 

It appears as though tensorflow has refactored a bit and `tf.batch_matmul()` is now simply `tf.matmul()`

Adding these lines of code to the top of https://github.com/thunlp/OpenKE/blob/master/models/TransR.py should address this problem:

```
if tf.__version__ > '0.12.1':
	matmul_func = tf.matmul
else:
	matmul_func = tf.batch_matmul

class TransR(Model):
	r'''
	TransR first projects entities from entity space to corresponding relation space 
	and then builds translations between projected entities. 
	'''
	def _transfer(self, transfer_matrix, embeddings):
		return matmul_func(transfer_matrix, embeddings)
```

Alex

**Comment by aspanghe** [comment]
See: https://github.com/tensorflow/tensorflow/issues/6560

**Comment by THUCSTHanxu13** [comment]
I have added this part into the code. Thank you very much for your help.
