### ISSUE TITLE
Entity may have multple words, How to make Entity2id file?

### ISSUE THREAD

**Issue by Borororo** [thunlp/OpenKE#134]
Thanks for sharing!
I want to adopt TransE on another own dataset, but unsure how I can achieve it.
It is hard to build entity2id file, since entity in  mine dataset is usually composed by mulitple words. 
For example: 
>  UsedFor    **zoom_lens**     **bringing_distant_object_into_focus**

if I treat zoom_lens as a whole entity, then I might get hundreds of thousands of entitys and that is useless. The best way is to divide each entity into words, like zoom_lens -> zoom + lens, but this will raise another issue:
in train2id file , each line will became [2,4] (e1) [12,35,55] (e2) [2] (relation) which is impossilbe to get trained.

so Any ideas?

**Comment by THUCSTHanxu13** [comment]
This toolkit is used for embedding knowledge graphs. In KGs, this nested entity mention will be viewed as different entities. Hence, in fact, there are many entities in KGs which may contain the same sub-mentions. So, I also have no idea to solve your problem. Maybe, you can use the experience of the character embedding and subword embedding.
