### ISSUE TITLE
请问type_constraints这种测试时才用到的类型约束是哪篇论文提到的？

### ISSUE THREAD

**Issue by 27232xsl** [thunlp/OpenKE#135]

**Comment by THUCSTHanxu13** [comment]
这个主要是用来测试的。在一般测试的时候对于给定实体(h,r,t)，我要将t换成其他实体来判断(h,r,t)的得分函数排在多少。不过有种测试方式会加一些限制，比如t的替换项不是全部实体集合中的元素，而是关系r右侧可能出现的实体集合元素，type_constrain.txt就是统计每个关系左侧右侧可能出现的实体集合。这种测试方式比较奇怪，绝大多数时候并没有被使用，一般只是用在大规模的数据上。

**Comment by THUCSTHanxu13** [comment]
(http://www.dbs.informatik.uni-muenchen.de/~krompass/papers/TypeConstrainedRepresentationLearningInKnowledgeGraphs.pdf).
论文是这个

**Comment by 27232xsl** [comment]
好的，谢谢你

**Comment by cheungdaven** [comment]
有没有办法把这个type constrain关闭掉？
