### ISSUE TITLE
Embeddings file

### ISSUE THREAD

**Issue by FernanOrtega** [thunlp/OpenKE#136]
Hi,

I found that almost all models write in the embedding.vec.json file a json object with the following entries: "ent_embeddings" and "rel_embeddings" that clearly relies on entity embeddings and relation embeddings, respectively. Your documentation spot these definitions.

But I also found that the models Analogy and ComplEx returns "ent_re_embeddings", "end_im_embeddings", "rel_re_embeddings", and "rel_im_embeddings". I suppose that the first two relies on entity embeddings and the last two relies on relation embeddings, but, what is the difference between "_re" and "_im" prefix?, why Analogy returns these embeddings in addiction to the regular one?.

I think these differences must be clearly documented in order to improve understandably of your framework.

Kind regards.

**Comment by THUCSTHanxu13** [comment]
For ComplEx and Analogy, these models set both real and imaginary vectors for entities and relations. However, other models (e.g., TransE, DistMult) just assign real vectors for KGs. Hence, for ComplEx and Analogy, our framework will output "_re" for real vectors and "_im" for imaginary vectors.
