### ISSUE TITLE
Can you help me?-Pretraind Embeddings

### ISSUE THREAD

**Issue by ypc-stu** [thunlp/OpenKE#138]
I downloaded Pretraind Embeddings----Xlore from this website http://139.129.163.161/index/toolkits, I want to use entity2vec.bin, but I found it to be a binary file.
I want to convert it to a .txt/word2vec/glove file format. I tried it very hard to solve it, but it didn't work. Can you help me how to convert, thank you.

**Comment by THUCSTHanxu13** [comment]
First you must read the binary file with "import numpy as np
vec = np.memmap(filename , dtype='float32', mode='r')". Then, you need to read the entity2id.txt of Xlore to know the id and name for each entity. Finally, you just need to align the entity2id.txt and the binary embedding file, and then rewrite them one entity per line.
