### ISSUE TITLE
About XLore Pre-trained Embeddings

### ISSUE THREAD

**Issue by 1049451037** [thunlp/OpenKE#139]
Hi, I have downloaded the [XLore pre-trained embeddings](http://139.129.163.161/index/toolkits#pretrained-embeddings). However, in the ```entity2id.txt``` file, all the entities are ```<PAD>```. And in the ```entity2id_zh.txt``` file, some English names are not complete such as ```"Intel```. I wonder if it is a bug?

**Comment by THUCSTHanxu13** [comment]
Because Xlore is a recent knowledge base constructed from Baidupedia and Wikipedia. It is a raw data and there are many errors in Xlore now. However, Xlore is growing fast. In the future, Xlore may be an effective knowledge base.
