### ISSUE TITLE
confusing about the test or predict results of models.

### ISSUE THREAD

**Issue by zhouhoo** [thunlp/OpenKE#14]
Hi,thanks for your test case, and I train and test successfully.
But  I was confused by the test  stage, here are the core code picce:

`self.lib.getHeadBatch(self.test_h_addr, self.test_t_addr, self.test_r_addr)`
`res = self.test_step(self.test_h, self.test_t, self.test_r)`

when I debug ,I found that `res` is just a list with value range from -1 to 0. are they stand for the possiblity for the indexed entity be choosing ?  so the index of the min value  is the predict entity id ? If so, why is range from [-1,0] but not [0,1]?

**Comment by THUCSTHanxu13** [comment]
For some models, higher scores mean better results. However, for some other models, lower scores mean better results. To implement these models under the same framework, we union their score functions. Specifically, we take the negative scores for some models, such as ComplEx, DistMult and RESCAL.
