### ISSUE TITLE
Question about Wikidata dataset

### ISSUE THREAD

**Issue by heendung** [thunlp/OpenKE#140]
Hi,
I just wonder whether the Wikidata dataset, provided under "Pretrained Embeddings" section on OpenKE website, is same as the whole Wikidata(**i.e.** whether the dataset contains all entities/relations/triples of the raw Wikidata). If this is just a subset of the raw Wikidata, what approaches did you use to select entities/relations/triples from the raw data to construct this dataset?

**Comment by THUCSTHanxu13** [comment]
We provide the pre-trained embeddings of a subset of Wikidata. We select the most frequent entities in Wikidata (more than 8,000,000) and filter out those entities existing fewer than 5 times in triples. For relations, we select all relations between the selected entities to construct the subset.

**Comment by THUCSTHanxu13** [comment]
Because our computer has only 32GB (RAM), we only select a subset of Wikidata to train pre-trained embeddings. If you have a more powerful computer, you can train your pre-trained embeddings using https://github.com/thunlp/Fast-TransX/tree/master/transE.
