### ISSUE TITLE
Unusual gradient values in TransE. Gradients always 0,1 or -1

### ISSUE THREAD

**Issue by UditGupta10** [thunlp/OpenKE#142]
After analysing the gradient values for TransE model for multiple epochs and batch settings, I have found that the gradient values for the entities are always 0, 1 or -1. I think this is unusual behaviour as the gradients can't always have just 3 values for such big matrix.

**Comment by THUCSTHanxu13** [comment]
For the original version TransE，the score function is |h+r-t|_l1/l2. For |h+r-t|_l1, its gradients are 1,-1. For |h+r-t|_l2, its gradients are continuous. Though TransE is simple, it is effective and often outperforms other more complicated models.
