### ISSUE TITLE
Training process doesn't start

### ISSUE THREAD

**Issue by luigiba** [thunlp/OpenKE#143]
Dear OpenKE team,
I'm getting some difficulties on starting the embedding training process. When I start the training process, the algorithm reads the entity, relation and training files and stops after a while without displaying any errors. I'm pretty sure that the files are well formatted because I've already used the algorithms with other datasets. However, using this dataset, all the algorithms present in the repository show the same behaviour.
I've modified the code to know where the process stops; it seems that it stops during the set_model function in the Config.py file at line 280 ("initializer = tf.contrib.layers.xavier_initializer(uniform = True)"). 
Do you know why this happen?
If it could be helpful I can provide the dataset where the algorithms fail.
Thanks in advance

**Comment by Nalq11** [comment]
Hi, I met the same problem. Could you please explain the reason? Thanks!

Finished, type constraint is True while not run the n-n.py.
After finishing it, it's OK.
