### ISSUE TITLE
Reader.h问题

### ISSUE THREAD

**Issue by wyue0824** [thunlp/OpenKE#145]
非常感谢您的代码：
      在阅读您代码的过程中，不明白Reader.h中的lefHead和rigHead的意义何在，看起来存的同样的index可却有些不同，请问这是什么原因。期待您的回复。

**Comment by wyue0824** [comment]
其中还有成对出现的0和-1是为何

**Comment by THUCSTHanxu13** [comment]
我们将所有的三元组都存在一个数组的连续空间里面，lefHead[i]表示实体i的三元组存储的左界，rigHead[i]表示实体i的三元组存储的右界。0，-1意味着这个实体没有作为三元组的头实体出现过。
