### ISSUE TITLE
Trans系列

### ISSUE THREAD

**Issue by 876012988** [thunlp/OpenKE#146]
请问Trans系列模型是以TransE为模板进行的改进的嘛

**Comment by THUCSTHanxu13** [comment]
Trans系列的论文基本都是按照TransE的平移约束来的，可以认为都是transE模板的改进

**Comment by THUCSTHanxu13** [comment]
从我们的实现结果来看，这些模型结果在FB15K-237上相差不大，在FB15K上倒是有差别，不过现在的FB15K已经不在论文上用了
