### ISSUE TITLE
negative sampling 问题

### ISSUE THREAD

**Issue by wyue0824** [thunlp/OpenKE#148]
非常感谢您的代码：
      请问关于negative Sampling中如何在固定范围内的triple中进行Corrupt制作，换句话说，不要全部范围内的Sampling。谢谢回复

**Comment by THUCSTHanxu13** [comment]
为了快速采样，我的采样算法写的比较复杂，感觉你要是写一个自己的采样算法的话，第一个要在https://github.com/thunlp/OpenKE/blob/master/base/Corrupt.h里面增加你的采样函数，第二个修改https://github.com/thunlp/OpenKE/blob/master/config/Config.py里的sampling函数，第三个修改https://github.com/thunlp/OpenKE/blob/master/base/Base.cpp里面C代码向python提供的sampling接口
