### ISSUE TITLE
negative Sampling 位置

### ISSUE THREAD

**Issue by wyue0824** [thunlp/OpenKE#149]
您好：
      请问如何查看制作出来的negative triple，或者如何输出他们的样子。

      谢谢

**Comment by THUCSTHanxu13** [comment]
https://github.com/thunlp/OpenKE/blob/master/base/Corrupt.h 里面就是负例采样，INT corrupt_head(INT id, INT h, INT r) 就是给定线程号id，头实体h，关系r来生成尾实体的负样例。

**Comment by chencjiajy** [comment]
> https://github.com/thunlp/OpenKE/blob/master/base/Corrupt.h 里面就是负例采样，INT corrupt_head(INT id, INT h, INT r) 就是给定线程号id，头实体h，关系r来生成尾实体的负样例。

@THUCSTHanxu13  你好，请问`corrupt_head(INT id, INT h, INT r, bool filter_flag = true)` 以及`corrupt_tail(INT id, INT t, INT r, bool filter_flag = true)`的原理什么，没有看懂
