### ISSUE TITLE
How can I use pretrained embeddings for TransE model initialization?

### ISSUE THREAD

**Issue by Kiwisher** [thunlp/OpenKE#150]
I want to initialize the embeddings for TransE using glove embeddings. Is there a way to safely do that?

**Comment by simonepri** [comment]
I think you can use the `set_parameters` function by providing a dictionary with the `ent_embeddings` and the `rel_embeddings` keys.

**Comment by simonepri** [comment]
@THUCSTHanxu13 What about documenting such a feature?

**Comment by captify-dieter** [comment]
@simonepri What's the order of such embeddings list? I would imagine these have to retain the order of the indices assigned to the unique entities?

**Comment by simonepri** [comment]
Yes that's correct, you should use the order you described.
