### ISSUE TITLE
运行examples下的py文件均出现interrupted by signal 11: SIGSEGV

### ISSUE THREAD

**Issue by RaymondTseng** [thunlp/OpenKE#153]
如题，运行examples下的py文件出现interrupted by signal 11: SIGSEGV
`Input Files Path : ./benchmarks/FB15K/
The toolkit is importing datasets.

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

**Comment by Una-zh** [comment]
我也遇到这个问题了，请问您解决了吗？

**Comment by Una-zh** [comment]
我是用IDE运行的，pycharm - preferences - build, execution, deployment - python debug，将PyQt compatible (auto)前面的勾去掉就好了。
