### ISSUE TITLE
How to write the results into the file to do grid search?

### ISSUE THREAD

**Issue by FFrankyy** [thunlp/OpenKE#155]
Hi,

I want to write the link prediction results into a file so that I can do the grid search, do you know how to do this? For current codes, I can only copy the results from the screen.

Thankx

**Comment by ShulinCao** [comment]
You can rewrite the codes in base/Test.h
https://github.com/thunlp/OpenKE/blob/5416886e35b375b8ce614d90742ec7c1a1e8a5dd/base/Test.h#L188
