### ISSUE TITLE
set_in_path not working if a / is not present at the end of the path

### ISSUE THREAD

**Issue by simonepri** [thunlp/OpenKE#157]
This works:
```python
con.set_in_path("./benchmarks/FB15K/")
```
This doesn't:
```python
con.set_in_path("./benchmarks/FB15K")
```

I think we should either fix such behaviour or clearly stating this in the readme since it may be a difficult problem to spot.

**Comment by THUCSTHanxu13** [comment]
We have added this information to the readme file. Thank you.
