### ISSUE TITLE
Confused about the meaning of test results

### ISSUE THREAD

**Issue by alittlealone** [thunlp/OpenKE#16]
Hi! I'm running the code following your instructions:
`python example_train_transe.py`
which runs perfectly. However, I'm having trouble understanding the results it gives:
`overall results:
left 245.622864 0.382235 0.173181 0.000000 
left(filter) 83.448372 0.579167 0.359415 0.000000 
right 161.250595 0.460615 0.228031 0.000000 
right(filter) 59.193935 0.631359 0.408847 0.000000
`
I'm not very familiar with C, so it's hard for me to understand your source code. So I'm having a very hard time figure out which number is mean rank, which number is hit@10, and why there are so many results. Can you kindly explain it for me? Thank you very much!

**Comment by THUCSTHanxu13** [comment]
For each line, there are Mean Rank, Hit@10, Hit@3, Hit@1

**Comment by alittlealone** [comment]
Thank you for your help!
