### ISSUE TITLE
我在尝试跑OpenKE demo（FB15K），想问下你的train,valid,test中都是正例还是也存在反例？

### ISSUE THREAD

**Issue by LETUTU** [thunlp/OpenKE#166]

**Comment by LETUTU** [comment]
2：我们的数据集只有train和test，并且train中一半为正例，一半为反例，请问这种情况可以怎样处理？

**Comment by THUCSTHanxu13** [comment]
知识图谱的数据都是正例，所有不在数据里面的三元组，模型通常都认为是负例。

**Comment by THUCSTHanxu13** [comment]
我感觉你要是训练集合里面有正例和负例，你可以在原来的损失函数上加上一项目，新的损失函数就是从你的数据里面采样正例，采负例，然后正例评分优于负面评分。这个你可以自己思考下

**Comment by LETUTU** [comment]
您的demo中没有用到predict_triple函数，我想加上去测试，可是尝试了很多都报错，想请问这个函数放在程序的哪处运行？
