### ISSUE TITLE
用model.vec.tf和embedding.vec.json测试模型的区别是什么

### ISSUE THREAD

**Issue by 673055938** [thunlp/OpenKE#168]
用model.vec.tf和embedding.vec.json测试模型的区别是什么

**Comment by 673055938** [comment]
找到答案了，在问题“请问该如何读取model.vec.tf？”中作者有回答

**Comment by 673055938** [comment]
(1）代码是直接读入tensorflow的存储结果的（2）代码是读入json格式的。

**Comment by THUCSTHanxu13** [comment]
没有区别，就是存储方式不同
