### ISSUE TITLE
L2-norm constraints and other soft constraints

### ISSUE THREAD

**Issue by Chrixtar** [thunlp/OpenKE#169]
Hi,

you have not answered the original question from https://github.com/thunlp/OpenKE/issues/52#issue-326373503. Although you added the option to set a weight_decay (I am referring to the PyTorch implementation), you have not set it in the examples (e.g. in TransE). Have you set it for your evaluation?

Furthermore, it seems to me that you have not considered other soft constraints like the C parameter in TransH (pointed out by https://github.com/thunlp/OpenKE/issues/95#issue-368480736), which is required in order to have the translation vector ON the hyperplane of the certain relation. How do you justify this decision?

I would like to read answers to both questions.
Thank you.

**Comment by THUCSTHanxu13** [comment]
We have tried various methods to add normalization operations for TransX models. And finally, the current normalization implementation can achieve the best performance on FB15K237 and WN18RR. Maybe you can try other constraints. If you achieve better results, please pull requests for us : )
