### ISSUE TITLE
TransD模型中relation的维度问题

### ISSUE THREAD

**Issue by rootlu** [thunlp/OpenKE#17]
TransD模型中，relation和entity的向量维度是不同的，但是代码里relation和entity的维度大小定义是一样的，这样对话，TransD应该就和TransE没有太大区别了吧，所以想请问一下这块代码是否有问题？

**Comment by shelly-github** [comment]
可以通过con.set_ent_dimension()和con.set_rel_dimension()分别设置entity和relation的维度；
TransD中entity和rel的维度不一定要相同，但原论文里调参发现entity和relation维度相同效果最好
