### ISSUE TITLE
how to speed up the valid function

### ISSUE THREAD

**Issue by Alexzsh** [thunlp/OpenKE#170]
Now the valid function need to calculate ValidTotal*(2(head and tail)*2(getBatch and valid)*EntityTotal) more times, it would cost 40mins, if you have 10 thousands triples.( i7-6950X CPU)
how to speed up this process?
Thanks

**Comment by THUCSTHanxu13** [comment]
Maybe you can use the type constraining file to select much fewer entities rather than all entities in KGs.
