### ISSUE TITLE
TransH predict bug (PyTorch)

### ISSUE THREAD

**Issue by Chrixtar** [thunlp/OpenKE#172]
Hi,

can someone explain to me, why you don't project the head and tail entities of test triples onto the relation specific hyperplane inside of the predict method of TransH?
You just calculate the score for the plane entity embeddings and the distance vector (on the hyperplane) of the relation.
For me this looks like an obvious bug in the PyTorch implementation.
Especially in comparison to your TransD implementation, where you project the entities at first in the predict method.

Best regards
Chrixtar

**Comment by ShulinCao** [comment]
Thank you for your feedback. I have fixed the bug.
