### ISSUE TITLE
Probability of entity/relation

### ISSUE THREAD

**Issue by akastrin** [thunlp/OpenKE#173]
I use a following chunk of code to evaluate presence of entities/relations:

```
import config
import models

'''step 1: Load the dataset and embedding files'''
con = config.Config()
con.set_in_path("./benchmarks/test-data/")
con.set_import_files("./TransE-results/model.vec.tf")    
con.set_work_threads(16)
con.set_dimension(100)

'''step 2: init the model'''
con.init()
con.set_model(models.TransE)

'''step 3: perform your operation'''
con.predict_head_entity(1928, 1, 5)
con.predict_tail_entity(0, 1, 5)
con.predict_relation(0, 1928, 5)
con.predict_triple(0, 1928, 1)
```

I wonder how to compute probability of a given head, tail, or relation. Thanks for any pointer.

**Comment by THUCSTHanxu13** [comment]
You can use the interface in the config.py:

def predict_head_entity(self, t, r, k):
      ...

def predict_tail_entity(self, h, r, k):
      ...

The information can be found from https://github.com/thunlp/OpenKE/blob/master/config/Config.py
