### ISSUE TITLE
loss value is nan always

### ISSUE THREAD

**Issue by msaasm71** [thunlp/OpenKE#175]
hi,
I use ComplEx model on my data 
I create data like examples and model start to training but loss value is nan always.
why?

**Comment by ShulinCao** [comment]
Maybe you need to tune the parameters for your own data, since the parameters in examples are for the standard datasets.

**Comment by kavinduchamiran** [comment]
Check your relations2id.txt 
it should contain integers only
mine contained textual ids also and once i encoded them into integers, nan error went away.

**Comment by msaasm71** [comment]
I use this data on [https://github.com/ttrouill/complex](url) GitHub and can correctly be trained
and I check relation2id.txt and relation's ids is an integer.

**Comment by kavinduchamiran** [comment]
see if all 5 files (train, test, valid, entity, relation) are available in right locations. python paths are relative so the location you are executing python3 train_model_code.py matters
