### ISSUE TITLE
about pytorch branch version used in cpu-only environment

### ISSUE THREAD

**Issue by Ling19871017** [thunlp/OpenKE#176]
first of all, openKE is quite useful, especially it offers pytorch version. but there is one problem that i've noticed which is that when i was trying to train a model in a cpu-only environment it threw out an exception saying "AssertionError: Torch not compiled with CUDA enabled", i think that's because  you haven't implemented the cpu version, right?
logs as follow:
[root@iZ8vbgwm2px6ajt8qo9f0yZ OpenKE]# python example_train_transe.py 
Input Files Path : ./benchmarks/FB15K/
The toolkit is importing datasets.
The total of relations is 1345.
The total of entities is 14951.
The total of train triples is 483142.
The total of test triples is 59071.
The total of valid triples is 50000.
Initializing training model...
/usr/share/anaconda3/lib/python3.7/site-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
/root/OpenKE/models/TransE.py:19: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(self.ent_embeddings.weight.data)
/root/OpenKE/models/TransE.py:20: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(self.rel_embeddings.weight.data)
Traceback (most recent call last):
  File "example_train_transe.py", line 26, in <module>
    con.set_train_model(TransE)
  File "/root/OpenKE/config/Config.py", line 291, in set_train_model
    self.trainModel.cuda()
  File "/usr/share/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/share/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/share/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/usr/share/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/share/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/usr/share/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

i wanna ask what i should do? should i modify the code by myself or you will develop an new version can either adapt the cpu or gpu enviroment? thanks a lot

**Comment by ShulinCao** [comment]
I have added the cpu choice, just use set_use_gpu  and have a try!

**Comment by Ling19871017** [comment]
Hi, team THUNLP
thank you very much for fixing the problem, now I can deploy my application on a cpu-enabled environment.
Your Sincerely,
Coby
A developer





------------------ 原始邮件 ------------------
发件人: "Shulin Cao"<notifications@github.com>;
发送时间: 2019年6月30日(星期天) 晚上11:46
收件人: "thunlp/OpenKE"<OpenKE@noreply.github.com>;
抄送: "小露宝"<863018396@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [thunlp/OpenKE] about pytorch branch version used in cpu-onlyenvironment (#176)




I have added the cpu choice, just use set_use_gpu  and have a try!
