### ISSUE TITLE
model.vec.tf is not saved

### ISSUE THREAD

**Issue by Yuminzhou** [thunlp/OpenKE#178]
![image](https://user-images.githubusercontent.com/22050071/60266809-6b027280-991b-11e9-985f-276c77f9706b.png)

Hi, I just run the "example_train_transe.py", but only the json, meta, index files are generated in the res folder, but the vec.tf model file is not generated. 

Can anyone kindly help? Thank you!

**Comment by THUCSTHanxu13** [comment]
Maybe you save the embeddings with the name "embedding2" or "model2" ... or there may be some files in the folder, the system automatically rename the new files  "embedding2" and "model2"
