### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by luluforever** [thunlp/OpenKE#180]
在Centos上面运行example_train_transe.py出现以下下错误：
OSError: /data/KE/OpenKE/release/Base.so: invalid ELF header
这是怎么回事？

**Comment by luluforever** [comment]
已经解决，忘记运行这个了：bash make.sh

**Comment by TuanMinhLe** [comment]
I have the same problem:
OSError: /home/tuanminhle/Desktop/Data science/GitHub/OpenKE/release/Base.so: invalid ELF header

**Comment by ShulinCao** [comment]
@TuanMinhLe Try the command `bash make.sh` ?

**Comment by TuanMinhLe** [comment]
@ShulinCao I fixed the problem, thank you

**Comment by stupidoge** [comment]
@ShulinCao 因为一些原因，我不能直接git安装。我把我电脑安装好的openke的文件夹复制粘贴到我的目标代码中，想要当作内地的源码库进行import。其中openke文件包括了：base, config, data, module, release, __pycache__, make.sh, __init__.py
但是运行的时候报出了一样的错误，不知道能否帮忙解答一下？感谢🙏
