### ISSUE TITLE
New dataset

### ISSUE THREAD

**Issue by trbn** [thunlp/OpenKE#183]
Hi
I have prepared a dataset in my language. I followed steps in readme file, but I get segmentation error.
I commented the statements for calling link prediction and classifiction and I have run just for training. I could run but after iterations I got segmentaion error in one line, whereas if I want to run for link prediction there is no running even training.

**Comment by ShulinCao** [comment]
You need to run the script OpenKE/benchmarks/FB15K/n-n.py to generate the type_constraint.txt file.

**Comment by trbn** [comment]
Dear Shulin,
Many thanks for your response. It war great help. I have run n-n.py and the files are generated. But the problem is remained.  I do not have two neg files. The problem is not related to those files? If it is, how I can generate them?

**Comment by ShulinCao** [comment]
It's ok that you miss the two neg files. The problem is not related to those files. You can run for training and there is problem with test, right?

**Comment by trbn** [comment]
I think so

**Comment by trbn** [comment]
Dear ShulinCao

I have changed my train2id and test2id after that I get segmentation fault. I had problem with testing, but embedding problem added. Please help me to run the models. If it is possible, I can send you my dataset.
Many thanks in advance

**Comment by trbn** [comment]
Dear ShulinCao

I have changed my train2id and test2id after that I get segmentation fault. I had problem with testing, but embedding problem added. Please help me to run the models. If it is possible, I can send you my dataset.
Many thanks in advance

**Comment by THUCSTHanxu13** [comment]
If you can share your dataset, please email cst_hanxu13@163.com.

**Comment by trbn** [comment]
Ofcourse. I have sent my dataset.
