### ISSUE TITLE
code comprehension issue:con.set_in_path("./benchmarks/FB15K/")

### ISSUE THREAD

**Issue by Kevin-chen-sheng** [thunlp/OpenKE#184]
con.set_in_path("./benchmarks/FB15K/")
Why the program can get the three file which are entity2id.txt,relation2id.txt,train2id.txt respectively by above code?

**Comment by ShulinCao** [comment]
https://github.com/thunlp/OpenKE/blob/425342ab2d999f0726c376449e18623388b4b892/base/Reader.h#L30

**Comment by Kevin-chen-sheng** [comment]
Thank you very much

**Comment by Kevin-chen-sheng** [comment]
![image](https://user-images.githubusercontent.com/52196486/61775925-84b8ac00-ae2c-11e9-9e6c-d31766ce3e27.png)
Why is train2id.txt such a construction?Seems to be intentional.

**Comment by ShulinCao** [comment]
you can read the readme.

**Comment by Kevin-chen-sheng** [comment]
![image](https://user-images.githubusercontent.com/52196486/62128870-f058b880-b307-11e9-8f36-bda6fad8db0d.png)
This error has occurred，，I assigned 12G of memory to the virtual machine.But still report this error
