### ISSUE TITLE
Undefined name 'conR' in train_transr_WN18RR.py

### ISSUE THREAD

**Issue by cclauss** [thunlp/OpenKE#186]
This variable is used before it is defined.

[flake8](http://flake8.pycqa.org) testing of https://github.com/thunlp/OpenKE on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./examples/train_transr_WN18RR.py:31:93: F821 undefined name 'conR'
parameters["transfer_matrix"] = np.array([(np.identity(50).reshape((50*50))) for i in range(conR.get_rel_total())])
                                                                                            ^
1     F821 undefined name 'conR'
1
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by THUCSTHanxu13** [comment]
I have fixed this bug. Please try it again.

**Comment by cclauss** [comment]
Testing in #189 ...

**Comment by Samuel123-hub** [comment]
> 我已修复此错误。请再试一次。

大佬，我在运行Traansr模型时出现错误，segmentation fault(core dump)，怎么解决？
