### ISSUE TITLE
How to get Embedding?

### ISSUE THREAD

**Issue by currenttime** [thunlp/OpenKE#187]
How to get or print the Embedding matrix for entity and relation? I want to pretrain KG by OpenKE, and get the input matrix for CNN.

**Comment by THUCSTHanxu13** [comment]
In the config code Config.py (https://github.com/thunlp/OpenKE/blob/master/config/Config.py), the function "get_parameter_lists" can return the parameter name list in a KE model, and "get_parameters_by_name" and "get_parameters" can return the model parameters by the parameter names.
