### ISSUE TITLE
question about prediction on pytorch vers

### ISSUE THREAD

**Issue by shenme7** [thunlp/OpenKE#192]
Hi, I have a quesion about prediction. I saw you mentioned on readme the fuction predict_head_entity.
def predict_head_entity(self, t, r, k):
	r'''This mothod predicts the top k head entities given tail entity and relation.

	Args: 
		t (int): tail entity id
		r (int): relation id
		k (int): top k head entities

	Returns:
		list: k possible head entity ids 	  	
	'''
	self.init_link_prediction()
	if self.importName != None:
		self.restore_tensorflow()
	test_h = np.array(range(self.entTotal))
	test_r = np.array([r] * self.entTotal)
	test_t = np.array([t] * self.entTotal)
	res = self.test_step(test_h, test_t, test_r).reshape(-1).argsort()[:k]
	print(res)
	return res
But, there is no function nit_link_prediction() on pytorch version Config.py file. Could you please help me about it?

**Comment by chenweize1998** [comment]
Sorry. It seems that we didn't implement this function in our PyTorch version. We will fix it later. Right now, you can modify the `link_prediction` function to get the top k entities.

To be clear, the code of `link_prediction` is 
```python
def link_prediction(self):
    print("The total of test triple is %d" % (self.testTotal))
    for i in range(self.testTotal):
        sys.stdout.write("%d\r" % (i))
        sys.stdout.flush()
        self.lib.getHeadBatch(self.test_h_addr, self.test_t_addr, self.test_r_addr)
        res = self.test_one_step(
            self.testModel, self.test_h, self.test_t, self.test_r
        )
        self.lib.testHead(res.__array_interface__["data"][0])

        self.lib.getTailBatch(self.test_h_addr, self.test_t_addr, self.test_r_addr)
        res = self.test_one_step(
            self.testModel, self.test_h, self.test_t, self.test_r
        )
        self.lib.testTail(res.__array_interface__["data"][0])
    self.lib.test_link_prediction()
```

The two `res` returned by test_one_step are scores returned by the model (unsorted). You can sort  `res` to get the top k result.
