### ISSUE TITLE
Segmentation fault (core dumped) after modify the entity and relation id

### ISSUE THREAD

**Issue by caoh18** [thunlp/OpenKE#193]
Hello, I am trying to uniform the entity and relation embedding so I changed the relation id (plus the number of entities 14541). So I get 0,1,2,3...,14540 for entities and 14541,14542, ...,14777 for relations in datatset. But after I changed the datatset and embedding layer I got a error "Segmentation fault (core dumped)". I am wondering if there is any code we need to change after changing the id? I am really upset now.
Thanks in advance!!!

**Comment by chenweize1998** [comment]
By default, we assume that the user will provide **BOTH** relation2id.txt and entity2id.txt in the dataset directory.  I don't quite understand what "uniform the entity and relation embedding" means. Could you explain your motivation? We may help to find a solution.
