### ISSUE TITLE
hyperparameters for pytorch version to achieve best performance

### ISSUE THREAD

**Issue by caoh18** [thunlp/OpenKE#198]
Hi, I notice that you provide different hyperparameter settings for tensorflow version code for different models and datasets in the ./examples fold to achieve best performance (like train_transe_FB15K237.py). But for Pytorch version the hyperparameter settings in the ./examples fold are all the same. When I try to use tensorflow version's hyperparameter setting for Pytorch version code directly, I get very bad performance. I want to ask if there are hyperparameter settings for Pytorch code to achieve best performance on datasets like FB15k237 and WN18RR? (at least reasonable performance)

**Comment by chenweize1998** [comment]
Can you post your training script and the final result? As for the best hyperparameter, we are sorry we haven't tried different hyperparameters for PyTorch version.

**Comment by THUCSTHanxu13** [comment]
I have implemented the new version of OpenKE-PyTorch, and provide the hyperparameters to reach great results on the benchmark datasets (https://github.com/thunlp/OpenKE/tree/OpenKE-PyTorch/examples).
