### ISSUE TITLE
存在拼写错误

### ISSUE THREAD

**Issue by kepsail** [thunlp/OpenKE#199]
https://github.com/thunlp/OpenKE/blob/b01b644c00f8fdf48617df9f39f26868bae16d99/config/Config.py#L113

在分支 OpenKE-PyTorch /config/Config.py 第113行，好像把‘alpha’ 写成立 'alpah'

**Comment by THUCSTHanxu13** [comment]
已解决，谢谢您的发现！我们也有新版本的pytorch实现，您也可以试用一下，再次感谢！
