### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by yuchenlin** [thunlp/OpenKE#2]
Dear THUNLP,

I installed OpenKE successfully but it reports segmentation fault when I run example.py. 

> ~/OpenKE$ python example.py
> Input Files Path : ./data/FB15K/
> Output Files Path : ./data/FB15K/
> The toolkit is importing datasets.
> Segmentation fault (core dumped)

**Comment by THUCSTHanxu13** [comment]
Because there are no data sets in the folder "./data". You need to change #con.set_in_path("./data/FB15K/")# to your own data path, such as #con.set_in_path("./benchmarks/FB15K/")#.

**Comment by asdassZY** [comment]
Hi I have loaded the dataset FB15K and WN18 as you suggested, but when I run example.py, it reports error:
 `Traceback (most recent call last):
  File "example.py", line 5, in <module>
    con = config.Config()
  File "/home/zhang_yan/work/OpenKE/config/Config.py", line 12, in __init__
    self.lib = ctypes.cdll.LoadLibrary("./release/Base.so")
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./release/Base.so: invalid ELF header`

**Comment by THUCSTHanxu13** [comment]
You need to compile C++ files first. You can try to run make.sh before you run example.py.

**Comment by yuchenlin** [comment]
We have already done this following the instruction in the readme.

**Comment by asdassZY** [comment]
Hi, it works after we only changed the content in the "con.set_in_path" to "./benchmark/FB15K/", previously we changed both "in_path" and "out_path". Thanks
