### ISSUE TITLE
弱问下，把knowledge Embedding之后最直接的做的inference是做什么？

### ISSUE THREAD

**Issue by guotong1988** [thunlp/OpenKE#20]
举个小例子就更好了，多谢多谢！！

**Comment by guotong1988** [comment]
看了一下TransE的test的代码，
如果testHead，就在所有59071个测试的三元组里，看看预测的Head是不是最接近给定（t-r），每判断一个测试三元组，需要遍历14951个实体；
如果testTail，就在所有59071个测试的三元组里，看看预测的Tail是不是最接近给定（h+r），每判断一个测试三元组，需要遍历14951个实体；

**Comment by THUCSTHanxu13** [comment]
所以实体多的话，测试非常慢
