### ISSUE TITLE
GPU memory consumption & paralle training

### ISSUE THREAD

**Issue by linfeng-du** [thunlp/OpenKE#201]
When using TransE to train model on GPU, I found that one small knowledge graph(9810, 6, 132489) consums approximately 30GiB of memory, which is about the same with the memory consumption training a larger knowledge graph(2455389, 14085, 6841723). Is the memory consumption non-relavent with the size of KGs in certain ranges? (Tuple stands for (sizeof(entity), sizeof(relation), sizeof(training edges)))

Besides(more of a tensorflow question), is there a way to train on different GPUs asynchronously? Currently I've try to assign GPUs by settting tf.deveices() and CUDA_VISIBLE_DEVICES but failed.

**Comment by guotong1988** [comment]
mark

**Comment by parvathysarat** [comment]
I have the same issue, trying to train on colab and it keeps crashing at the beginning of training. Did you solve this?
(I tried with 1000 edges and it still seems to be crashing.)

**Comment by linfeng-du** [comment]
> I have the same issue, trying to train on colab and it keeps crashing at the beginning of training. Did you solve this?
> (I tried with 1000 edges and it still seems to be crashing.)

I solve this problem by adding
`tf.ConfigProto(allow_soft_placement=True)`
when creating session. Then it will allocate GPU memory dynamically.
