### ISSUE TITLE
How to compute entity similarity for TransD?

### ISSUE THREAD

**Issue by Kalethars** [thunlp/OpenKE#202]
The original paper says using cosine similarity of projection vectors, but indeed projection vectors are computed based on relation transfers which is not available in similarity computing.

Also entity similarity for TransH is calculated by manhattan distance between two normed entity embedding vectors right?

**Comment by THUCSTHanxu13** [comment]
The similarity for entities of TransE, TransH, TransD are computed by the same method, directly calculating l1/l2 distance between two entity embeddings.
