### ISSUE TITLE
How to use Wikidata pre-trained model for transe

### ISSUE THREAD

**Issue by moh-yani** [thunlp/OpenKE#203]
I want to use transe wikidata pre-trained model in our system, especially in test run process . However I have not found what we should do. If I want to implement this code https://github.com/thunlp/OpenKE/blob/master/example_test_transe.py then how I can configure that file code in use of entity2vec.bin and relations2vec.bin?

Here, I enclose the example source code of example_test_transe.py:

import config
import models
import tensorflow as tf
import numpy as np
import json
import os
os.environ['CUDA_VISIBLE_DEVICES']='7'
# (1) Set import files and OpenKE will automatically load models via tf.Saver().
con = config.Config()
con.set_in_path("./benchmarks/FB15K/")
#con.set_test_link_prediction(True)
con.set_test_triple_classification(True)
con.set_work_threads(8)
con.set_dimension(100)
con.set_import_files("./res/model.vec.tf")
con.init()
con.set_model(models.TransE)
con.test()
# sesuai petunjuk untuk proses testing data hanya sampai sini

con.predict_head_entity(152, 9, 5)
con.predict_tail_entity(151, 9, 5)
con.predict_relation(151, 152, 5)
con.predict_triple(151, 152, 9)
con.predict_triple(151, 152, 8)

What part so I can use the transe wikidata pre-trained models?

**Comment by mhmgad** [comment]
As for my attempt, all you need is to read the bin files using numpy and assume that the rows are the entity ids (Zero-based) this is the code I am using

```
vector_size= 100 or 50
embedding_vec = np.memmap(embedding_filename ,dtype='float32',mode='r')
# reshape as (n,vector_size)
embedding_vec=embedding_vec.reshape(int(embedding_vec.shape[0]/vector_size),vector_size)
# for entity in row 3
vector_3= embedding_vec[3]

```

**Comment by moh-yani** [comment]
Nice mhmgad, I can get the entity vector in row 3. So, how can i implement head or tail prediction from that? 

con.predict_head_entity(981, 13, 5) # (tail, relation, top-k)

for instance

**Comment by mhmgad** [comment]
For transE, you can use the equation in the paper If I remember correctly it is t=h-r or something similar. Have you tried the code described in the readme file. Just instantiate the vectors from the loaded matrix and you should be good to go.

**Comment by moh-yani** [comment]
Great mhmgad...

Yes, that's correct. To predict tail we can use t=h-r. I also already read that paper. Let's I guess, for doing that I also need to read the relation@vec.bin using numpy as aforementioned above, then I can use predict_head_entity function. So for predict the head of ((981, 13, 5) I can write this:

ent_filename = "entity2vec.bin"
rel_filename = "relation@vec.bin"

vector_size= 100
embedding_vec = np.memmap(ent_filename ,dtype='float32',mode='r')
# reshape as (n,vector_size)
embedding_vec=embedding_vec.reshape(int(embedding_vec.shape[0]/vector_size),vector_size)
# for entity in row 981
vector_981= embedding_vec[981]

embedding_vec2 = np.memmap(rel_filename ,dtype='float32',mode='r')
# reshape as (n,vector_size)
embedding_vec2=embedding_vec2.reshape(int(embedding_vec2.shape[0]/vector_size),vector_size)
# for relation in row 13
vector_13= embedding_vec2[13]

con.predict_head_entity(vector_981, vector_13, 5) # (tail, relation, top-k), stated in readme file

Is that correct?

**Comment by moh-yani** [comment]
However I still get error:
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

my code is:
ent_filename = './transe/entity2vec.bin'
rel_filename = './transe/relation2vec.bin'
embedding_vec_ent = np.memmap(ent_filename ,dtype='float32',mode='r')
embedding_vec_rel = np.memmap(rel_filename ,dtype='float32',mode='r')
vector_ent= embedding_vec_ent[981]
vector_rel= embedding_vec_rel[13]
con.predict_head_entity(vector_ent, vector_rel, 20) # (tail, relation, top-k)
vector_head = embedding_vec_ent[366]
vector_tail = embedding_vec_ent[981]
vector_relation = embedding_vec_rel[69]
con.predict_triple(vector_head, vector_tail, vector_relation) # (head, tail, relation)

How should I do next?

**Comment by moh-yani** [comment]
However I still get error:
IndexError: only integers, slices (:), ellipsis (...), numpy.newaxis (None) and integer or boolean arrays are valid indices

my code is:
ent_filename = './transe/entity2vec.bin'
rel_filename = './transe/relation2vec.bin'
embedding_vec_ent = np.memmap(ent_filename ,dtype='float32',mode='r')
embedding_vec_rel = np.memmap(rel_filename ,dtype='float32',mode='r')
vector_ent= embedding_vec_ent[981]
vector_rel= embedding_vec_rel[13]
# predict a entity head
con.predict_head_entity(vector_ent, vector_rel, 20) # (tail, relation, top-k)
vector_head = embedding_vec_ent[366]
vector_tail = embedding_vec_ent[981]
vector_relation = embedding_vec_rel[69]
# predict triple
con.predict_triple(vector_head, vector_tail, vector_relation) # (head, tail, relation)

How should I do next?

**Comment by MuhibKhan** [comment]
Hello @mhmgad. Will you please guide me. I want to check the Head prediction and Tail prediction at (Hits@10) of FB15k dataset. How can I check the different types of relation like 1-to-1, 1-to-N, N-to-1 and N-to-N of FB15k dataset?
Thanks for anticipation

**Comment by ronghui19** [comment]
If i just want to get embedding of training data, how am i supposed to do it?

**Comment by swhnu** [comment]
@moh-yani  Hello, I am facing the same problem. I have read your code and I guess the problem is that the (head, tail, relation) in con.predict_triple(head, tail, relation) should be the index of entity and relation rather than the vector. I have tried to use the equation in the paper to predict the top-k entity, but the speed is too slow. Have you solved this problem
