### ISSUE TITLE
新数据集和embedding导出

### ISSUE THREAD

**Issue by Yongquan-He** [thunlp/OpenKE#204]
您好，我想用您的transe代码拍下wn11数据集，我需要建四个2id文件，请问我是否需要用您的C++代码做下预处理，我看一下那里面大概是负采样什么的，还有我怎么在训练结束后得到实体和关系的embedding？感谢

**Comment by THUCSTHanxu13** [comment]
构建4个id的文件不需要使用我的C++代码，自己构建即可，第一步将所有的实体编号为0-n存在entity2id.txt，第二步将所有的关系编号为0-m存在relation2id.txt，第三步将train2id.txt, test2id.txt里的三元组都替换为刚才的编号即可，你看一下文件里的具体内容就知道了。

**Comment by THUCSTHanxu13** [comment]
新版本的pytorch实现的openke，每个model都有get_parameters()接口，你可以从 https://github.com/thunlp/OpenKE/blob/OpenKE-PyTorch/openke/module/BaseModule.py 里面看到。

tensorflow实现的openke，Config.py里有get_parameters()
你可以参考 https://github.com/thunlp/OpenKE/blob/OpenKE-Tensorflow1.0/config/Config.py

**Comment by Yongquan-He** [comment]
谢谢！！！

**Comment by sawyerfeng** [comment]
> 构建4个id的文件不需要使用我的C++代码，自己构建即可，第一步将所有的实体编号为0-n存在entity2id.txt，第二步将所有的关系编号为0-m存在relation2id.txt，第三步将train2id.txt, test2id.txt里的三元组都替换为刚才的编号即可，你看一下文件里的具体内容就知道了。

请问一定是从零开始递增嘛?
