### ISSUE TITLE
Supported PyTorch version(s)

### ISSUE THREAD

**Issue by adaruna3** [thunlp/OpenKE#205]
Hi all,

Is it possible to document the version(s) of PyTorch tested/supported? As PyTorch is actively being developed, it would help to know which version of PyTorch OpenKE is being developed on.

If I overlooked this, I apologize. I have not found it in the documentation or previous issues.

Thanks,
Angel

**Comment by THUCSTHanxu13** [comment]
The current openke-pytorch can support the current PyTorch versions (e.g., 1.1 1.2 1.3 1.4)

**Comment by THUCSTHanxu13** [comment]
Note that I have used tqdm in the package, and tqdm can just work for python3. Hence, if you want to run the package with python2, you have to remove all code related to tqdm by yourself.
