### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by YichengDWu** [thunlp/OpenKE#206]
run `!bash make.sh` returns
`/usr/bin/ld: cannot open output file ./release/Base.so: No such file or directory
collect2: error: ld returned 1 exit status`

**Comment by kahy-shen** [comment]
I meet the same question, have you addressed it?

**Comment by YichengDWu** [comment]
> 
> 
> I meet the same question, have you addressed it?

Note that it was released yeasterday so maybe incomplete

**Comment by chenweize1998** [comment]
Sorry for that. Before we fix this problem, you can manually create a new directory 'release' under 'openke' directory before you run `bash make.sh`
```
cd openke
mkdir release
bash make.sh
```
We will fix it soon. Many thanks.

**Comment by chenweize1998** [comment]
Already fixed. Closing this issue.
