### ISSUE TITLE
DistMult Classification Loss Function

### ISSUE THREAD

**Issue by adodge** [thunlp/OpenKE#208]
Do you have a reference for the logistic loss function used in this implementation of DistMult?  I note that in the original paper (Yang et al 2015, section 3.3 "Parameter Learning") they describe it as having a margin-based ranking loss function.  Is there a followup paper that describes this change, or is there a practical reason for it?

Thank you for your work on OpenKE.  It's very useful having an implementation to look at for these models.

Alex

**Comment by THUCSTHanxu13** [comment]
Though the original setting in Yang et al (2015) is a margin-based ranking loss function, the implementation of DistMult in the later papers adopts the logistic loss function as their baseline. From their experiments, you can find that adopting the logistic loss function  leads to better performance. The source code of ComplEx (https://github.com/ttrouill/complex/blob/master/efe/models.py) provide the  DistMult based on the logistic loss function.

**Comment by adodge** [comment]
Perfect!  Thank you.
