### ISSUE TITLE
中文数据集

### ISSUE THREAD

**Issue by wwwxmu** [thunlp/OpenKE#21]
请问有没有中文的数据集，比如COAE2016任务三的数据集？

**Comment by THUCSTHanxu13** [comment]
感觉你可以用wikidata的中文部分做一个，或者看看xlore这个图谱。一般论文里面用的数据貌似是没有纯中文的数据

**Comment by adzhua** [comment]
@wwwxmu 你好，你找到COAE2016任务三的数据集吗?能否提供下adzhua@163.com

**Comment by ZongWeiZhu** [comment]
> 请问有没有中文的数据集，比如COAE2016任务三的数据集？

请问你有任务三的解压码吗

**Comment by HWZX** [comment]
> > 请问有没有中文的数据集，比如COAE2016任务三的数据集？
> 
> 请问你有任务三的解压码吗

请问可以分享一下压缩包吗
