### ISSUE TITLE
The issues of the implementation for TransR.

### ISSUE THREAD

**Issue by ngl567** [thunlp/OpenKE#212]
Thank you for this open-source project. I have two questions when implementing TransR:
1. Once you use TransE as pretrain for TransR, the dimension of entity embeddings and relation embeddings should be the same, which will  be out of accord with the algorithm of TransR in the paper.
2. How many epochs should be set when pretraining TransE for TransR.

**Comment by THUCSTHanxu13** [comment]
Though TransR can be trained from scratch, the implementation of the original paper (https://github.com/thunlp/KB2E) trains TransR with the TransE pre-trained embeddings. 

For the epochs for pretraining TransE for TransR, you can set 500.
