### ISSUE TITLE
请问链接预测中的type_constrain参数是什么意思呢？

### ISSUE THREAD

**Issue by blldd** [thunlp/OpenKE#213]

**Comment by THUCSTHanxu13** [comment]
在readme的评测方式里面我写到过了

For those large-scale entity sets, to corrupt all entities with the whole entity set is time-costing. Hence, we also provide the experimental setting named "type constraint" to corrupt entities with some limited entity sets determining by their relations.

**Comment by THUCSTHanxu13** [comment]
大体就是测试的时候用一个小的实体集合来替换头尾实体而不是全部实体。具体小实体集合的生成方式是通过关系来确定的，给定(h,r,t)，所有r能够接上的尾实体构成这个实体集合，来替换t

**Comment by THUCSTHanxu13** [comment]
你可以看下链接的论文，不过一般不会用这个方式来评测

**Comment by blldd** [comment]
hi，您好，我想请教一个问题：
我用最新的代码，测试了train_transe_FB15K237.py，type_constrain=False的时候是正常的，当我设置type_constrain=True的时候就出现：
Segmentation fault (core dumped)
错误，我尝试用python重现c中的代码，并研究了testTail函数，发现这一段代码有点不太理解，能不能解释一下呢，感谢🙏

            if (type_constrain) {
                while (lef < rig && tail_type[lef] < j) lef ++;
                if (lef < rig && j == tail_type[lef]) {
                        if (value < minimal) {
                            r_s_constrain += 1;
                            if (not _find(h, j ,r)) {
                                r_filter_s_constrain += 1;
                            }
                        }
                }
            }
