### ISSUE TITLE
openke-pytorch: The embedding layer always reports an error“RuntimeError:index out of range”

### ISSUE THREAD

**Issue by Angelinaa** [thunlp/OpenKE#216]
The embedding layer always reports an error“RuntimeError: index out of range: Tried to access index 1124 out of table with 14540 rows. at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorEvenMoreMath.cpcpp:418”. The new and old version of openke-pytorch reports the same error.

**Comment by THUCSTHanxu13** [comment]
Because the underlying code is implemented with the library file thread.h (-pthtead), the library is for Liunx and OS X. I do not know if the thread can work stable for Windows. I suggest you try the package with Liunx.
