### ISSUE TITLE
Compute Head and Tail Prediction on FB15K dataset

### ISSUE THREAD

**Issue by MuhibKhan** [thunlp/OpenKE#217]
I want to check the Prediction Head and Prediction Tail (Hits@10) on different types of relation like 1-to-1, 1-to-N, N-to-1 and N-to-N of TransD model like the results mentioned in the paper. How can I perform the Head and Tail Prediction on 1-to-1, 1-to-N, N-to-1 and N-to-N of relations of FB15k dataset?

![TransD](https://user-images.githubusercontent.com/7377986/68865463-d4015000-072d-11ea-85f1-d401f8a5431b.png)

**Comment by drcdr** [comment]
To review, 
* The {1-1, 1-N, N-1, N-N} files are created via [n-n.py](https://github.com/thunlp/OpenKE/blob/OpenKE-PyTorch/benchmarks/FB15K237/n-n.py
), for each of the datasets.   Roughly, {train2id, valid2id, test2id} -> dictionaries -> {type_constrain.txt, test2id};  {test2id, f(dictionaries)} -> {1-1, 1-n, n-1, n-n}.txt.
* As a check: if you add up the number of triples (first line in the file) in 1-1.txt, 1-n.txt, n-1.txt, n-n.txt, they add up to the number of triples in test2id.txt.
* test2id.txt is used in Reader.h (see [here](https://github.com/thunlp/OpenKE/blob/OpenKE-PyTorch/openke/base/Reader.h#L170)).  So, if you replace test2id.txt with 1-1.txt, for instance...you'll get the results for 1-1.
* So, if you train a model, you can then run separate tests on {1-1,etc.} by changing Reader.h's "test2id.txt" to "1-1.txt", etc., recompiling, then running your test.

The best way to improve this would be to bring the n-n.py code into the base; then, the {1-1,1-n,n-1,n-n} statistics could be generated more flexibly.

You asked about FB15K, though.  There is no "train_transe_FB15K.py" in the repository right now.  I made an initial attempt on one of these with the new OpenKE_Pytorch, but couldn't match the performance of the old OpenKE_Pytorch.  So, reproducing the {1-1, etc.} results for FB15K will take a little more work there.

**Comment by MuhibKhan** [comment]
@drcdr I follow the same thing steps earlier. Major Thing which confuses me and I unable to understand, how I differentiate the Prediction of Head and Tail. For example, I change the test2id.txt in Reader.h with 1-1.txt and run it on my dataset. The result which I got after the train and test, what would it represent (prediction of head or prediction of tail)?

**Comment by MuhibKhan** [comment]
As you mentioned in your third point:

- test2id.txt is used in Reader.h (see here). So, if you replace test2id.txt with 1-1.txt, for instance...you'll get the results for 1-1.

That's the main concern. The output result belongs to which? Prediction of Head or Prediction of Tail?

**Comment by drcdr** [comment]
I think that's what left and right are (head and tail).  But I'm not 100% sure, you could look at the source code in base to check a little more closely.

**Comment by MuhibKhan** [comment]
I tried very hard after that I post the question. I look into it again from start, may be I can find something. Anyway Thank you so much Sir. Your helped me alot. I appreciate your help.

**Comment by THUCSTHanxu13** [comment]
Just rename the file '1-1.txt' with 'test2id.txt', you can achieve the performance of 1-to-1 settings, the output results include both  head prediction, tail prediction, and average prediction.
