### ISSUE TITLE
How to use embedding to compute triplet score for RotatE?

### ISSUE THREAD

**Issue by zhongpeixiang** [thunlp/OpenKE#219]
Regarding RotatE, I don't quite understand your training script about head-batch. Anyway, I have pretrained ent and rel embeddings without understanding it.

Now I want to figure out that given a triplet: h [x1, ..., x200], r=[r1, ..., r100] and t=[y1, ..., y200], how to compute its score?

A detailed description will be much appreciated.

**Comment by THUCSTHanxu13** [comment]
For the original negative sampling, it will randomly replace head or tail entities. If the batch size if 200 and the negative example number is 25, the triplet for models is head-entity[200 * 25], relation[200 * 25], tail-entity[200 * 25]

**Comment by THUCSTHanxu13** [comment]
For head-batch, it will just replace tail entity for each triple.  If the batch size if 200 and the negative example number is 25, the triplet for models is head-entity[200], relation[200], tail-entity[200 * 25]. It will require less GPU memory during training models, and accelerate training.
