### ISSUE TITLE
Add a license to OpenKE?

### ISSUE THREAD

**Issue by weronica** [thunlp/OpenKE#22]
Have you considered adding a license to your code? Without an explicit license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work ([source](https://help.github.com/articles/licensing-a-repository/)). Since you've created an open-source project, would you consider adding an open-source license?

GitHub created [choosealicense.com](https://choosealicense.com/) to help repo managers select the right license. They also created the [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project), which goes more in-depth on the pros/cons of each license for different kinds of open-source projects. 

The [MIT license](https://choosealicense.com/licenses/mit/) would be a great choice because it’s short, very easy to understand, and allows anyone to do anything so long as they keep a copy of the license, including your copyright notice. You’ll be able to release the project under a different license if you ever need to.

Thanks in advance!

**Comment by THUCSTHanxu13** [comment]
I have added the MIT license file for our toolkit.

**Comment by weronica** [comment]
Thank you!
