### ISSUE TITLE
Are the configs in examples/ the best? Or could you provide them?

### ISSUE THREAD

**Issue by ShawXh** [thunlp/OpenKE#220]
We've tested the code on the benchmarks but found that the configs in the examples didn't yield good results.. Maybe the configs are not the best, what are the best configs? can you provide them?

**Comment by THUCSTHanxu13** [comment]
I want to know which model you have run with our example code

**Comment by THUCSTHanxu13** [comment]
Our example code can achieve comparable results or better results as compared with the original paper.
