### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'config'

### ISSUE THREAD

**Issue by ronghui19** [thunlp/OpenKE#222]
Traceback (most recent call last):
  File "get_embedding.py", line 14, in <module>
    con.set_model(TransE)
  File "/data/ronghui_data/OpenKE/config.py", line 313, in set_model
    self.trainModel = self.model(config = self)
TypeError: __init__() got an unexpected keyword argument 'config'

**Comment by THUCSTHanxu13** [comment]
I do not know which version you have used. Maybe you can give me more details about your code and package version

**Comment by juihsuanlee** [comment]
I have the same question, did you solve it?
