### ISSUE TITLE
Values of ent_embeddings are different when loaded from model.vec.tf than those from embedding.vec.json?

### ISSUE THREAD

**Issue by mhmgad** [thunlp/OpenKE#224]
When loading the saved model using the example read me file :

```
con = config.Config()
con.set_in_path("./benchmarks/FB15K/")
con.set_test_link_prediction(True)
con.set_test_triple_classification(True)
con.set_work_threads(4)
con.set_dimension(50)
con.init()
con.set_model(models.TransE)
con.import_variables("./res/model.vec.tf")
con.test() ```

Are different from those loaded by:

```
f = open("./res/embedding.vec.json", "r")
embeddings = json.loads(f.read())
f.close()
```

which one is correct?

**Comment by THUCSTHanxu13** [comment]
If you use the code "con.set_export_files("./res/model.vec.tf", 0)", you should use the code "con.set_import_files("./res/model.vec.tf")" to load the saved model.

**Comment by THUCSTHanxu13** [comment]
If you use the code "con.set_out_files("./res/embedding.vec.json")", you should use the following code to load the saved model:

f = open("./res/embedding.vec.json", "r")
content = json.loads(f.read())
f.close()
con.set_parameters(content)
