### ISSUE TITLE
ConvE的实现

### ISSUE THREAD

**Issue by gao-xiao-bai** [thunlp/OpenKE#225]
您给出了ConvE的测试结果，但是我并没有看到ConvE的实现代码，您可以分享一下吗？OpenKE-pytorch看起来并不适合1-N score

**Comment by Toni-Chan** [comment]
直接把ConvE的代码迁移到OpenKE试过了，尽管可以看到在训练，loss也在降低，但是测试成绩奇差。猜测是ConvE有特殊的训练模式或者测试模式

**Comment by THUCSTHanxu13** [comment]
这个我已经在尝试迁移了，原因是conve和tucker的训练模式都是对全体实体做bce loss的，不是negative sampling之后做bce loss，而且有label smoothing，所以你只是迁移模型效果会比较差，不出意外我最近会更新下这块内容

**Comment by mxuran** [comment]
请问好久可以更新呀？

> 这个我已经在尝试迁移了，原因是conve和tucker的训练模式都是对全体实体做bce loss的，不是negative sampling之后做bce loss，而且有label smoothing，所以你只是迁移模型效果会比较差，不出意外我最近会更新下这块内容

**Comment by ReadyTeresa** [comment]
> 这个我已经在尝试迁移了，原因是conve和tucker的训练模式都是对全体实体做bce loss的，不是negative sampling之后做bce loss，而且有label smoothing，所以你只是迁移模型效果会比较差，不出意外我最近会更新下这块内容

请问什么时候会更新ConvE的内容啊？

**Comment by quqxui** [comment]
请问更新了ConvE吗？
