### ISSUE TITLE
关于论文 OpenKE: An Open Toolkit for Knowledge Embedding 中提到的训练时间有疑惑

### ISSUE THREAD

**Issue by charlielin** [thunlp/OpenKE#227]
在论文中提到使用 OpenKE 在数据集 FB15K 上训练 TranseE 模型，只需要 266 秒（GPU，PyTorch）。而我使用 GitHub 的代码`train_transe_FB15K237.py`训练却需要一个小时。
![](https://tva1.sinaimg.cn/large/006tNbRwgy1gaid5gydgyj31gv0bijtz.jpg)
训练环境：
CPU: Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz 8 核心
GPU: GeForce GTX 1080
MEM: 32G

请问有可能造成这种差异的原因是什么？

**Comment by THUCSTHanxu13** [comment]
最直接的原因就是原来的模型negative的数量是1，我给出的脚本是25

**Comment by THUCSTHanxu13** [comment]
另外的话，跑图谱的时候CPU影响还挺大的，不是非常多并行多卡的情况下，Xeon其实比普通的I7差不少，我2年前在8卡的1080TI+Xeon E5的服务器上用单卡跑的时候，耗时是论文1070配置的耗时的2倍

**Comment by charlielin** [comment]
感谢回复^ ^
