### ISSUE TITLE
您好，pytorch所提供的example能够输出link prediction的结果，请问在代码中如何设置能够使其输出triple classification的结果呢？

### ISSUE THREAD

**Issue by Moringa9513** [thunlp/OpenKE#229]

**Comment by zzzAshui** [comment]
最后加一行tester.run_triple_classification(type_constrain = False)

**Comment by Moringa9513** [comment]
您好，首先感谢您的回复
按照您说的，我在最后一行加上tester.run_triple_classification(type_constrain = False)
但却出现了如下错误
TypeError: run_triple_classification() got an unexpected keyword argument 'type_constrain'
自己看了一下还是未能解决，想请问您，这个错误大概是什么原因呢
十分谢谢

**Comment by THUCSTHanxu13** [comment]
把 tester.run_link_prediction(type_constrain = True)改掉就成下面这个就行了

...
tester = Tester(model = transe, data_loader = test_dataloader, use_gpu = True)
acc, threshlod = tester.run_triple_classification()
print (acc)
...

抱歉抱歉，过完年我尽量把这些example和文档补全
