### ISSUE TITLE
Train Time Costs

### ISSUE THREAD

**Issue by dalinvip** [thunlp/OpenKE#230]
Hi, Thanks for your work.

I wonder to know the training time comparison of use C++ to implement some underlying operations and not use c++ to replace python.

**Comment by THUCSTHanxu13** [comment]
I have released PyTorchTrainDataLoader, which builds the dataloader with PyTorch, and compared this module with the original TrainDataLoader based on C++. When the number of the negative sampling process is more than 64, they have comparable sampling time. When the number is smaller than 64, the module based on C++ is much more efficient.

**Comment by THUCSTHanxu13** [comment]
Maybe you can have a try on your server.
