### ISSUE TITLE
What does this mean？

### ISSUE THREAD

**Issue by ysgncss** [thunlp/OpenKE#231]
Input Files Path : ./benchmarks/WN18RR/
The toolkit is importing datasets.

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by THUCSTHanxu13** [comment]
Is your computer system Windows?

**Comment by THUCSTHanxu13** [comment]
This wrong is that the system cannot find any files in the path "./benchmarks/WN18RR/"

**Comment by THUCSTHanxu13** [comment]
You can check your file path
