### ISSUE TITLE
Test data leakage when using type constraints

### ISSUE THREAD

**Issue by dschaehi** [thunlp/OpenKE#232]
It seems when generating type constraints triples in the test data are also involved. Isn't it then quite obvious that type constraints will help improve the performance of the models, because of this test data leakage?
Wouldn't it be better (and fairer) to only include the triples in the training data when generating type constraints?

https://github.com/thunlp/OpenKE/blob/12bfd9c68b911a9ce34cd6917cb1af884219f23f/benchmarks/FB15K237/n-n.py#L44-L59

**Comment by THUCSTHanxu13** [comment]
The type constraints are not one method to improve the performance of the models. It is just a test approach to reduce the numbers of candidate entities.

**Comment by THUCSTHanxu13** [comment]
In fact, data generated by n-n.py does not be used to train models. If you want to adopt this information for training your models, to run n-n.py on training triples is more suitable.

**Comment by dschaehi** [comment]
Oh I see. Thanks for the clarification @THUCSTHanxu13. 

it is weird though that the [QuatE](https://papers.nips.cc/paper/8541-quaternion-knowledge-graph-embeddings.pdf) paper reports about scores using type constraints, when using type constraints does not seem to contribute much to the interpretation of the performance of a model.
