### ISSUE TITLE
How to convert freebase IDs (/m/07s9rl0 ) to their corresponding entities ?

### ISSUE THREAD

**Issue by unmeshvrije** [thunlp/OpenKE#237]
I could not find relevant documentation in the repo or online.

**Comment by chenweize1998** [comment]
Try [this](https://drive.google.com/file/d/0B52yRXcdpG6MaHA5ZW9CZ21MbVk/view)

**Comment by unmeshvrije** [comment]
Thanks @chenweize1998 !
