### ISSUE TITLE
Relation prediction scores??

### ISSUE THREAD

**Issue by ahmeshaf** [thunlp/OpenKE#238]
Hi,

Is there a way I could calculate the relation prediction scores as part of the evaluation?

Thanks

**Comment by LiuYuemei111** [comment]
Hi，please refer to this https://github.com/thunlp/OpenKE/tree/OpenKE-PyTorch(old) 
![image](https://user-images.githubusercontent.com/19309481/134465450-37c8a141-e023-440e-95f9-1b5a27d96d9f.png)
