### ISSUE TITLE
Who can tell me the idea of negative sampling in this version?

### ISSUE THREAD

**Issue by Una-zh** [thunlp/OpenKE#239]
Who can tell me the idea of negative sampling in this version?

**Comment by ywfan617** [comment]
do you understand this idea of negative sampling? I need your help,Thank you!

**Comment by rlafraie** [comment]
Can you specify your question? 
Did you mean why each training sample match a multiple number of negative examples in the training procedure rather than a single negative one (like described in the papers of the baseline methods TransE, TransH, etc.?

**Comment by LiuYuemei111** [comment]
For details of negative sampling and its implementation, you can refer to the paper [OpenKE: An Open Toolkit for Knowledge Embedding](https://aclanthology.org/D18-2024/)

**Comment by LiuYuemei111** [comment]
> Who can tell me the idea of negative sampling in this version?

For details of negative sampling and its implementation, you can refer to the paper [OpenKE: An Open Toolkit for Knowledge Embedding ](https://aclanthology.org/D18-2024/)
