### ISSUE TITLE
如果能上传一份entity的真实数据的文件就好了

### ISSUE THREAD

**Issue by guotong1988** [thunlp/OpenKE#24]
现在是`/m/016qtt`这样的数据，
如果能对应到真实数据，就能有更直观的认识。
多谢多谢！

**Comment by THUCSTHanxu13** [comment]
这个是freebase的编号，现在freebase已经关闭不开放了。如果你要获取信息的话，一个方面你可以去wikidata或者dbpedia这种还活着的图谱上去找。另一个办法就是下freebase的dump，自己解析（https://developers.google.com/freebase/）。
