### ISSUE TITLE
oserror

### ISSUE THREAD

**Issue by ywfan617** [thunlp/OpenKE#241]
我在win10系统中使用OpenKE-Pytorch，在运行完bash make.sh之后，运行train_transd_FB15K237.py出现如下问题：OSError: exception: access violation writing 0x0000024FE7B3D8E0，请问怎么解决呢？

**Comment by WenXiuxiu** [comment]
Set the relative paths to the absolute paths

**Comment by LiuYuemei111** [comment]
目前版本许多功能是用C++实现的，其中有一些依赖包不支持在window系统上编译。建议你在linux平台上使用
