### ISSUE TITLE
Optimal hyper parameters for FB15K and WN18 for NEW OpenKE-Pytorch branch

### ISSUE THREAD

**Issue by rlafraie** [thunlp/OpenKE#242]
I just tried the hyper parameters from the FB15K example in the example file train_transe.py (PyTorch Old) which didn't work very well. 

Does anyone know the optimal hyper parameters for the new OpenKE-Pytorch branch?

Many Thanks in advance!

**Comment by LiuYuemei111** [comment]
The authors have provided the hyper-parameters of some models to achieve the state-of-the-art performace (Hits@10 (filter)) on FB15K237 and WN18RR.  These scripts can be founded in the folder [./examples/](https://github.com/thunlp/OpenKE/tree/OpenKE-PyTorch/examples)
