### ISSUE TITLE
Use countries datasets have segmentation fault

### ISSUE THREAD

**Issue by HagridThick** [thunlp/OpenKE#243]
i change countries to this project‘s required format，i can see this code read entities and relation，but it still got segmentation fault.

![在country上实验的代码](https://user-images.githubusercontent.com/7401689/77844971-7ef64000-71dd-11ea-82ba-72da62502d97.png)

the datasets likes that

![Snipaste_2020-03-29_16-52-40](https://user-images.githubusercontent.com/7401689/77845006-cda3da00-71dd-11ea-9a7f-19852300953a.png)
![Snipaste_2020-03-29_16-52-50](https://user-images.githubusercontent.com/7401689/77845008-cf6d9d80-71dd-11ea-85c8-d8aeaba556d2.png)

**Comment by liubingai** [comment]
@HagridThick  I converted my own data to the required format and met the same error (segmentation fault) as you. Really confused about it. Hope the authors can output more useful message for debugging file format.

**Comment by THUCSTHanxu13** [comment]
If you have N entities, their ids are from 0 to N-1. I will emphasize this again in the readme file.
