### ISSUE TITLE
关于三元组分类中threshlod的确定

### ISSUE THREAD

**Issue by wqh1234** [thunlp/OpenKE#244]
您好，请问threshlod值在验证集上是如何确定的呢，看代码部分没太读懂。

**Comment by THUCSTHanxu13** [comment]
Tester里的run_triple_classification(self, threshlod = None)在给定threshlod的情况下会根据threshlod计算acc，如果threshlod=None的话，会根据当前数据计算一个最好的threshold。可以开两个Tester，一个放入验证数据，一个放入测试数据。  放入验证数据的Tester调用run_triple_classification()获得验证集上的acc和threshold，然后放入测试数据的Tester调用run_triple_classification(threshold)按照验证集得到的threshold计算测试集的acc。

**Comment by wqh1234** [comment]
谢谢您的解答，我最近在研究一篇多模态知识图谱表示的论文，那篇论文的三元组分类思想也是根据验证集算出threshold，但是他似乎是为每一个关系构造出pairs，然后计算acc，最后得出的是每一个关系对应一个threshold，我对于这点比较疑惑，请问应该是整个验证集上得出一个threshold，还是每个关系对应一个threshold呢？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"SillyXu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月10日(星期五) 中午12:34
收件人:&nbsp;"thunlp/OpenKE"<OpenKE@noreply.github.com&gt;;
抄送:&nbsp;"weiqh"<250804486@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thunlp/OpenKE] 关于三元组分类中threshlod的确定 (#244)





 
Tester里的run_triple_classification(self, threshlod = None)在给定threshlod的情况下会根据threshlod计算acc，如果threshlod=None的话，会根据当前数据计算一个最好的threshold。可以开两个Tester，一个放入验证数据，一个放入测试数据。  放入验证数据的Tester调用run_triple_classification()获得验证集上的acc和threshold，然后放入测试数据的Tester调用run_triple_classification(threshold)按照验证集得到的threshold计算测试集的acc。

**Comment by THUCSTHanxu13** [comment]
其实每个关系定一个threshold也不是不合理，不同关系的尺度不太一样也合理。每个关系算一个threshold的话，你可能要修改下我的代码了，这段时间我有时间的话我就把这个加上去

**Comment by wqh1234** [comment]
谢谢您，期待您能加上去



---原始邮件---
发件人: "SillyXu"<notifications@github.com&gt;
发送时间: 2020年4月10日(周五) 下午3:23
收件人: "thunlp/OpenKE"<OpenKE@noreply.github.com&gt;;
抄送: "wqh1234"<250804486@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [thunlp/OpenKE] 关于三元组分类中threshlod的确定 (#244)




 
其实每个关系定一个threshold也不是不合理，不同关系的尺度不太一样也合理。每个关系算一个threshold的话，你可能要修改下我的代码了，这段时间我有时间的话我就把这个加上去

**Comment by mxuran** [comment]
@THUCSTHanxu13 在测试集上得到最好的threshold再按照这个去测试本身的话，是不是不太合理？如果开两个Tester的话，是不是要修改底层C/C++代码，如将Test.h中的test变为valid的，或者说将Reader.h读入的test改为valid？有没有只修改python就可以实通过验证集得到threshold的方法？期待您的回复，感谢！~
