### ISSUE TITLE
How to get embeddings file like word2vec?

### ISSUE THREAD

**Issue by yyHaker** [thunlp/OpenKE#246]
I use current OpenKE version to train my KG, the code is the same with the examples directory? How can I get embeddings file saved?
like the following format is below:
---------------------
entity1 1.2 2.3 3.4 0.5
entity2 1.2 2.3 3.4 0.4
entity3 1.2 2.3 3.4 0.4
...

**Comment by mistborn17** [comment]
I think the embeddings are present in the model file. You need to extract it from there.

**Comment by Toni-Chan** [comment]
OpenKE doesn't keep internal references from text words to embeddings. Just use torch.save() to the embeddings part of the model, and align them to the external "vocab2id" list if present.

**Comment by mfsadi** [comment]
Create this function in your model.py (e.g, distmult.py ) and call it after training. I don't know if this saves the best model or not. It is based on the previous version of OpenKE
```python
def save_emb(self):   
	f = open("..model_out.json", "w")
	param_dict=self.state_dict()
	mode="list"
	for param in param_dict:
		param_dict[param] = param_dict[param].cpu()
	res = {}
	for param in param_dict:
		if mode == "numpy":
			res[param] = param_dict[param].numpy()
		elif mode == "list":
			res[param] = param_dict[param].numpy().tolist()
		else:
			res[param] = param_dict[param]
	f.write(json.dumps(res))
	f.close()
```

**Comment by nheist** [comment]
By the way, this functionality is already implemented in the new version as well (see https://github.com/thunlp/OpenKE/blob/OpenKE-PyTorch/openke/module/BaseModule.py#L32). You can call the `save_parameters` function directly on every model (e.g. TransE).
