### ISSUE TITLE
module 'config' has no attribute 'Config'

### ISSUE THREAD

**Issue by chuanhaoLi** [thunlp/OpenKE#250]
An error occurred while using transE, showing module 'config' has no attribute 'Config'. There is indeed no Config file in the config module

**Comment by bianshanyipilang** [comment]
我也遇到了这个问题  请问你解决了吗

**Comment by ZMLin2020** [comment]
同样问题+1，求解答

**Comment by dongandi** [comment]
config的路径设置错误，这个config是需要导入OPENKE自带的

**Comment by ren-1247** [comment]
> config的路径设置错误，这个config是需要导入OPENKE自带的
可以说一下具体要怎么做吗？

**Comment by LiuYuemei111** [comment]
There are only trainer.py and tester.py in config. What do you mean by Config() ?
