### ISSUE TITLE
At least 606 out of 20K test triples do not make sense

### ISSUE THREAD

**Issue by unmeshvrije** [thunlp/OpenKE#254]
There are several tripels in test set that do not make sense
E.g. (Film, crew_role, Special effect Supervisor)
A film/movie cannot be a special effects supervisor.

606 out of 20K test triples are of this form.
There are others of the form (Football Club, team_roster_position, left wing back)
A football/soccer team cannot have a roster position like left wing back. It must be a player.

```
Quills (film), /film/film/other_crew./film/film_crew_gig/film_crew_role, _
Orange County (movie), /film/film/other_crew./film/film_crew_gig/film_crew_role, Special effects supervisor
Star Wars: Episode 2 - Attack of the Clones, /film/film/other_crew./film/film_crew_gig/film_crew_role, MakeUp Artist
Anonymous (film), /film/film/other_crew./film/film_crew_gig/film_crew_role, Special effects supervisor
Saw 3D The Traps Come Alive, /film/film/other_crew./film/film_crew_gig/film_crew_role, Graphic designers
Grown Ups (film)/version 2, /film/film/other_crew./film/film_crew_gig/film_crew_role, _
Prince Caspian (movie), /film/film/other_crew./film/film_crew_gig/film_crew_role, DFX/ Digital FX
The Reader (2008 film), /film/film/other_crew./film/film_crew_gig/film_crew_role, Art direction
Beetlejuice 2, /film/film/other_crew./film/film_crew_gig/film_crew_role, MakeUp Artist

```

**Comment by THUCSTHanxu13** [comment]
These benchmark datasets come from Freebase. As Freebase is constructed automatically before 2013, there may be some noise in the knowledge graph. And Freebase has also been no longer maintained. To construct new benchmark datasets instead of the typical ones may be promising.
