### ISSUE TITLE
使用自己的数据，train2id.txt里面有10万triples,运行之后显示8万。

### ISSUE THREAD

**Issue by w82318029** [thunlp/OpenKE#255]
train2id.txt有10万triples。运行train_transe.py  
显示
The Total of train triples is 88041.

train2id.txt格式是对的。是对triples 有其他 校验操作吗？

**Comment by avery-listening** [comment]
出现同样的问题，想问问是为什么？

**Comment by mug2mag** [comment]
@w82318029 遇到同样的问题，请问找到原因了么

**Comment by feitboiling** [comment]
我也遇到了同样的问题，请问是什么原因呢？

> train2id.txt有10万triples。运行train_transe.py 显示 The Total of train triples is 88041.
> 
> train2id.txt格式是对的。是对triples 有其他 校验操作吗？

**Comment by s821220** [comment]
应该是有重复的数据
