### ISSUE TITLE
the `prob` in this line may be the probability to replace the tail entity

### ISSUE THREAD

**Issue by SidewinderAK47** [thunlp/OpenKE#257]
https://github.com/thunlp/OpenKE/blob/7a561c26a13300d910a3253c3efd4fd852f979e0/openke/base/Base.cpp#L112-L120

the `prob` in this line may be the probability to replace the tail entity, but  not the probability to replace head entity.
formula prove:
`prob =  (freqRel[i] / right_num[i])/(freqRel[i] / right_num[i]+freqRel[i] / left_num[i])`
`=left_num[r]/(right_num[r]+left_num[r])`
`=1/(1+right_num[r]/left_num[r])`
among the relation` r `, if per head entity mapping more tail entity(n : m↑),  will have low probability to replace tail entity and high probability to replace head entity.

so the `prob` here is the probability to replace the tail entity. 
the previous open-source project is right：
https://github.com/thunlp/KB2E/blob/ddfcfeebbddda157ed1fc4cfb058b3841e7d7e14/TransE/Train_TransE.cpp#L151

**Comment by LiuYuemei111** [comment]
The `right_mean` counts the number of heads, not the number of tails.  Please see
https://github.com/thunlp/OpenKE/blob/bc64ca73f6ca9363fff62d6132d75a5bcea13d8e/openke/base/Reader.h#L142-L159
