### ISSUE TITLE
loss设计问题求助

### ISSUE THREAD

**Issue by ZhaoLiang-GitHub** [thunlp/OpenKE#259]
您好，在TransH的loss中，原始论文提出了一个叫软约束的东西，来控制关系法向量和关系转移向量垂直等等，但是在您的代码中我没有看到这一点，方便解释下嘛

**Comment by THUCSTHanxu13** [comment]
您说的应该是正交约束，让法向量和关系转移向量正交。在我们之前实验，这个正交有没有好像没有太大差别，然后实现起来对速度有负面影响，我们就没有再增加这块，做了一定的简化。
