### ISSUE TITLE
pytorch版本中TransR的实现

### ISSUE THREAD

**Issue by rootlu** [thunlp/OpenKE#26]
PyTorch版本的TransR代码没有载入TransE的预训练结果啊？能否补充一下？

**Comment by THUCSTHanxu13** [comment]
我应该在tensorflow的版本的样例里面写了一下，你可以参考下 = =！

**Comment by rootlu** [comment]
嗯嗯，写好了

**Comment by carrie0307** [comment]
> 我应该在tensorflow的版本的样例里面写了一下，你可以参考下 = =！

您好，请问可以提供一下链接吗？一直没找到。

谢谢您啦！
