### ISSUE TITLE
How to get the link predict results?

### ISSUE THREAD

**Issue by Minjuner-97** [thunlp/OpenKE#260]
The results of the code is a evaluation report, but I want to get the link predict results.
Like this,
input:   J. K. Rowling influenced by;
output:   G. K. Chesterton, J. R. R. Tolkien, C. S. Lewis, Lloyd Alexander, Terry Pratchett, Roald Dahl, Jorge Luis Borges, Stephen King, Ian Fleming

**Comment by kantholtz** [comment]
+1

Interested for the new pytorch branch.

**Comment by Minjuner-97** [comment]
I do it as following:
If I predict the tail , the predicted scores were ranked in ascending order, and return the right index 
 . Then, we can find the corresponding code from the document(entity2id.txt).

**Comment by kantholtz** [comment]
Thank you for your hint :)

**Comment by fjrivasf** [comment]
I'm aiming to do the same thing on the pytorch branch but I'm having trouble figuring out which function to use to "predict" a specific tail. Any help would be appreciated.
