### ISSUE TITLE
请问有没有比较过KG的大小对Embedding的影响

### ISSUE THREAD

**Issue by iDimple** [thunlp/OpenKE#262]
如题，请问有没有尝试面向不同大小的KG使用同种方法的效果变化。KG最少要多少数量级方法才有效

**Comment by THUCSTHanxu13** [comment]
这个很难讲，因为图大了之后，虽然信息多了，但是你做link prediction的时候候选项也多了，link prediction的难度也增加了。我们做过几千万的大图谱的训练，如果这些向量只在小图谱内做link prediction还是会有效果提升的。
