### ISSUE TITLE
Exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by mikamp116** [thunlp/OpenKE#264]
Hi!

I am using your framework in my Computer Engineering Degree final project for Content based fake news detection. I have explored the _examples_ folder and I have modified the _train_transe_FB15K237.py_ to use a custom dataset for my project. 

Here is the code:

```
import openke
from openke.config import Trainer, Tester
from openke.module.model import TransE
from openke.module.loss import MarginLoss
from openke.module.strategy import NegativeSampling
from openke.data import TrainDataLoader, TestDataLoader

# dataloader for training
train_dataloader = TrainDataLoader(
	in_path = "./benchmarks/custom/",
	nbatches = 100,
	threads = 8, 
	sampling_mode = "normal", 
	bern_flag = 1, 
	filter_flag = 1, 
	neg_ent = 25,
	neg_rel = 0)

# dataloader for test
test_dataloader = TestDataLoader("./benchmarks/custom/", "link")

# define the model
transe = TransE(
	ent_tot = train_dataloader.get_ent_tot(),
	rel_tot = train_dataloader.get_rel_tot(),
	dim = 200, 
	p_norm = 1, 
	norm_flag = True)


# define the loss function
model = NegativeSampling(
	model = transe, 
	loss = MarginLoss(margin = 5.0),
	batch_size = train_dataloader.get_batch_size()
)

# train the model
trainer = Trainer(model = model, data_loader = train_dataloader, train_times = 1000, alpha = 1.0, use_gpu = False)
trainer.run()
transe.save_checkpoint('./checkpoint/custom.ckpt')

# test the model
transe.load_checkpoint('./checkpoint/custom.ckpt')
tester = Tester(model = transe, data_loader = test_dataloader, use_gpu = False)
tester.run_link_prediction(type_constrain = False)
```

I have only changed the path for the `TrainDataLoader` and the `TestDataLoader`, set the 'use_gpu' to _False_ and changed the save and load checkpoint functions path. I get the following output:

```
Input Files Path : ./benchmarks/custom/
The toolkit is importing datasets.
The total of relations is 5.
The total of entities is 7.
The total of train triples is 6.
Input Files Path : ./benchmarks/custom/
The total of test triples is 1.
The total of valid triples is 1.
Segmentation fault
```

I have created a _custom_ directory on the _benchmarks'_ and added the _entity2id_, _relation2id_, _train2id_, _valid2id_ and _test2id_ txt files. Why do I get this error? Thank you so much in advance.

**Comment by fjrivasf** [comment]
I'm not related to the developers, but from my experience with this package that happens when the C++ library gets its data in a way that is not expecting. I'd recheck the datasets you built to make sure they're 100% formatted in the same way as the data in the examples. 

The library is accessing the data through memory pointers, so any small difference in the bit stream will trigger a seg fault.

**Comment by dongandi** [comment]
你好，我也遇到这个问题了，请问您解决这个问题了吗？

**Comment by Fitness-Horse** [comment]
我也遇到了这个问题，是路径的问题，把：
train_dataloader = TrainDataLoader(
	in_path = "./benchmarks/custom/",
	nbatches = 100,
	threads = 8, 
	sampling_mode = "normal", 
	bern_flag = 1, 
	filter_flag = 1, 
	neg_ent = 25,
	neg_rel = 0)
中的in_path = "./benchmarks/custom/"改为in_path = "../benchmarks/custom/"就可以运行了

**Comment by dongandi** [comment]
你好，加了路径之后，还是报这个错误，但是看信息是已经读取实体和关系的文件了，您有类似错误吗？

**Comment by YaooXu** [comment]
I think it's the problem of the relative path "./benchmarks/custom/".

You can change the working directory in "Run/Debug Configurations" of PyCharm.
For me, I change the working directory from xxxx/OpenKE-OpenKE-PyTorch/example to xxxx/OpenKE-OpenKE-PyTorch, and it works.

**Comment by LiuYuemei111** [comment]
You need to do an additional data processing，please use [benchmarks/FB15K237/n-n.py](https://github.com/thunlp/OpenKE/blob/OpenKE-PyTorch/benchmarks/FB15K237/n-n.py)
@mikamp116
