### ISSUE TITLE
I didn't change code, and i run the examples/train_transe_FB15K237.py  get a unsatisfactory results.

### ISSUE THREAD

**Issue by hesterLong** [thunlp/OpenKE#265]
`no type constraint results:
metric:                  MRR             MR              hit@10          hit@3           hit@1
l(raw):                  0.001551        4645.398438     0.003176        0.000586        0.000195
r(raw):                  0.001964        4321.225586     0.002785        0.001564        0.000733
averaged(raw):    0.001758        4483.312012     0.002981        0.001075        0.000464

l(filter):               0.001584        4463.916016     0.003323        0.000586        0.000195
r(filter):               0.001966        4305.211914     0.002785        0.001564        0.000733
averaged(filter):        0.001775        4384.563965     0.003054        0.001075        0.000464
0.003054
0.0030538453720510006`
I want to know the reason,thank u!

**Comment by Samuel123-hub** [comment]
你要调整参数，参数调整好了结果就很好

**Comment by mscsedu** [comment]
Are you running your code on CPU or GPU?

> `no type constraint results:
> metric: MRR MR hit@10 hit@3 hit@1
> l(raw): 0.001551 4645.398438 0.003176 0.000586 0.000195
> r(raw): 0.001964 4321.225586 0.002785 0.001564 0.000733
> averaged(raw): 0.001758 4483.312012 0.002981 0.001075 0.000464
> 
> l(filter): 0.001584 4463.916016 0.003323 0.000586 0.000195
> r(filter): 0.001966 4305.211914 0.002785 0.001564 0.000733
> averaged(filter): 0.001775 4384.563965 0.003054 0.001075 0.000464
> 0.003054
> 0.0030538453720510006`
> I want to know the reason,thank u!

**Comment by luffycodes** [comment]
I get better performance than this, but results are still BAD.
RAN ON GPU !



![transe_fb15k237](https://user-images.githubusercontent.com/22951144/106204941-5d5e4000-6183-11eb-92ba-ccb1df739a7b.png)

**Comment by LiuYuemei111** [comment]
Please see the row `averaged (filter)`, the model gets the performance score 0.475 of hits@10, which is close to the result reported in the readme file
