### ISSUE TITLE
How to save embedding training result?

### ISSUE THREAD

**Issue by gawainx** [thunlp/OpenKE#268]
In old version of openKE, I can use `con.set_out_files("./res/embedding.vec.json")` to save training result.

But in the newest pyTorch version, I can not find this API, just find the save and load checkpoint.

So How can I save the training result?

**Comment by slliao445** [comment]
> In old version of openKE, I can use `con.set_out_files("./res/embedding.vec.json")` to save training result.
> 
> But in the newest pyTorch version, I can not find this API, just find the save and load checkpoint.
> 
> So How can I save the training result?

是的，我也在好奇新版pytorch版本的openKE怎么保存embedding结果。 我在train_transe_FB15K237.py文件末尾加上了
```
# save the embeddings
sava_path = args.model_save_dir + "embedding.vec.json"
transe.save_parameters(sava_path)
```
但是得到的embedding.vec.json文件中是一个非常长的list，而不是想象中的每个entity的向量。请问怎么回事呢？

**Comment by slliao445** [comment]
> > In old version of openKE, I can use `con.set_out_files("./res/embedding.vec.json")` to save training result.
> > But in the newest pyTorch version, I can not find this API, just find the save and load checkpoint.
> > So How can I save the training result?
> 
> 是的，我也在好奇新版pytorch版本的openKE怎么保存embedding结果。 我在train_transe_FB15K237.py文件末尾加上了
> 
> ```
> # save the embeddings
> sava_path = args.model_save_dir + "embedding.vec.json"
> transe.save_parameters(sava_path)
> ```
> 
> 但是得到的embedding.vec.json文件中是一个非常长的list，而不是想象中的每个entity的向量。请问怎么回事呢？

已解决，把embedding.vec.json文件读取到python代码中就是字典格式，对应着所有实体和relation的embedding。~~

**Comment by foxnike123** [comment]
怎么获得相应实体编号和对应的mebedding呢

**Comment by renwenshuang** [comment]
> 怎么获得相应实体编号和对应的mebedding呢

请问你知道了吗？我也很疑惑这个问题

**Comment by foxnike123** [comment]
我直接使用一一对应的方法拿的，不知道对不对仅供参考
f1 = open("../results/entity_vec_.transe", "w")
f2 = open("../results/relation_vec.transe","w")
param_dict = self.state_dict()
mode = "list"
for param in param_dict:
   param_dict[param] = param_dict[param].cpu()
res = {}
for param in param_dict:
   if mode == "numpy":
      res[param] = param_dict[param].numpy()
   elif mode == "list":
      res[param] = param_dict[param].numpy().tolist()
   else:
      res[param] = param_dict[param]
str1=""
str2=""
list1=res["ent_embeddings.weight"]
list2=res["rel_embeddings.weight"]
for i,temp_enemb in enumerate(list1):
   str1 += str(i)+"\t"
   str1 += str(list(list1[i]))+"\n"
for i, temp_relenm in enumerate(list2):
   str2 += str(i)+"\t"
   str2 += str(list(list2[i]))+"\n"

f1.write(str1)
f2.write(str2)
f1.close()
f2.close()





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "renwenshuang"<notifications@github.com&gt;; 
发送时间: 2020年12月29日(星期二) 中午1:44
收件人: "thunlp/OpenKE"<OpenKE@noreply.github.com&gt;; 
抄送: "狐狸"<1766895329@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [thunlp/OpenKE] How to save embedding training result? (#268)





  
怎么获得相应实体编号和对应的mebedding呢
  
请问你知道了吗？我也很疑惑这个问题

**Comment by renwenshuang** [comment]
> param_dict = self.state_dict() mode = "list" for param in param_dict: param_dict[param] = param_dict[param].cpu() res = {} for param in param_dict: if mode == "numpy": res[param] = param_dict[param].numpy() elif mode == "list": res[param] = param_dict[param].numpy().tolist() else: res[param] = param_dict[param] str1="" str2="" list1=res["ent_embeddings.weight"] list2=res["rel_embeddings.weight"] for i,temp_enemb in enumerate(list1): str1 += str(i)+"\t" str1 += str(list(list1[i]))+"\n"

谢谢！
