### ISSUE TITLE
About the "type constraint"

### ISSUE THREAD

**Issue by Zawo1995** [thunlp/OpenKE#269]
Is this technique only used in testing step? 
Because when I remove the line 'self.lib.importTrainFiles()', the project can still go on training and validating, but meet 'segmental fault' in last step like 'link prediction'.
I am sorry to misuse this project, but I am just curious about that phenomenon.

Looking forward to your response :)

**Comment by LiuYuemei111** [comment]
`self.lib.importTrainFiles()` needs to be kept in training and testing. It is used to process the type_constrain.
