### ISSUE TITLE
New DataSet

### ISSUE THREAD

**Issue by saeedizade** [thunlp/OpenKE#270]
Hi
how should be the format of new dataset?
i am trying new graph but i have a run time problem, the code stops at reading of Train2id.txt

i did 3 thing in my graph :
1- ids start from 0 but second one is not 1, it can be 4
2- like u sad ,train valid and test has space between tripples
3- there is a count at the beginning of files

here is some example, can you see bugs? 

entity2id : 
528430
100001	0
100002	1
100003	2
100004	3
100005	4
100006	5
100007	6
100008	7
100009	8
100010	9
100011	10
....
train2id : 
1085622
376576 150271 773
445883 480216 534
64247 48067 905
17736 371977 159
270729 272281 925
58244 479187 877
201531 430650 695
213163 73599 975
210058 159056 102
....

relation2id:
525
isoCodeRegion	0
stellarClassification	4
network	5
federalGovernmentElectorate	8
river	9
crystalStructure	10
season	12
locationCountry	14
discipline	15
computingInput	16
....

code stops at this : 
Input Files Path : ./benchmarks/Graph/
The toolkit is importing datasets.
The total of relations is 525.
The total of entities is 528430.

**Comment by saeedizade** [comment]
i know that the problem is with one of  this file :
relation2id , train2id ,entity2id ,test2id,valid2id
but i cant find the problem

**Comment by saeedizade** [comment]
i make 1- ids start from 0 but second one is not 1, it can be 4
 to this : 1- ids 0,1,2,3...

**Comment by shoron-dutta** [comment]
Hello, I am running into a similar problem (I am getting "Segmentation fault: core dumped" after the number of valid triples get printed). Did you start counting the entities as 0,1,2,3,.. and so on in the entity2id.txt file and got your problem solved?

Any help is much appreciated. Thanks.
