### ISSUE TITLE
save follow your introduction and example 

### ISSUE THREAD

**Issue by chrislouis0106** [thunlp/OpenKE#271]
Traceback (most recent call last):
  File "train_transe_FB15K237.py", line 41, in <module>
    transe.save_checkpoint('./checkpoint/transe.ckpt')
  File "/workspace/OpenKE/openke/module/BaseModule.py", line 21, in save_checkpoint
    torch.save(self.state_dict(), path)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 327, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './checkpoint/transe.ckpt'
![image](https://user-images.githubusercontent.com/31423097/90138535-bbe85b00-dda9-11ea-917a-28e3e960c8df.png)
![image](https://user-images.githubusercontent.com/31423097/90144629-a37c3e80-ddb1-11ea-8275-e7aaacede799.png)

I follow the order then get the error.I don't why;

**Comment by saeedizade** [comment]
its simple , create folder "checkpoint" in OpenKE directory

**Comment by chrislouis0106** [comment]
And, just:if not os.path.exists('./checkpoint/transe.ckpt'):
&nbsp; &nbsp; os.mkdir('./checkpoint/transe.ckpt')&nbsp;
so, the reason is that the code is imcomplete.&nbsp;
before，I think the codes is correct and pass the test. OK, I will try and give you back
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MohammadJavad"<notifications@github.com&gt;; 
发送时间: 2020年8月14日(星期五) 下午3:49
收件人: "thunlp/OpenKE"<OpenKE@noreply.github.com&gt;; 
抄送: "朵朵"<884665320@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thunlp/OpenKE] save follow your introduction and example  (#271)





 
its simple , create folder "checkpoint" in OpenKE directory
