### ISSUE TITLE
There is only ACC in triplet classification. Why not precision and recall?

### ISSUE THREAD

**Issue by Samuel123-hub** [thunlp/OpenKE#272]
There is only ACC in triplet classification. Why not precision and recall? How to add precision and recall to your code? How many positive and negative samples are there in FB15K?

**Comment by mxuran** [comment]
@Samuel123-hub Have you solved this problem? I have the same problem.

**Comment by LiuYuemei111** [comment]
Hi, we just follow the previous works. 
The precision and recall seem to be commonly used in relation extraction.
