### ISSUE TITLE
about type_constrain.txt

### ISSUE THREAD

**Issue by chrislouis0106** [thunlp/OpenKE#273]
hi,
![image](https://user-images.githubusercontent.com/31423097/91806392-8b843600-ec5e-11ea-83b4-b193dabbc966.png)
by browse your code, I know how to get the type_constrain.txt and I confused the "type" because the data is just the formation(relation_id, number_head_entities, head_entity1,head_entity2,..., number_tail_entities, tail_entity1,tail_entity2,...,)
So, where show the "type"?
Best wishes!

**Comment by LiuYuemei111** [comment]
The type_constrain means the existence of entity relation constraints. For example ('China', 'capital', t), the tail entity t can only be a city, not a person's name.  The type_costrain.txt will provide the list of head entity canidates and tail entity condidates of each relation_id.
