### ISSUE TITLE
中文数据集出现段错误问题

### ISSUE THREAD

**Issue by slliao445** [thunlp/OpenKE#274]

**Comment by slliao445** [comment]
你好，我用代码里的英文数据集跑实验的时候没出现问题。 换成自己的中文数据集之后，出现了段错误。
我已经确保relation2id.txt, entity2id.txt, train2id.txt等文件的格式符合要求。
我认为可能是以下几个原因之一：
1. 数据集是中文的，所以entity2id和relation2id里面含有中文字段。
2. 部分实体字段中含有空格。C++文件读取relation2id和entity2id时，是否因为空格无法分割而无法读取文件？但是我不太懂C语言，没找到在哪里更改用‘\tab’来作为文件读取时的分隔符。

数据敏感，所以不便发出来。示例如下。
entity2id.txt:
xx xx \t 0 (xx xx表示实体中有空格)
relation2id.txt:
xx \t 0
train2id.txt:
0 1 0
希望能获得解答，谢谢！

**Comment by Samuel123-hub** [comment]
老哥，你把Transr模型运行成功了吗？

**Comment by slliao445** [comment]
> 老哥，你把Transr模型运行成功了吗？

没有，transR模型需要多大的显存啊，我一开始训练就说显存不够，我都是32G的显存了。。。其他trans模型也就只需要1G以内的显存。

**Comment by Samuel123-hub** [comment]
你要降维，k=50就可以，调整一下。你的微信是多少？可以好好交流一下吗？openke代码里只有ACC，没有精确率和召回率的代码，你有吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "slliao445"<notifications@github.com&gt;; 
发送时间: 2020年9月7日(星期一) 上午9:33
收件人: "thunlp/OpenKE"<OpenKE@noreply.github.com&gt;; 
抄送: "Samuel(张正航)"<zhangzhenghang.123@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [thunlp/OpenKE] 中文数据集出现段错误问题 (#274)





  
老哥，你把Transr模型运行成功了吗？
  
没有，transR模型需要多大的显存啊，我一开始训练就说显存不够，我都是32G的显存了。。。其他trans模型也就只需要1G以内的显存。

**Comment by zxjwudi** [comment]
遇到了同样的问题，怎么办啊！哭哭

**Comment by zxjwudi** [comment]
> 你好，我用代码里的英文数据集跑实验的时候没出现问题。 换成自己的中文数据集之后，出现了段错误。
> 我已经确保relation2id.txt, entity2id.txt, train2id.txt等文件的格式符合要求。
> 我认为可能是以下几个原因之一：
> 
> 1. 数据集是中文的，所以entity2id和relation2id里面含有中文字段。
> 2. 部分实体字段中含有空格。C++文件读取relation2id和entity2id时，是否因为空格无法分割而无法读取文件？但是我不太懂C语言，没找到在哪里更改用‘\tab’来作为文件读取时的分隔符。
> 
> 数据敏感，所以不便发出来。示例如下。
> entity2id.txt:
> xx xx \t 0 (xx xx表示实体中有空格)
> relation2id.txt:
> xx \t 0
> train2id.txt:
> 0 1 0
> 希望能获得解答，谢谢！

怎么解决的55555

**Comment by Samuel123-hub** [comment]
你的qq号是多少？可以交流




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Snow white"<notifications@github.com&gt;; 
发送时间: 2020年10月15日(星期四) 晚上10:49
收件人: "thunlp/OpenKE"<OpenKE@noreply.github.com&gt;; 
抄送: "Samuel(张正航)"<zhangzhenghang.123@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [thunlp/OpenKE] 中文数据集出现段错误问题 (#274)





  
你好，我用代码里的英文数据集跑实验的时候没出现问题。 换成自己的中文数据集之后，出现了段错误。
 我已经确保relation2id.txt, entity2id.txt, train2id.txt等文件的格式符合要求。
 我认为可能是以下几个原因之一：
  
数据集是中文的，所以entity2id和relation2id里面含有中文字段。
 
部分实体字段中含有空格。C++文件读取relation2id和entity2id时，是否因为空格无法分割而无法读取文件？但是我不太懂C语言，没找到在哪里更改用‘\tab’来作为文件读取时的分隔符。
  
数据敏感，所以不便发出来。示例如下。
 entity2id.txt:
 xx xx \t 0 (xx xx表示实体中有空格)
 relation2id.txt:
 xx \t 0
 train2id.txt:
 0 1 0
 希望能获得解答，谢谢！
  
怎么解决的55555

**Comment by Samuel123-hub** [comment]
你的qq号是多少？可以相互交流




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Snow white"<notifications@github.com&gt;; 
发送时间: 2020年10月15日(星期四) 晚上10:44
收件人: "thunlp/OpenKE"<OpenKE@noreply.github.com&gt;; 
抄送: "Samuel(张正航)"<zhangzhenghang.123@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [thunlp/OpenKE] 中文数据集出现段错误问题 (#274)





 
遇到了同样的问题，怎么办啊！哭哭

**Comment by zxjwudi** [comment]
可以加我的微信106906195，qq比较少用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Samuel123-hub <notifications@github.com&gt;
发送时间: 2020年10月18日 21:45
收件人: thunlp/OpenKE <OpenKE@noreply.github.com&gt;
抄送: Snow white <xuejiaozhao_snow@foxmail.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[thunlp/OpenKE] 中文数据集出现段错误问题 (#274)





 你的qq号是多少？可以相互交流 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "Snow white"<notifications@github.com&amp;gt;;  
 发送时间: 2020年10月15日(星期四) 晚上10:44 
 收件人: "thunlp/OpenKE"<OpenKE@noreply.github.com&amp;gt;;  
 抄送: "Samuel(张正航)"<zhangzhenghang.123@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [thunlp/OpenKE] 中文数据集出现段错误问题 (#274) 
 
 
 
 
 
   
 遇到了同样的问题，怎么办啊！哭哭

**Comment by dongandi** [comment]
你好，最后您最后怎么解决这个问题的?

**Comment by mengtinglll** [comment]
数据集中是否包含type_constrain.txt？
openke/data/TestDataLoader.py中27行默认使用type_constrain.txt，如果没有type_constrain.txt就会报错

**Comment by gaoxing153** [comment]
> 数据集中是否包含type_constrain.txt？
> openke/data/TestDataLoader.py中27行默认使用type_constrain.txt，如果没有type_constrain.txt就会报错

我的数据中包含了type_contrain.txt文件，但是在运行的时候还是会报错

**Comment by gaoxing153** [comment]
> 你好，我用代码里的英文数据集跑实验的时候没出现问题。 换成自己的中文数据集之后，出现了段错误。
> 我已经确保relation2id.txt, entity2id.txt, train2id.txt等文件的格式符合要求。
> 我认为可能是以下几个原因之一：
> 
> 1. 数据集是中文的，所以entity2id和relation2id里面含有中文字段。
> 2. 部分实体字段中含有空格。C++文件读取relation2id和entity2id时，是否因为空格无法分割而无法读取文件？但是我不太懂C语言，没找到在哪里更改用‘\tab’来作为文件读取时的分隔符。
> 
> 数据敏感，所以不便发出来。示例如下。
> entity2id.txt:
> xx xx \t 0 (xx xx表示实体中有空格)
> relation2id.txt:
> xx \t 0
> train2id.txt:
> 0 1 0
> 希望能获得解答，谢谢！

你好，请问一下你这个问题解决了没有，我在换成自己的数据之后也遇到了问题

**Comment by LiuYuemei111** [comment]
可以用下划线代替空格，可以参考该数据格式[https://github.com/thunlp/OpenKE/blob/OpenKE-PyTorch/benchmarks/YAGO3-10/entity2id.txt](https://github.com/thunlp/OpenKE/blob/OpenKE-PyTorch/benchmarks/YAGO3-10/entity2id.txt),  即

Gmina_Lelis     123172
Danilo_Dias     123173
Simon_Sešlar    123174
Nathan_Peat     123175
Mijat_Marić     123176
Brown_Ideye     123177
Pavol_Staňo     123178
Appenzell_Ausserrhoden  123179
Bruno_Herrero_Arias     123180
C.D._Guadalajara        123181

**Comment by wangcccchen** [comment]
> 你好，我用代码里的英文数据集跑实验的时候没出现问题。 换成自己的中文数据集之后，出现了段错误。 我已经确保relation2id.txt, entity2id.txt, train2id.txt等文件的格式符合要求。 我认为可能是以下几个原因之一：
> 
> 1. 数据集是中文的，所以entity2id和relation2id里面含有中文字段。
> 2. 部分实体字段中含有空格。C++文件读取relation2id和entity2id时，是否因为空格无法分割而无法读取文件？但是我不太懂C语言，没找到在哪里更改用‘\tab’来作为文件读取时的分隔符。
> 
> 数据敏感，所以不便发出来。示例如下。 entity2id.txt: xx xx \t 0 (xx xx表示实体中有空格) relation2id.txt: xx \t 0 train2id.txt: 0 1 0 希望能获得解答，谢谢！

想请问一下，使用自己的中文数据集，怎么保证测试集中的实体和关系在训练集中都出现过且三元组跟测试集中不一样？

**Comment by Samuel123-hub** [comment]
你说的这个问题只是一个部分，最关键的是看train2id.txt和type_constrain.txt这两个文件，不然就会出现内存溢出的问题，而这些工作都需要你把1-1,1-n,n-1,n-n先弄出来，对于你说的空格问题，直接用FB15K里train2id.txt文件中的空格复制，替换你的空格就可以，多测试你就会发现问题所在，还有，中文的数据集直接用数字替换，你在设置实体和关系的时候你就应该这么做呀



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月11日(星期五) 晚上11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thunlp/OpenKE] 中文数据集出现段错误问题 (#274)





  
你好，我用代码里的英文数据集跑实验的时候没出现问题。 换成自己的中文数据集之后，出现了段错误。 我已经确保relation2id.txt, entity2id.txt, train2id.txt等文件的格式符合要求。 我认为可能是以下几个原因之一：
  
数据集是中文的，所以entity2id和relation2id里面含有中文字段。
 
部分实体字段中含有空格。C++文件读取relation2id和entity2id时，是否因为空格无法分割而无法读取文件？但是我不太懂C语言，没找到在哪里更改用‘\tab’来作为文件读取时的分隔符。
  
数据敏感，所以不便发出来。示例如下。 entity2id.txt: xx xx \t 0 (xx xx表示实体中有空格) relation2id.txt: xx \t 0 train2id.txt: 0 1 0 希望能获得解答，谢谢！
  
想请问一下，使用自己的中文数据集，怎么保证测试集中的实体和关系在训练集中都出现过且三元组跟测试集中不一样？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
