### ISSUE TITLE
在TransH和TransR论文里除了ACC，还有精确率和召回率，而代码里好像没有添加，怎么在三元组分类那里加？

### ISSUE THREAD

**Issue by Samuel123-hub** [thunlp/OpenKE#275]
在TransH和TransR论文里除了ACC，还有精确率和召回率，而代码里好像没有添加，怎么在三元组分类代码那里加？

**Comment by yyysfff** [comment]
在openke/config/Tester.py中的run_triple_classification(self, threshlod = None)进行修改：
在源代码的144行到149行进行改动：
for index, [ans, score] in enumerate(res):
    if score > threshlod:
        acc = (2 * total_current + total_false - index) / total_all
        break
    elif ans == 1:
        total_current += 1.0
改成下面这样试试：
tp = 0.0
fn = 0.0
fp = 0.0
tn = 0.0
for index, [ans, score] in enumerate(res):
    if score > threshlod and ans==1:
        tp += 1.0
    elif score > threshlod and ans==0:
        fp += 1.0
    elif score <= threshlod and ans==1:
        fn += 1.0
    elif score <= threshlod and ans==0:
        tn += 1.0
acc = (tp +tn)/(tp +tn+fn+fp)
precision = tp/(tp+fp)
recall = tp/(tp+fn)

**Comment by Samuel123-hub** [comment]
非常感谢你

**Comment by mxuran** [comment]
@Samuel123-hub @yyysfff Is this solution possible? I tried it, but the acc value is different from the original code？
