### ISSUE TITLE
Setting.h中数据类型定义错误

### ISSUE THREAD

**Issue by www008** [thunlp/OpenKE#278]
Setting.h中定义#define INT long  //32位
Base.cpp中定义 extern "C" void sampling( INT *batch_h,  INT *batch_t, ....)
但TrainDataLoader.py中竟然定义
self.batch_h = np.zeros(self.batch_seq_size, dtype=**np.int64**) //64位，完全对不上。
self.batch_t = np.zeros(self.batch_seq_size, dtype=**np.int64**)
...
**很怀疑这程序是如何跑起来的？？？:(**

**Comment by mscsedu** [comment]
Did you find any solution to this error?

**Comment by mscsedu** [comment]
I have resolved the issue. I was using a 32-bit g++ installer on 64-bit windows. Now i am using 64-bit g++ installer. Select your installer accordingly
