### ISSUE TITLE
Predict relation on new entities, id

### ISSUE THREAD

**Issue by reobroqn** [thunlp/OpenKE#279]
Thanks for sharing your code!
I have trained and ran your code smoothly! But in my case, I need to predict relation for those entities outside of train, test, valid file. Like, when i create relation2id.txt and entity2id.txt, and predict in this area then it's okay, but if I want to use an entity not in this list. How can i do it? Or i have to re-create relation2id.txt and entity2id.txt that include all entities i want to use and then train all from the begin. Is there another way to do it?
Thanks!

**Comment by dinani65** [comment]
Hello @reobroqn 
I have a subset of FreeBase's triples as my input dataset, the triples are in the form of (FreebaseID1, relation, FreeBaseID2)such as the following triple:
 <fb:m.0100zv6s>	<fb:common.topic.notable_for>	<fb:g.1q3sj7rb3>
 my goal is generating the embedding of the entities and relations of my dataset and then using them for a question answering system.
 I am not sure what I should do with OpenKE:
 1- can I consider all triples as training data according to my goal?
 2- when it is said the embeddings of some existing large-scale KGs pre-trained by OpenKE are available, how can I employed for my work?

**Comment by LiuYuemei111** [comment]
> Thanks for sharing your code! I have trained and ran your code smoothly! But in my case, I need to predict relation for those entities outside of train, test, valid file. Like, when i create relation2id.txt and entity2id.txt , and predict in this area then it's okay, but if I want to use an entity not in this list. How can i do it? Or i have to re-create relation2id.txt and entity2id.txt that include all entities i want to use and then train all from the begin. Is there another way to do it? Thanks!

It is not supported for not appearing in the entity list. The simple way is to add new entities to the already trained embeddings for retraining. Here we can freeze the already trained embeddings and only tune the new entities added.

**Comment by LiuYuemei111** [comment]
1. Yes, you can use all triples as training data
2. You can use it  https://github.com/thunlp/OpenKE/blob/bc64ca73f6ca9363fff62d6132d75a5bcea13d8e/openke/module/BaseModule.py#L23
·model.load_parameters(path)· where path is the path of your trained embedding
