### ISSUE TITLE
同时加载两个训练数据，出现数据混乱问题

### ISSUE THREAD

**Issue by ahtwq** [thunlp/OpenKE#283]
> import os
> import ctypes
> import numpy as np
> 
>  定义了2个类，完成训练数据的预处理
> class TrainDataSampler(object):
>     
> class TrainDataLoader(object):

   
usage:

> 	train_dataloader_dr = TrainDataLoader(
> 	in_path="./benchmarks/DR/",
> 	nbatches=5,
> 	threads=2,
> 	sampling_mode="normal",
> 	bern_flag=1,
> 	filter_flag=1,
> 	neg_ent=8,
> 	neg_rel=0)
> 
> 	print('dr:', list(train_dataloader_dr))
> 
> 	train_dataloader_dme = TrainDataLoader(
> 	in_path="./benchmarks/DME/",
> 	nbatches=2,
> 	threads=2,
> 	sampling_mode="normal",
> 	bern_flag=1,
> 	filter_flag=1,
> 	neg_ent=6,
> 	neg_rel=0)

problem:

> 使用一次TrainDataLoader，代码正常；如果同时加载train_dataloader_dr和train_dataloader_dme，
> rain_dataloader_dr出现了INDEX问题，似乎两次使用train_dataloader不独立
> 
> 不知道大家有没有这样的问题

**Comment by LiuYuemei111** [comment]
两个都会调用C++底层，可能会存在内存冲突。解决这个问题，估计需要修改C++代码。目前对于这个版本建议不要这么使用
