### ISSUE TITLE
How to get the prediction result on Pytorch?

### ISSUE THREAD

**Issue by Coldery** [thunlp/OpenKE#289]
Your example code about prediction result is on tensorflow, can I get the Pytorch code?

**Comment by yyysfff** [comment]
You can refer to the py file in the example file, and tester.run_triple_classification() can get the result of triple classification.

**Comment by LiuYuemei111** [comment]
https://github.com/thunlp/OpenKE/issues/319#issuecomment-925547973  Please refer to this.
