### ISSUE TITLE
负采样部分，Pytorch版本的OpenKE

### ISSUE THREAD

**Issue by SHIBOYA** [thunlp/OpenKE#291]
底层C++对于一些只用python的研究生来说不太友好，感觉缺乏必要的注释。我的疑问主要集中于负采样部分：
1：目前我对整个工程的理解是PyTorchTrainDataLoader.py实现了负采样，但在其他的文件中似乎并没有引用或者说用到这个文件，这是为什么？
2：在TrainDataLoader.py中，无法理解self.batch_y_addr = self.batch_y.__array_interface__["data"][0]这句话的含义，为什么有很多这种关于地址的句子？

**Comment by THUCSTHanxu13** [comment]
因为python很慢，所以sample都交给了底层的c去做。
numpy之所以快的原因也是底层是连续的地址空间，是c的实现。
所以这里需要array_interface来取你的numpy数据，然后传给底层的c代码

**Comment by THUCSTHanxu13** [comment]
采用算法在base里面的corrupt.h

这个算法的核心在于，给所有的实体重新编号。假设0~N里面有3个实体 3、7、9 是正例，是不能被取到的话，那么重新编号后的号码为
原编码：0 1 2 3 4 5 6 7 8 9 10 11 12 ... N
现编码：0 1 2 2 3 4 5 5 6 6 7 8 9 ... N-3

所以我们随机从0到N-3里面取一个数X，然后用二分找这个数X在现编码中最左边的位置，再返回对应的原编码即可。
你说的两个if相当于是这里面0到2 以及 7到N-3这部分的判断，2到7的需要下面这个二分去做。

这样的算法可以一次随机在log(n)的时间复杂度里就采用出一个不会在训练集里出现过的三元组，不用任何重复采用操作

**Comment by THUCSTHanxu13** [comment]
如果用写python写最裸的采样的话，会很慢

**Comment by SHIBOYA** [comment]
感谢您的回复，终于理解了
