### ISSUE TITLE
loss计算中的regularization理解

### ISSUE THREAD

**Issue by ReadyTeresa** [thunlp/OpenKE#292]
不太理解	这个地方，有没有人帮忙解释一下，非常感谢。	
if self.regul_rate != 0:
loss_res += self.regul_rate * self.model.regularization(data)

regularization里面为什么是平方

  def regularization(self, data):
      batch_h = data['batch_h']
      batch_t = data['batch_t']
      batch_r = data['batch_r']
      h = self.ent_embeddings(batch_h)
      t = self.ent_embeddings(batch_t)
      r = self.rel_embeddings(batch_r)
      r_norm = self.norm_vector(batch_r)
      regul = (torch.mean(h ** 2) + 
			      torch.mean(t ** 2) + 
			      torch.mean(r ** 2) +
			      torch.mean(r_norm ** 2)) / 4
      return regul

**Comment by THUCSTHanxu13** [comment]
2阶的regularization基本等比与各个要素的平方平均
