### ISSUE TITLE
我用example中的初始参数去跑，效果都很差，可以公开超参数吗？

### ISSUE THREAD

**Issue by zxxxxxxxin** [thunlp/OpenKE#293]
我跑了Complex，SImplE，DistMult，Anonogy ，效果都远达不到readme中的表格的效果。各位有谁可以公开超参数吗？

**Comment by LiuYuemei111** [comment]
您是直接采用默认参数运行的么？ 我刚运行了一下Complex，结果与readme中报告的结果是差不多的

(ptuning) wanghuadong@node1:~/OpenKE$ python train_transe_FB15K237.py
Input Files Path : ./benchmarks/FB15K237/
The toolkit is importing datasets.
The total of relations is 237.
The total of entities is 14541.
The total of train triples is 272115.
Input Files Path : ./benchmarks/FB15K237/
The total of test triples is 20466.
The total of valid triples is 17535.
Finish initializing...
Epoch 999 | loss: 2.381454: 100%|████████████████████████████████████████████████████████████████████████████| 1000/1000 [20:19<00:00,  1.22s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 20466/20466 [00:18<00:00, 1091.37it/s]
no type constraint results:
metric:                  MRR             MR              hit@10          hit@3           hit@1
l(raw):                  0.089113        561.105835      0.204779        0.086583        0.033470
r(raw):                  0.251904        165.952652      0.441171        0.271817        0.160608
averaged(raw):           0.170508        363.529236      0.322975        0.179200        0.097039

l(filter):               0.189979        308.011200      0.362748        0.213720        0.105492
r(filter):               0.390304        139.963348      0.594400        0.441268        0.283495
averaged(filter):        0.290141        223.987274      0.478574        0.327494        0.194493
0.478574
0.4785742163658142
