### ISSUE TITLE
Running examples/train_transe_FB15K237.py does not give reported performance.

### ISSUE THREAD

**Issue by luffycodes** [thunlp/OpenKE#297]
Running examples/train_transe_FB15K237.py does not give reported performance.
Running on GPU (11Gb).

![transe_fb15k237](https://user-images.githubusercontent.com/22951144/106204811-30aa2880-6183-11eb-8a2c-f9cf9b5d2435.png)

**Comment by LiuYuemei111** [comment]
Please see the row "averaged (filter)",  the model gets 0.475 of hits@10
