### ISSUE TITLE
如何在trans系列模型中使用自己的数据

### ISSUE THREAD

**Issue by gaoxing153** [thunlp/OpenKE#298]
如果想在trans系列的模型中使用自己的数据应该如何处理，对数据格式有哪些要求

**Comment by Samuel123-hub** [comment]
你需要进行编译才行，对格式要求很高，尤其是空格

**Comment by WhianGaulin** [comment]
> 你需要进行编译才行，对格式要求很高，尤其是空格

请问编译是什么意思呢？
空格的要求体现在哪？ 我感觉只要有空格就行了呀
我也想在自己的数据上训练rescal，还没进行

**Comment by gaoxing153** [comment]
> > 你需要进行编译才行，对格式要求很高，尤其是空格
> 
> 请问编译是什么意思呢？
> 空格的要求体现在哪？ 我感觉只要有空格就行了呀
> 我也想在自己的数据上训练rescal，还没进行

可以参考一下https://github.com/zqhead/TransH
