### ISSUE TITLE
Some Advice

### ISSUE THREAD

**Issue by gavinjou818** [thunlp/OpenKE#3]
HI friends..    I hope i can get more examples, when I run example.py with TransH, the output is nan..  but i dont know why...    and  i hope you can post the configuration on the site like the version of Tensorflow and describe clearly like OpenNE ...  Thanks you .

**Comment by gavinjou818** [comment]
it is so strange ...
![_001](https://user-images.githubusercontent.com/17568341/32616078-6c0fc112-c5ac-11e7-9530-4335d9035f77.png)
![_002](https://user-images.githubusercontent.com/17568341/32616087-71541894-c5ac-11e7-9e10-550b0eaffdff.png)

**Comment by THUCSTHanxu13** [comment]
For TransH, you should set alpha as "0.001". For these models, we will provide parameter settings soon.

**Comment by JunhengH** [comment]
Could you please kindly provide optimal parameter settings for all the Trans"X" models? That will help save great efforts and avoid some unexpected errors. ^_^

**Comment by MingleiLI** [comment]
For TransH, I also got nan event setting alpha to 0.001 using the example code in the examples/ dir. 
![image](https://user-images.githubusercontent.com/3665731/38169201-5f08147e-3596-11e8-9e28-338551a48fa7.png)
