### ISSUE TITLE
使用自己的数据集时发生c++的库出现内存访问错误

### ISSUE THREAD

**Issue by motefly** [thunlp/OpenKE#30]
您好，
      我在使用这份代码读取自己生成的数据集时发生了一些错误
问题已解决，在此提醒大家：
注意数据集的反人类设计。。。三元组排列顺序是 h t r 而不是KG中的 h r t !!!

**Comment by THUCSTHanxu13** [comment]
因为很多论文的原始数据格式是h,t,r...
