### ISSUE TITLE
预训练实体向量错误

### ISSUE THREAD

**Issue by Diison** [thunlp/OpenKE#300]
贵实验室提供的预训练实体向量：http://139.129.163.161/sendMessage，中的 Freebase.zip，解压得到的 Freebase/embeddings/dimension_50/transe/entity2vec.bin 文件，使用 http://139.129.163.161/index/toolkits#pretrained-freebase 提供的方法 ：

#Python codes to read the binary files.
import numpy as np
vec = np.memmap(filename , dtype='float32', mode='r')

加载以后得到的结果是长度为 4302707550 数组：[ 0.099023 -0.181624  0.221403 ... -0.220965  0.069453 -0.029318]，请问是数据问题还是代码问题？

**Comment by THUCSTHanxu13** [comment]
vec是所有的向量拉成一列的结果，reshape成(n, dim)就可以
