### ISSUE TITLE
whats the meaning of lef and rig (Head/Tail/Rel) ??

### ISSUE THREAD

**Issue by Sein-Kim** [thunlp/OpenKE#301]
at OpenKE/openke/base/Reader.h   line 112 ~ 160 (in the function importTrainFiles),

the variables named lefHead, rigHead, and same for Tail, Rel appears.
It seems to be crucial to fully understand the meaning and role of each variables since it continuously appears in other files such as OpenKE/openke/base/corrupt.h (or test.h)

In terms of generating corrupted set, what would be the key role of 'lef', 'rig' int type variable?

Or could you recommend any other papers or concepts to understand and derive such variables?

Thanks, in advance.

**Comment by ShulinCao** [comment]
This is for Offset-based Negative Sampling, please refer to the OpenKE paper for this part. https://aclanthology.org/D18-2024.pdf.
