### ISSUE TITLE
TestDataLoader in a batch.  Pytorch code

### ISSUE THREAD

**Issue by quqxui** [thunlp/OpenKE#305]
hi, 
Can i load a batch of data in the TestDataLoader as same as TrainDataLoader?  If not,  how can i achieve it? 
I am not very familiar with c++, can you explain to me briefly how can i do?  

Hope for your reply, thank you very much!!

**Comment by LiuYuemei111** [comment]
The current test module in this version cannot support setting batch_size. No relevant parameter setting interface is provided in the code. The test module is implemented in C++ and many functions are written in a fixed form. It is not easy to change it to support batch_size setting. We will implement a new parallelized version later.
