### ISSUE TITLE
How to split train/valid/test

### ISSUE THREAD

**Issue by SRL94** [thunlp/OpenKE#306]
Hi, how do you split the knowledge graph into train/valid/test? I am confused about how to make all entities appearing in the training set.

**Comment by RucLee** [comment]
I have the same problem~! 
please help

**Comment by LiuYuemei111** [comment]
The benchmarks are selected from the original published papers.  For example,
FB15K [Translating Embeddings for Modeling Multi-relational Data](https://proceedings.neurips.cc/paper/2013/file/1cecc7a77928ca8133fa24680a88d2f9-Paper.pdf)
FB15K237 [Observed versus latent features for knowledge base and text inference](https://aclanthology.org/W15-4007.pdf)
WN18,WN18RR [Convolutional 2D Knowledge Graph Embeddings](https://arxiv.org/abs/1707.01476)
NELL-995 [DeepPath: A Reinforcement Learning Method for Knowledge Graph Reasoning](https://aclanthology.org/D17-1060.pdf)
YAGO3-10 [YAGO3: A Knowledge Base from Multilingual Wikipedias](https://asiabiega.github.io/papers/yago3_cidr2015.pdf)
You can find more details about how to split these benchmarks.

> Hi, how do you split the knowledge graph into train/valid/test? I am confused about how to make all entities appearing in the training set.
