### ISSUE TITLE
the batch_size for the test process

### ISSUE THREAD

**Issue by chrislouis0106** [thunlp/OpenKE#309]
Hi, I try to set a batch_size for the test process, because, for the test process, it's too slow for NELL-995 data including about 150000 test triples. 
But, when I read the Tester.py and TestDataLoader.py, I don't found the key to resolve the problem.
So, could you give me some advice, thank you anyway.

**Comment by LiuYuemei111** [comment]
The current test module in this version cannot support setting batch_size. No relevant parameter setting interface is provided in the code.
