### ISSUE TITLE
请问embedding.vec.json文件中对应的向量表示，是经过filter处理之后的吗？

### ISSUE THREAD

**Issue by penelope24** [thunlp/OpenKE#31]
提这个问题是因为，我看到运行测试集后，分别生成了raw模式与filtered模式的统计结果，而最终生成的向量表示似乎只有唯一的embedding.vec.json文件。
因此，embedding.vec.json里的向量表示对应的是raw还是filtered呢？在我的实验中发现采用两种模式的预测结果相差非常悬殊。

**Comment by THUCSTHanxu13** [comment]
raw和filter只是在测试的时候link prediction的候选集合不一样，属于测试标准上的不同。向量都是一样的。对于(美国，总统，?)做预测，如果答案是特朗普的话，在raw里面你回答奥巴马就是错误的，但是在filter设定下你回答奥巴马就是正确的，所以结果差距很悬殊。

**Comment by penelope24** [comment]
@THUCSTHanxu13 回答的很清楚，非常感谢！
