### ISSUE TITLE
如何在windows中使用OpenEK

### ISSUE THREAD

**Issue by nipirennipi** [thunlp/OpenKE#313]
如何编译得到Base.dll ？

**Comment by Walker-ZD** [comment]
> 如何编译得到Base.dll ？

有什么办法吗？我这边在windows上编译会出错，得不到Base.so，但是linux服务器上可以。
如果把linux服务器上生成的Base.so直接拿过来的话，会报错：OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by nipirennipi** [comment]
> > 如何编译得到Base.dll ？
> 
> 有什么办法吗？我这边在windows上编译会出错，得不到Base.so，但是linux服务器上可以。
> 如果把linux服务器上生成的Base.so直接拿过来的话，会报错：OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

我直接选择Linux了。关闭这个issue不是因为我解决了😭

**Comment by zqhead** [comment]
有办法，docker架远程服务，pycharm去访问这个远程服务就可以了
