### ISSUE TITLE
How to Get Embedding Matrix

### ISSUE THREAD

**Issue by eric2213** [thunlp/OpenKE#314]
您好，我使用了RotatE并使用了自己的数据去做训练，但不晓得如何取得Embedding Matrix

http://139.129.163.161/static/notes/matrix.html
舊的文檔的方法不管用了，还请您帮我解答，谢谢

Hello, I wonder how to get the Embedding Matrix from the OpenKE-PyTorch version while using model RotatE, does anybody know how to get that?

**Comment by chenxn2020** [comment]
I have a same quetion....

**Comment by SRL94** [comment]
import numpy as py

import config
import models
con = config.Config()
con.set_in_path("./benchmarks/FB15K/") # path to your dataset
con.set_test_flag(True)
con.set_work_threads(4)
con.set_dimension(100)
con.set_import_files("./res/model.vec.pt") # path to you model
con.init()
con.set_model(models.TransE)
# Get the embeddings (numpy.array)
embeddings = con.get_parameters("numpy")

然后你会得到一个有两个key的dict，一个key是ent_embeddings, 一个key是rel_embeddings

**Comment by chenxn2020** [comment]
> 您好，我使用了RotatE并使用了自己的数据去做训练，但不晓得如何取得Embedding Matrix
> 
> http://139.129.163.161/static/notes/matrix.html
> 舊的文檔的方法不管用了，还请您帮我解答，谢谢
> 
> Hello, I wonder how to get the Embedding Matrix from the OpenKE-PyTorch version while using model RotatE, does anybody know how to get that?
你好，我正好解决了这个问题。直接model.load_checkpoint()加载模型，之后model.sate_dict()输出模型的参数就会有embedding matrix

**Comment by SRL94** [comment]
Not sure if it works for you. I trained TransE and got the embeddings by simply calling the matrix names. For example,
`model.load_checkpoint()
ent_embeds = model.ent_embeddings.weight.data
`
You can convert it to NumPy (PyTorch provides the function) and save it to .txt or .pickle.

**Comment by chenxn2020** [comment]
I found that the author has written a method to save the model parameters, you only need to use `model.save_parameters(path)` after training. The specific program can be seen in ./openke/module/BaseModule.py
