### ISSUE TITLE
Cuda Enabled PyTorch Mandatory?

### ISSUE THREAD

**Issue by sreebhattacharyya** [thunlp/OpenKE#316]
I am trying to follow the quick start instructions to see an example of training transE. Getting the error message "Torch not complied with CUDA enabled". I don't quite understand what it means? Also, suggestions of any other ways to train TransE would be welcome. Thank you!

**Comment by ShulinCao** [comment]
Could you please show your detailed running environment?
Maybe you can check the compatability with
import torch

print(torch.\_\_version\_\_)

print(torch.cuda.is_available)
