### ISSUE TITLE
如何做relation prediction实验

### ISSUE THREAD

**Issue by MiaoHu-Pro** [thunlp/OpenKE#319]
在test.h 中有test_relation_prediction这个函数，我想知道如何调用这个函数做relation prediction任务。

谢谢。

**Comment by ShulinCao** [comment]
可以参考下https://github.com/thunlp/OpenKE/tree/OpenKE-PyTorch(old) Readme里的
![image](https://user-images.githubusercontent.com/19309481/134465450-37c8a141-e023-440e-95f9-1b5a27d96d9f.png)

**Comment by mxuran** [comment]
@ShulinCao Hello, I tried to modify the source code, including TestDataLoader.py and Tester.py, but the program does not continue to execute during testRel. Do I need to modify the C code further？In addition, I see that there have been many people have questions about the relationship prediction, I hope to consider improving the function. Looking forward to your reply, thank you very much!

**Comment by wangcccchen** [comment]
> 可以参考下https://github.com/thunlp/OpenKE/tree/OpenKE-PyTorch(old) Readme里的 ![图片](https://user-images.githubusercontent.com/19309481/134465450-37c8a141-e023-440e-95f9-1b5a27d96d9f.png)

![image](https://user-images.githubusercontent.com/70743874/145765460-14455101-7502-4777-8df7-22d26a575c05.png)
你好，预测的时候这几个函数没看到具体是在哪里实现的？程序运行会报错。期待回复

**Comment by VachelChen** [comment]
> 具体

您好，请问解决了吗？我也想知道这个代码如何做连接预测任务
