### ISSUE TITLE
关于模型constraints部分的代码实现疑惑

### ISSUE THREAD

**Issue by Guohai93** [thunlp/OpenKE#32]
您好，我阅读代码(PyTorch版)时有一个疑惑：以TransE为例，请问原论文算法流程图中提到实体norm，在代码中什么地方实现的，我好像没有找到？谢谢
即，e ← e/ ∥e∥ for each entity e ∈ E

**Comment by THUCSTHanxu13** [comment]
其实在之前写完之后发现不加向量模长约束对结果几乎不造成影响，所以这部分就直接省略了。。。
