### ISSUE TITLE
关于corrupt.h的几个问题

### ISSUE THREAD

**Issue by SsnAgo** [thunlp/OpenKE#320]
请问corrupt_head(INT id, INT h, INT r, bool filter_flag = true) 以及corrupt_tail(INT id, INT t, INT r, bool filter_flag = true)的原理什么？在论文中感觉对这个部分的描述不是很能理解，接下来是看代码的一些理解（不知道对不对）以及看不懂的地方
1. corrupt_head方法首先找了h，r相同，t不同的三元组们（相邻且按t升序）。ll和rr是为了确定这些三元组的区间(分别为左右边界)。由于这些都是正三元组，因此里面的t不能被选择。因此用ll和rr划分了一个不能被选择的区间
2. 不理解：以下这段代码是随机了一个tmp作为替换的尾实体，如果tmp在区间左边，就ok，如果在左边界往右，就增加一个偏移，确保不选择区间里的t
```
INT tmp = rand_max(id, entityTotal - (rr - ll + 1));
if (tmp < trainHead[ll].t) return tmp;
if (tmp > trainHead[rr].t - rr + ll - 1) return tmp + rr - ll + 1;
lef = ll, rig = rr + 1;
while (lef + 1 < rig) {
	mid = (lef + rig) >> 1;
	if (trainHead[mid].t - mid + ll - 1 < tmp)
		lef = mid;
	else 
		rig = mid;
}
```
这块代码  在前两个if 感觉已经把两种情况都包含了，下面这个while是考虑了什么情况呢？

**Comment by THUCSTHanxu13** [comment]
这个算法的核心在于，给所有的实体重新编号。假设0~N里面有3个实体 3、7、9 是正例，是不能被取到的话，那么重新编号后的号码为
原编码：0 1 2 3 4 5 6 7 8 9  10  11  12 ... N
现编码：0 1 2 2 3 4 5 5 6 6  7     8   9 ... N-3

所以我们随机从0到N-3里面取一个数X，然后用二分找这个数X在现编码中最左边的位置，再返回对应的原编码即可。
你说的两个if相当于是这里面0到2 以及 7到N-3这部分的判断，2到7的需要下面这个二分去做。

**Comment by SsnAgo** [comment]
理解了，谢谢，之前对这个实体重新编号的部分也有些疑问，现在一并解决了

**Comment by lvfeifei** [comment]
不理解，为什么要重新编号
