### ISSUE TITLE
How to receive rank of each entity during testing the model?

### ISSUE THREAD

**Issue by marja-w** [thunlp/OpenKE#322]
Hello, 

I am trying to compute the output the model TransE has for every test triple. 

I modified the OpenKE/openke/config/Tester.py file, so that it stores each triple, the first 500 results in order, and the rank of the entity in the ordered score. I sort the score descending, so that the model would have picked the entity with the highest score as first. These are my modifications in the run_link_prediction method:

<img width="575" alt="Screenshot 2021-07-28 150348" src="https://user-images.githubusercontent.com/58331624/127326756-7d88ad32-e505-4733-b0dd-a209eae52987.png">

or as code:

`for index, [data_head, data-tail] in enumerate(training_range):
      triple = ([data_tail['batch_h'][0], data_head['batch_t'][0], data_head['batch_r#][0]])
      score = self.test_one_step(data_head)
      ordered_score = (-score).argsort()
      first_n = ordered_score[:500]
      rank_entity = np.where(ordered_score == data_tail['batch_h'][0])[0][0]
      scores_head.append({'triple': triple, 'first_500': first_n, 'rank': rank_entity})
      self.lib.testHead(score.__array_interface__["data"][0], index, type_constrain)`

Now, my question is, do I do this the right way? My outcomes do not match the computed hit@k metrics, because most of the time I do not even get one entity that is ranked in the first 20, while my average hit@10 is 80%. 

If anyone sees my mistake or knows what I am doing wrong, please help my with this issue.

**Comment by ShulinCao** [comment]
Maybe you can refer to the old version of OpenKE-Pytorch. As in https://github.com/thunlp/OpenKE/tree/OpenKE-PyTorch(old)#predict-head-entity
![image](https://user-images.githubusercontent.com/19309481/134478690-1a451fb4-592f-4209-9ef6-63eb4bcd1e81.png)
