### ISSUE TITLE
AttributeError: module 'config' has no attribute 'Config'

### ISSUE THREAD

**Issue by zjwu0522** [thunlp/OpenKE#326]
Hi I use the code here:
import config
from  module.model import *
import json

con = config.Config()
but I get an AttributeError.

I checked the OpenKe/openke/config director and there is no config.py.
I am wondering how to fix it?
Thanks in advance.

**Comment by ShulinCao** [comment]
There are only trainer.py and tester.py in config. What do you mean by Config() ?
