### ISSUE TITLE
dataset for transr

### ISSUE THREAD

**Issue by PatelAxita** [thunlp/OpenKE#33]
I want to make a movie dataset for TransR as it requires triples, entities, and relations. How these three are considered for ex: in train2id.txt (0 1 0) means 0's are entities and 1 is their relation is it so or just sequence numbers?

**Comment by THUCSTHanxu13** [comment]
For each line in train2id.txt, its format is (h,t,r), h and t indicate the ids of head and tail entities, r indicates the ids of relations. For example, (1,2,0) means there is a relation Rel#0 between Ent#1 and Ent#2.

**Comment by PatelAxita** [comment]
Thankyou so much sir for replying and sir in entity2id.txt: "/m/06cx9" what it means

**Comment by ShulinCao** [comment]
That's the [Freebase ID](https://www.wikidata.org/wiki/Property:P646)

**Comment by THUCSTHanxu13** [comment]
"/m/XXXXX" is the entity id in Freebase (an existing large-scale knowledge graphs). If you want to know more information about Freebase, you can search on https://developers.google.com/freebase/ or https://www.wikidata.org/wiki/Wikidata:Main_Page.

**Comment by AxitaPatel** [comment]
thankyou sir
