### ISSUE TITLE
我想请问一个关于预测的问题

### ISSUE THREAD

**Issue by silverbulle** [thunlp/OpenKE#331]
您好，我打算使用您的模型对自建的一个数据集进行关系预测，但是我发现在Test模块中只找到了对缺失头实体和尾实体的预测，如果我想要实现“输入两个实体，得到两个实体间的关系”这样的效果，我应该怎么做呢？需要从C++处进行改动编译么？

**Comment by THUCSTHanxu13** [comment]
不用改c++吧。模型层面有塞入三元组，然后给你返回分数的接口。给定头尾实体的话，你枚举下关系构建三元组，然后直接塞到模型算分数就行了。
