### ISSUE TITLE
loss下降，但是hit@1 hit@5和hit@10等却都下降了

### ISSUE THREAD

**Issue by mug2mag** [thunlp/OpenKE#332]
我用了自己的中文数据集(74497个实体、218个关系，20万个三元组)训练complEx模型，发现epoch为10(最后的loss是21)的时候最好。但是epoch设置更高的时候，loss是更小的，比如loss为5.1，但是最后hit@1 hit@5和hit@10等的结果却都下降了，不知道为什么
补充：应该不是过拟合，因为当我把训练集的比例调大，验证集和测试集的比例调小(从5:1:1调整到8:1:1)，hit@1 hit@5和hit@10的结果是提高了的

求帮忙看看是为什么 @THUCSTHanxu13

**Comment by THUCSTHanxu13** [comment]
多半是过拟合了。complex用的adagrad，还挺容易过拟合的。

**Comment by THUCSTHanxu13** [comment]
另外，如果你训练集多了的话，hit@N天然的会提高吧，因为测试样本少了，训练数据多了，理论上任务变的更简单了。当然测试集变小，结果的方差也会变大。
