### ISSUE TITLE
用全部数据训练complex模型，用其中一部分数据作为测试，效果却非常不好

### ISSUE THREAD

**Issue by mug2mag** [thunlp/OpenKE#333]
还有一个点很奇怪，就是我拿全部的数据训练，用其中的一部分数据作为测试，结果极差，hit@100.0002。我在想测试数据和训练数据都是一样的了，为什么效果还是这么差 (loss为18)

Any reply will be very appreciated! @THUCSTHanxu13

**Comment by ShulinCao** [comment]
你是按照example里的示例训的吗？可否提供一些详细信息，比如训练的超参
