### ISSUE TITLE
MarginLoss And SigmoidLoss的一些问题

### ISSUE THREAD

**Issue by SylarWu** [thunlp/OpenKE#336]
你好，你们的Negative Sampling应该是参考的RotatE里面的self-adversarial方法吧。
不知道我理解的对不对啊，如果有问题希望能指出来。
在RotatE论文里面的self-adversarial negative sampling里面公式是
![image](https://user-images.githubusercontent.com/28731355/134273820-05587be9-f405-467a-b390-5d77674ff3c0.png)
也就是说负样本的得分越大那么所占的比重越大。
![image](https://user-images.githubusercontent.com/28731355/134273891-cadd2db4-ac91-475c-b376-ba0e05bbaf18.png)
整个loss里，正样本得分越高那么loss越大，相反的负样本得分越低loss越大，那么相应的分类就是正样本得分小，负样本得分高，那么加上上述的softmax即平衡了负样本的loss，即得分高的负样本相应的loss会小，而比重变大了，反之亦然。

在SigmoidLoss里：没有使用margin，正样本直接输入至logsigmoid，那么正样本得分越高loss越小，则是期望正样本得分高。负样本得分越高loss越大，期望负样本得分低。而get_weights里得分越高比重越大，也就说强化了错误的比重，而并不是RotatE里面平衡的想法。

在MarginLoss里：p_score - n_score，那么这样是期望正样本得分低，负样本得分高，与SigmoidLoss的期望完全是相反的。

总的来说，按我的理解来说，就是上述两个loss期望不同，那么不同loss训练出来的模型后续进行通过得分预测的实现也会有一定问题，如果我的理解有误，希望作者指出来，也希望作者在代码里多加点注释。

**Comment by ShulinCao** [comment]
其实两个loss的期望是相同的，把score理解为三元组存在合理性的话，两种loss都是期望正例的合理性高，负例的低。具体你可以看下 https://aclanthology.org/D18-2024.pdf里对scoring function的阐述
