### ISSUE TITLE
在Tester.py部分的run_link_prediction那里不知道是如何计算score的

### ISSUE THREAD

**Issue by Samuel123-hub** [thunlp/OpenKE#337]
在Tester.py部分的run_link_prediction那里不知道是如何计算score的，这个hits10、meanrank的得分是如何计算的，看不懂

**Comment by ShulinCao** [comment]
你可以看下https://github.com/thunlp/OpenKE/blob/bc64ca73f6ca9363fff62d6132d75a5bcea13d8e/openke/base/Test.h#L65
