### ISSUE TITLE
I would like to know what is the difference between these two calculation methods?

### ISSUE THREAD

**Issue by mxuran** [thunlp/OpenKE#339]
`		if mode == 'head_batch':
			score = h + (r - t)
		else:
			score = (h + r) - t`

**Comment by LiuYuemei111** [comment]
You are right, their results are same. It is written for understanding.   When you set sampling_mode=‘head_batch’, you will find that the sizes of h, r and t are different under 'head_batch' and 'tail_batch'，such as
`head_batch, h=torch.Size([26, 2721, 200]), r=torch.Size([1, 2721, 200]), t=torch.Size([1, 2721, 200])`
`tail_batch, h=torch.Size([1, 2721, 200]), r=torch.Size([1, 2721, 200]), t=torch.Size([26, 2721, 200])`

**Comment by mxuran** [comment]
@LiuYuemei111 Okay, thanks for your answer~

**Comment by FirstDiscoverer** [comment]
:+1: :+1: :+1:
