### ISSUE TITLE
datasets里面train2id,test2id,valid2id,entity2id,relation2id数据具体的格式？

### ISSUE THREAD

**Issue by qyin863** [thunlp/OpenKE#34]

**Comment by ShulinCao** [comment]
For training, datasets contain three files:
train2id.txt: training file, the first line is the number of triples for training. Then the follow lines are all in the format (e1, e2, rel).
entity2id.txt: all entities and corresponding ids, one per line. The first line is the number of entities.
relation2id.txt: all relations and corresponding ids, one per line. The first line is the number of relations.

For testing, datasets contain additional two files (totally five files):
test2id.txt: testing file, the first line is the number of triples for testing. Then the follow lines are all in the format (e1, e2, rel).
valid2id.txt: validating file, the first line is the number of triples for validating. Then the follow lines are all in the format (e1, e2, rel).

**Comment by qyin863** [comment]
我就是这样格式调的，
但是在debug的时候到self.lib.importTrainFiles就跳出了，
我entity2id,relation2id里面是中文，不知道会不会有问题

**Comment by qyin863** [comment]
因为这边我没办法看importTrainFiles里面到底出了什么问题，
不知道能否我把转换过的这5个文件发给  这个项目的作者？
那边调试下，看看问题能否解决？不知道是否可以

**Comment by qyin863** [comment]
![default](https://user-images.githubusercontent.com/37169003/38556715-37b969d6-3cfd-11e8-9c4e-a2d0b4265ae8.png)

**Comment by ShulinCao** [comment]
应该不是entity2id,relation2id的问题，你可以看一下OpenKE/base/Reader.h里的代码

**Comment by THUCSTHanxu13** [comment]
如果你数据不敏感的话可以发给我看一下cst_hanxu13@163.com

**Comment by qyin863** [comment]
可以啦
环境python,gcc有要求，我昨天代码跑通了
谢谢你，手动点赞！






发自网易邮箱大师


在2018年04月16日 00:31，SillyXu<notifications@github.com> 写道：

如果你数据不敏感的话可以发给我看一下cst_hanxu13@163.com
