### ISSUE TITLE
neg_ent和neg_rel

### ISSUE THREAD

**Issue by mxuran** [thunlp/OpenKE#342]
您好，请问neg_ent和neg_rel参数，在链接预测和关系预测等任务上有何区别？代码中设置neg_ent=25和neg_rel=0，在关系预测时，是否需要进行调整？祝好。

**Comment by LiuYuemei111** [comment]
是有区别的，需要调整。目前负采样设置(neg_ent=25和neg_rel=0)只能用于链接预测，在关系预测上会很差。如果想用于关系预测，可以尝试增加关系的负采样，如neg_ent=0和neg_rel=25.
