### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by justyyau** [thunlp/OpenKE#344]
Input Files Path : ./benchmarks/WN18RR/
The toolkit is importing datasets.
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

how to deal with this problem????

**Comment by FirstDiscoverer** [comment]
me too ......

**Comment by FirstDiscoverer** [comment]
解决了，参考链接 https://issueexplorer.com/issue/thunlp/OpenKE/264

是路径的问题，把：
train_dataloader = TrainDataLoader(
in_path = "./benchmarks/custom/",
nbatches = 100,
threads = 8,
sampling_mode = "normal",
bern_flag = 1,
filter_flag = 1,
neg_ent = 25,
neg_rel = 0)
中的in_path = "./benchmarks/custom/"改为in_path = "../benchmarks/custom/"就可以运行了

**Comment by justyyau** [comment]
好的，非常感谢
