### ISSUE TITLE
简单疑问

### ISSUE THREAD

**Issue by skey-yk** [thunlp/OpenKE#349]
trans系列经常看到如下片段代码，想问下h+(r-t)和(h+r)-t区别是什么？为什么分开要这两种写法？
		if mode == 'head_batch':
			score = h + (r - t)
		else:
			score = (h + r) - t

**Comment by FirstDiscoverer** [comment]
同问
head_batch是把head替换了，但是这两个公式表达是一样的

**Comment by LiuYuemei111** [comment]
请参考#339
