### ISSUE TITLE
Results of TransE

### ISSUE THREAD

**Issue by AxitaPatel** [thunlp/OpenKE#35]
Sir, how can i get accuracy i want to find precision from confusion matrix and im getting my results something like this 
![transeoutput](https://user-images.githubusercontent.com/38253850/38562720-d54bca9a-3cf8-11e8-93fb-28b08eab56e0.JPG)

**Comment by ShulinCao** [comment]
You can see #23

**Comment by THUCSTHanxu13** [comment]
The result is used to test embeddings with the default metric, and the results are like as follows,
    (?, r, t) : Mean rank, Hit 10, Hit 3, Hit 1
    (?, r, t) : Mean rank(filter), Hit 10(filter), Hit 3 (filter), Hit 1(filter)
    (h, r, ?) : Mean rank, Hit 10, Hit 3, Hit 1
    (h, r, ?) : Mean rank(filter), Hit 10(filter), Hit 3 (filter), Hit 1(filter).
More details you can find in "Bordes et al. Translating Embeddings for Modeling Multi-relational Data (2013) "
