### ISSUE TITLE
windows不能用？C必须要32位python，但是pytorch又没有32位的

### ISSUE THREAD

**Issue by zzyo-yu** [thunlp/OpenKE#352]

**Comment by LiuYuemei111** [comment]
是的，目前该工具包不支持Windows上运行，其中的C代码部分使用了一些依赖包不能在windows编译

**Comment by Nazzcjy** [comment]
用minGW-w64对make.sh文件重新编译就可以在windows跑了

**Comment by Nazzcjy** [comment]
我试了用minGW-w64对make.sh文件重新编译就可以在windows上运行了

**Comment by justdoit0** [comment]
> 我试了用minGW-w64对make.sh文件重新编译就可以在windows上运行了

请问可以分享一下是如何重新编译的吗，我也有MinGW-w64 但是还是会报错啊，是需要执行什么操作吗，谢谢！
