### ISSUE TITLE
A Possible Problem In PyTorchTrainDataLoader.py

### ISSUE THREAD

**Issue by Mateng0228** [thunlp/OpenKE#354]
Hello! 
I've been looking at the OpenKE's codes (in OpenKE-PyTorch branch). I found that there are two versions of TrainDataLoader, one named 'TrainDataLoader.py' calls the routine written by C programs, and the other named 'PyTorchTrainDataLoader.py' uses only Python.

When it comes to constructing the negative examples using 'bern' method, the two DataLoaders seem to have different behaviors, and I think the relevant codes in 'PyTorchTrainDataLoader.py' maybe wrong. Here are the codes I mentioned:

```python
neg_size_h = 0 # the number of corrupted triplets whose head entity is replaced
neg_size_t = 0 # the number of corrupted triplets whose tail entity is replaced
prob = self.rig_mean[r] / (self.rig_mean[r] + self.lef_mean[r]) if self.bern_flag else 0.5
    for i in range(neg_size):
	if random.random() < prob:
	    neg_size_h += 1
	else:
	    neg_size_t += 1
```

According to the codes above, the variable **prob** should be the probability of corrupting the triplet by replacing the head. But  **self.left_mean** and **self.rig_mean** are Initialized like this:

```python
for r in range(self.rel_total):
	self.h_of_r[r] = np.array(list(self.h_of_r[r].keys()))
	self.t_of_r[r] = np.array(list(self.t_of_r[r].keys()))
	self.lef_mean[r] = self.freqRel[r] / len(self.h_of_r[r])
	self.rig_mean[r] = self.freqRel[r] / len(self.t_of_r[r])
```

Because  **self.freqRel[r]** is the number of triplets which contain **r** and  **self.h_of_r[r]** is an array which contains all distinct head entities shown up together with **r** ,  **self.lef_mean** should be the average number of tail entities per head entity given the same **r** (shorthand for **tph**).  In a same way, **self.rig_mean**  should be **hpt**.

If we look back at the codes that got the **prob**:

```python
prob = self.rig_mean[r] / (self.rig_mean[r] + self.lef_mean[r]) if self.bern_flag else 0.5
```

We can get **prob = hpt / hpt + tph**, which means **prob** should be the probability of  corrupting the triplet by replacing the tail entity, so the first piece of codes maybe wrong.

By the way, I noticed that the corrupting logic between 'TrainDataLoader.py' and 'PytorchTrainDataLoader.py' is quite different(besides the coding language). I haven't done performance testing, but I think the former is probably faster under the same conditions.  

Thank you for reading my issue. If there are mistakes, please let me know.

**Comment by lwlyee** [comment]
I also noticed this problem. Through testing I found that the effect of the Pytorch version is much worse than the effect of the C++ version. I went through the code for the C++ version and found a possible cause.
in [openke/base/Base.cpp](https://github.com/thunlp/OpenKE/blob/OpenKE-PyTorch/openke/base/Base.cpp)

```
if (randd(id) % 1000 < prob) {   
	batch_h[batch + last] = trainList[i].h;  
	batch_t[batch + last] = corrupt_head(id, trainList[i].h, trainList[i].r);  
	batch_r[batch + last] = trainList[i].r;  
} else {  
	batch_h[batch + last] = corrupt_tail(id, trainList[i].t, trainList[i].r);  
	batch_t[batch + last] = trainList[i].t;  
	batch_r[batch + last] = trainList[i].r;
}
```
when < prob, what it really does is destroy the tail entity, but named the function as 'corrupt_head', which may lead to the following problems when implementing the Pytorch version.
in [openke/data/PyTorchTrainDataLoader.py](https://github.com/thunlp/OpenKE/blob/OpenKE-PyTorch/openke/data/PyTorchTrainDataLoader.py)
```
for i in range(neg_size):
	if random.random() < prob:
		neg_size_h += 1
	else:
		neg_size_t += 1

neg_list_h = []
neg_cur_size = 0
while neg_cur_size < neg_size_h:
	neg_tmp_h = self.__corrupt_head(t, r, num_max = (neg_size_h - neg_cur_size))
	neg_list_h.append(neg_tmp_h)
	neg_cur_size += len(neg_tmp_h)
if neg_list_h != []:
	neg_list_h = np.concatenate(neg_list_h)
	
neg_list_t = []
neg_cur_size = 0
while neg_cur_size < neg_size_t:
	neg_tmp_t = self.__corrupt_tail(h, r, num_max = (neg_size_t - neg_cur_size))
	neg_list_t.append(neg_tmp_t)
	neg_cur_size += len(neg_tmp_t)
if neg_list_t != []:
	neg_list_t = np.concatenate(neg_list_t)
```
when < prob, what it really does is destroy the head entity. They are completely contradictory.
so I change the code as:
```
for i in range(neg_size):
	if random.random() < prob:
		neg_size_t += 1
	else:
		neg_size_h += 1
```
Through testing, it has achieved the same effect as the C++ version

**Comment by Mateng0228** [comment]
> when < prob, what it really does is destroy the head entity. They are completely contradictory. so I change the code as:

Personally, I think you're on the point. But unlike you, I modified the C + + version,hahah.
