### ISSUE TITLE
Is there any explanation about the testing results?

### ISSUE THREAD

**Issue by yhshu** [thunlp/OpenKE#355]
Actually I'm not doing a research on link prediction task, but just wanna get an embedding result.
I'm a little confused how to understand the testing results such as `left`  `right` `left(filter)` and `right(filter)`?

Thanks.

**Comment by LiuYuemei111** [comment]
`right`: predict the tail entity when given a triple (h, r, ?),  
`left`:  predict the head entity when given a triple (?, r, t)
`right(filter)`, `left(filter)`:  filter out predicted relations that already appear in the training set
