### ISSUE TITLE
bash make.sh报错

### ISSUE THREAD

**Issue by ghost** [thunlp/OpenKE#356]
mac M1 运行bash make.sh 报错如下
clang: error: the clang compiler does not support '-march=native'
但是我下载了gcc的环境，还是报这个错。请问是我gcc没有安装正确还是其他什么问题？
求解。。。

**Comment by LiuYuemei111** [comment]
请参考该回复 https://github.com/thunlp/OpenKE/issues/323#issuecomment-925542703
