### ISSUE TITLE
小疑问：改进后的模型反而效果不好？

### ISSUE THREAD

**Issue by wangcccchen** [thunlp/OpenKE#358]
TransH、TransR和TransD都是基于TransE模型进行改进的，但是跑出来的实验效果却都没有TransE好，想请问以下这是什么原因呀？

**Comment by Siziyou** [comment]
我想改进=实验效果好，这是未必的，对不同的数据，不同的方法具有不同的拟合特性。我也使用过Trans系列模型，以及部分语义模型，也都尝试做了写改进，但效果都未能如愿。
我认为这背后的主要原因就是数据问题。现实中的数据很复杂，在这种情况下，不知你是否做足了参数的调整与嵌入方案的设计。如果没做好，我想出现“负优化”的情况也是可以理解的。

**Comment by yuqiwang-vii** [comment]
> 我想改进=实验效果好，这是未必的，对不同的数据，不同的方法具有不同的拟合特性。我也使用过Trans系列模型，以及部分语义模型，也都尝试做了写改进，但效果都未能如愿。 我认为这背后的主要原因就是数据问题。现实中的数据很复杂，在这种情况下，不知你是否做足了参数的调整与嵌入方案的设计。如果没做好，我想出现“负优化”的情况也是可以理解的。

赞成！其实我一直也有这样的疑惑，听了你这么说我就明白了。 有时候改进的方向只是基于理论层面上的，在实践中结果不一定真正能够有所提升

**Comment by LiuYuemei111** [comment]
> TransH、TransR和TransD都是基于TransE模型进行改进的，但是跑出来的实验效果却都没有TransE好，想请问以下这是什么原因呀？

如果按照与论文数据集和设置相同的设置的话，应该可以得到一致的结论。 另外，不同的模型最优参数是不一样的，可以尝试一下调参
