### ISSUE TITLE
Are there any official benchmark results of the framework?

### ISSUE THREAD

**Issue by yuchenlin** [thunlp/OpenKE#36]
Hi, 

Thanks for this wonderful framework! 

I was wondering whether you have reported your official results (with hyper-parameters) on the WN18 or FB15K using this framework. I am trying to reproduce the results of TransE on the two benchmark datasets, while it seems to be hard to tune for a comparable result reported by other papers. 

Thus, I was thinking that you might have some benchmark results to verify that the framework could possibly reproduce similar results.

**Comment by ShulinCao** [comment]
We will soon report our benchmark results.

**Comment by yuchenlin** [comment]
Thanks for the prompt reply! Could you please provide **a typical great setting of the hyperparameters** for the FB15K dataset? The settings in the example*.py are like just for testing whether the framework can run successfully.

**Comment by ShulinCao** [comment]
The settings of OpenKE-PyTorch branch are what you want.

**Comment by yuchenlin** [comment]
@THUCSTHanxu13 I see! Thanks so much! I am trying to tune the parameters to reproduce reported performances of methods like ComplEX. Once I got some promising results, I will post the hyper-parameters here.

**Comment by rlafraie** [comment]
Hi @yuchenlin,

I know this issue is closed, but I'm currently looking for the optimal parameters, too.
Could you therefore please share the parameters especially for the WN18 dataset. The OpenKE-PyTorch (old) branch does only include them for the FB15K dataset.

Many Thanks in Advance!
