### ISSUE TITLE
请问最新版的openke-pytorch如何获得模型学习到的知识图谱表示学习的矩阵？

### ISSUE THREAD

**Issue by lizhixi212** [thunlp/OpenKE#360]
文档只有老版的方法

**Comment by LiuYuemei111** [comment]
请模型有对应接口https://github.com/thunlp/OpenKE/blob/bc64ca73f6ca9363fff62d6132d75a5bcea13d8e/openke/module/BaseModule.py#L32
通过`model.save_parameters(path)`可以保存训练好的图谱嵌入向量。
