### ISSUE TITLE
只训练的情况下，train triples 数量减少的问题？请问如何解决？还是代码对三元组有筛选？triples从8643->4101

### ISSUE THREAD

**Issue by feitboiling** [thunlp/OpenKE#361]
![Snipaste_2022-03-19_17-26-37](https://user-images.githubusercontent.com/59522921/159115620-47d72665-c272-4c06-939d-8050da0f463e.jpg)
![Snipaste_2022-03-19_17-26-43](https://user-images.githubusercontent.com/59522921/159115628-686ebb11-7a91-41f3-84b3-8484ad4f7fe1.jpg)

**Comment by s821220** [comment]
我也碰到了这种情况

**Comment by feitboiling** [comment]
问题解决了，是我的训练数据 里面有重复的三元组
