### ISSUE TITLE
Error in HolE.py: module 'torch' has no attribute 'rfft' with PyTorch

### ISSUE THREAD

**Issue by Kunlun-Zhu** [thunlp/OpenKE#362]
Line 61: 'a = self._conj(torch.rfft(a, signal_ndim = 1, onesided = False))'
Line62: 'b = torch.rfft(b, signal_ndim = 1, onesided = False)'
Line 64: 'res = torch.ifft(res, signal_ndim = 1)'

Current pytorch seems no longer support torch.rfft & torch.ifft anymore(since torch 1.8),
I am currently try to fix this by using torch.fft.rfft & torch.fft.ifft instead

**Comment by Kunlun-Zhu** [comment]
def _ccorr(self, a, b):
		'''
		original ccorr:
		a = self._conj(torch.rfft(a, signal_ndim = 1, onesided = False))
		b = torch.rfft(b, signal_ndim = 1, onesided = False)
		res = self._mul(self._real(a), self._imag(a), self._real(b), self._imag(b))
		res = torch.ifft(res, signal_ndim = 1)
		return self._real(res).flatten(start_dim = -2)
		'''
		a = self._conj(torch.view_as_real(torch.fft.fft(a, dim = 1)))
		b = torch.view_as_real(torch.fft.fft(b, dim = 1))
		res = self._mul(self._real(a), self._imag(a), self._real(b), self._imag(b))
		res = torch.fft.ifft(torch.view_as_complex(res), n=res.shape[1], dim=1)
		return self._real(res).flatten(start_dim = -2)
This is how I handle it for now, not sure if this would be appropriate.

**Comment by LiuYuemei111** [comment]
换个支持该接口的pytorch版本
