### ISSUE TITLE
The total of train triples mismatch with actual number

### ISSUE THREAD

**Issue by dayuyang1999** [thunlp/OpenKE#364]
Hi THUNLP group,

I encountered an issue that: although my train2id has totally 574457 lines, the code always shows "The total of train triples is 299929." (which is much smaller than 574457)

I am not sure what caused this issue.

My train2id.txt is like:
![image](https://user-images.githubusercontent.com/60718476/163827353-dca31642-8516-483c-84b5-16150c0a73b8.png)
![image](https://user-images.githubusercontent.com/60718476/163827449-a4d776da-fb0c-4e45-bace-719f9dfd1fe7.png)

I create this file by adding "a space" among (node, node, relation), and add a "\n" after each relation tuple (node, node, relation).

However, the system report:
![image](https://user-images.githubusercontent.com/60718476/163827566-09518b8c-d67f-4c90-a249-582ab421a832.png)

Thanks

**Comment by dayuyang1999** [comment]
By the way, I checked the entity both in lines 299929 and 299930 in train2id file. They are all in entity2id file.

**Comment by dayuyang1999** [comment]
Ok, I found the reasons.

For people with similar issues, please check if:
- each relation only shows once in your dataset
- if there is relation like (me, me, 0)

**Comment by allohvk** [comment]
Any reason why we eliminate duplicates? Let us say we are scraping from a large internet DB. There could be relations that are strongly reinforced multiple times, other relations which may appear once or twice (in some incorrect website). When trained on the entire corpus, the model will ignore the incorrect relationships. Let us say a relation appears about 100 times in the corpus. 99 of the websites got it right and 1 website got it wrong. If trained with the entire corpus, the correct info will outweigh the wrong one (in the embeddings). If duplicates are eliminated, we get 1 correct and one incorrect relationship which will be impossible to train. I understand this is not a bug but I am curious to know your thoughts on this
