### ISSUE TITLE
Example in documentation does not work

### ISSUE THREAD

**Issue by dayuyang1999** [thunlp/OpenKE#365]
Hi,

I am trying the examples in your [documentation](http://139.129.163.161/static/notes/train.html), but it does not work.

The error is :
<img width="343" alt="image" src="https://user-images.githubusercontent.com/60718476/163737237-c8950fec-f520-4ba6-8432-ac2942975399.png">

is there any version requirement for config module?

**Comment by LiuYuemei111** [comment]
The document is for the branch [OpenKE-PyTorch(old)](https://github.com/thunlp/OpenKE/tree/OpenKE-PyTorch(old)).
For the branch  [OpenKE-PyTorch](https://github.com/thunlp/OpenKE), please refer to the examples in the folder "./examples/"
