### ISSUE TITLE
Entity to id

### ISSUE THREAD

**Issue by latuanvinh1998** [thunlp/OpenKE#368]
Dear author, thanks for your great work.
I wanna ask that how can I convert entity like 'barack obama' to corresponding id in entity2id.txt.
I read alot in issue and instruction from your github but I cannot see where you mention it.
Thank you for spending time for reading my issue.

**Comment by LiuYuemei111** [comment]
This entity id can be defined by yourself. You first get a list of all entities, then assign each entity a unique numeric id to obtain the entity2id. Similar to get relation2id.  Next, you turn all entity relations into relation2id based on the entity2id and relation2id.

**Comment by hsfzxjy** [comment]
@latuanvinh1998 @LiuYuemei111 

Sorry for replying to this closed issue, but I am still confused about how to map an entity name to its id.

Currently I am using services like TAGME to detect entities in texts, and I am going to use the pretrained embeddings from [here](http://139.129.163.161/index/toolkits#pretrained-freebase) to extract a feature vector to each entity.

Could somebody enlight me how to map a word like 'barack obama' to one of those `m.xxxxx`? Appreciate for your help!
