### ISSUE TITLE
IndexError: index out of range in self

### ISSUE THREAD

**Issue by dejuzhang** [thunlp/OpenKE#369]
运行官方的examples中的代码也会出现“IndexError: index out of range in self”这个问题，请问这是什么原因呢？谢谢。

**Comment by LiuYuemei111** [comment]
请问是哪个example？

**Comment by dejuzhang** [comment]
是make.sh的编译问题， 我已经解决了，不好意思，打扰了。


| |
张德举
|
|
***@***.***
|
签名由网易邮箱大师定制
On 6/6/2022 22:05，Yuemei ***@***.***> wrote：

请问是哪个example？
