### ISSUE TITLE
[feature request] consider supporting MRR metric in the test?

### ISSUE THREAD

**Issue by yuchenlin** [thunlp/OpenKE#37]
Hi,

I found that most recent papers do not use Mean Rank as their evaluation metrics anymore. Instead, [Mean Reciprocal Rank (MRR)](https://en.wikipedia.org/wiki/Mean_reciprocal_rank) seems to be a more popular alternative. Do you think it is easy to support this metric?  

Best,

**Comment by ShulinCao** [comment]
Thank you for you advice. MRR has been supported.

**Comment by yuchenlin** [comment]
Thanks! Did you mean MRR is already implemented in the tf or pytorch branch? I mainly used pytorch branch and did not see MRR in results.  

Actually, I just implement MRR calculation in the Test.h of my own local version and will start a pull request to the pytorch branch soon.

**Comment by ShulinCao** [comment]
MRR was already implemented in the pytorch branch. And here is an example of MRR results.
![image](https://user-images.githubusercontent.com/19309481/38780355-a28ff686-4107-11e8-86c4-5d1805452ef5.png)

**Comment by ShulinCao** [comment]
MRR was already implemented in the pytorch branch. And here is an example of MRR results.
![image](https://user-images.githubusercontent.com/19309481/38780376-e96d8a14-4107-11e8-8fe4-230f1d345997.png)

**Comment by yuchenlin** [comment]
Oh, I see. Sorry for not noticing your commits 30 mins ago. Well done! Thanks!
I have also implemented some minor codes for better result presentation, which will be in my later pull request! 

Best,
