### ISSUE TITLE
训练集过大时出现段错误

### ISSUE THREAD

**Issue by leeruibin** [thunlp/OpenKE#39]
您好，我在使用平台测试我自己的样本的时候出现了段错误，我调试+搜了好多相关的内容定位到了出错的位置在config.py 文件中的self.lib.importTrainFiles()句中，我在网上看到的是由于在import训练集的时候太大在c返回给python的时候就会有段错误，但我搜了很多也没有搜索到解决方案，想咨询一下你们是怎么处理的，我的训练集文件大小22M

**Comment by THUCSTHanxu13** [comment]
方便的话可否把数据发给我，我调试下。。。

**Comment by THUCSTHanxu13** [comment]
是数据格式问题吧。我们这边输入的格式是头实体，尾实体，关系。
The first line is the number of triples. Then the follow lines are all in the format (e1, e2, rel).

**Comment by leeruibin** [comment]
是的！！是我疏忽了，感谢！！
