### ISSUE TITLE
OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by ChacesXia** [thunlp/OpenKE#4]
![image](https://user-images.githubusercontent.com/15275744/32589117-a54f0c3a-c54d-11e7-8ab8-3f4e9ad91140.png)
Hi, thunlp:

  when I try run example.py after run bash make.py, console show this, how can I fix that? thanks.

**Comment by gavinjou818** [comment]
i think you should use the python2.7  ...

**Comment by ChacesXia** [comment]
Thank you, I have try it. but I use it in windows OS. If I use python27, and I will not use tensorflow.

**Comment by binjiaqm** [comment]
I think you need to use Linux.

**Comment by zhaodongh** [comment]
i use the python2.7 ... and run the file ./make.sh firstly ,but i get a mistake:

![image](https://user-images.githubusercontent.com/29967198/33125646-4ca8159e-cfbc-11e7-8149-4899b43cd73a.png)
段错误（核心已转储）
what should i do? thank you!

**Comment by binjiaqm** [comment]
This is due to the IO problem.  Change './data/FB15K/' to './benchmarks/FB15K/'
