### ISSUE TITLE
An issue about the file "Reader.h"

### ISSUE THREAD

**Issue by Syunzhou** [thunlp/OpenKE#41]
![default](https://user-images.githubusercontent.com/32785348/39041852-1ab196ee-44bc-11e8-8ee6-b4e77424fd2d.PNG)
in the line 106, the range of 'j' is from 'lefHead[i] + 1' to 'rigHead[i]-1', why not it is from 'lefHead[i] + 1' to 'rigHead[i]'?

**Comment by arthurcgusmao** [comment]
@Syunzhou , I have verified the code and indeed it looks like you are correct. Tests I have made show that `left_mean` and `right_mean` are incorrect when `j < rigHead[i]`. I will open a pull request on this. Thanks for your observation.
