### ISSUE TITLE
预训练嵌入下载

### ISSUE THREAD

**Issue by xlx0010** [thunlp/OpenKE#43]
我想下载wiki的预训练嵌入，可是这个网站http://openke.thunlp.org/download/wikidata显示not found了?
谢谢！

**Comment by THUCSTHanxu13** [comment]
原来发在百度网盘上，不过百度网盘速度巨慢，我们正在往云服务器上搬，需要一些时间，不过应该很快就好了

**Comment by xlx0010** [comment]
哦好的，谢谢！
