### ISSUE TITLE
请问近期的更新是否更新了tensorflow的版本

### ISSUE THREAD

**Issue by penelope24** [thunlp/OpenKE#46]
如题，我记得之前项目对应的TF版本是0.12，在更新后运行测试代码貌似遇到了tensorflow版本不兼容的情况。谢谢

**Comment by THUCSTHanxu13** [comment]
= =! 你说的有道理，我们处理下，新版本和这一版本确实有不少出入。。。

**Comment by penelope24** [comment]
@THUCSTHanxu13 哈哈好赞！辛苦！

**Comment by penelope24** [comment]
@THUCSTHanxu13 还有一个请求，就是是否能把新加入的triple classification accuracy写一个简介放到readme里边啊。因为我感觉应该有一些小白和我一样不太明白这个新的测试的具体含义吧。还有就是我发现test_link_prediction里新加入了一个metric叫做MRR，求问这个是什么意思啊，O(∩_∩)O谢谢！

**Comment by ShulinCao** [comment]
测试的具体含义我写了~

**Comment by penelope24** [comment]
@ShulinCao 看到了，非常感谢！

**Comment by xitongdashi** [comment]
Analogy model 指的是哪篇论文？链接可以发下吗？

**Comment by ShulinCao** [comment]
@xitongdashi  可以看下 [KRLPapers](https://github.com/thunlp/KRLPapers)

**Comment by xitongdashi** [comment]
@ShulinCao 谢谢

**Comment by THUCSTHanxu13** [comment]
现在应该在python2和python3上都可以运行，TensorFlow版本至少1.4.0是可以的
