### ISSUE TITLE
更新后貌似不能使用自己的数据集运行训练和测试代码

### ISSUE THREAD

**Issue by penelope24** [thunlp/OpenKE#47]
我不知道是不是自己的问题...但是同样的数据集在更新之前是可以跑的，更新之后会报错：
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
我看到之前的issue有的是因为三元组的顺序弄错了，但是我这个检查了一下是正确的，而且在之前的版本是可以正常运行的。

**Comment by penelope24** [comment]
目前已正常

**Comment by wangwangbobo** [comment]
你好，我也遇到了同样的问题，新版本上跑显示的是段错误（核心已转储），请问你是怎么解决的呢？

**Comment by Una-zh** [comment]
我也遇到这个问题了，请问您是怎么处理的哦？

**Comment by venusafroid** [comment]
> 
> 
> 你好，我也遇到了同样的问题，新版本上跑显示的是段错误（核心已转储），请问你是怎么解决的呢？

你好，我也遇到了同样的问题，请问你解决了吗？
