### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by sywang15** [thunlp/OpenKE#5]
Hi, 

When I run TransE, both of the python version and C version( from https://github.com/thunlp/KB2E ) rose "Segmentation fault".
My env is Python 3 +MacOS (I have already modified the init files to make them adapt to Python3)
![snip20171111_121](https://user-images.githubusercontent.com/33584473/32695811-e9a6c358-c734-11e7-8b14-f812b632f340.png)
![snip20171111_122](https://user-images.githubusercontent.com/33584473/32695812-e9b21d48-c734-11e7-888d-d9b9e4d3b391.png)

I would appreciate if you could help me on this. Thank you so much.

**Comment by Rahman29** [comment]
Check data file Path. data->FB15k->5 files  (paste this files in data folder or correct path in the code)
That works for me.

Cheers.
