### ISSUE TITLE
Imposing Type Constraints for Link Prediction

### ISSUE THREAD

**Issue by pmitra01** [thunlp/OpenKE#55]
Hi,
I was investigating the functionality around imposing type constraints - via the type_constrain.txt file. 
If i understand correctly, this has not been implemented for link-prediction yet, has it? Only triple_classification appears to be dependent on it, and the training of a model for triple classification on FB15K returns a segmentation fault when type_constrain.txt is removed. 
I have tried to understand the underlying implementation of type constraints in your code base, but have not been able to grasp it as clearly yet. Any elaboration on this would be much appreciated.

It would be interesting if type constraints are imposed on the link prediction task as one can force certain examples to label 0 based on the type constraints, which I feel would add valuable negative examples for learning. Otherwise, with uniform sampling for negative triples across the entire unrestricted range of entities, as is done now, we often return triples that could have directly been labeled as negative. 

Is this something we can implement here for link prediction? Or am I missing something? 

Thanks!

**Comment by ShulinCao** [comment]
I have impose type constraints for link prediction. Just try it!

**Comment by pmitra01** [comment]
Hi, 
Thanks for the prompt response. Which flag controls the incorporation of type constraints into the model? I could not find an appropriate argument in the config module. Thanks, in advance!

**Comment by ShulinCao** [comment]
con.set_link_prediction(True)

**Comment by pmitra01** [comment]
Ah, I just saw the commit you made yesterday. That was real quick, thanks! I shall try it out. :)
