### ISSUE TITLE
改变实体或关系个数，出现数组越界问题

### ISSUE THREAD

**Issue by wangwangbobo** [thunlp/OpenKE#56]
请问将实体或关系的个数变小就出现数组下标越界的问题怎么解决？本人c++小白，望作者告知，不胜感激

**Comment by THUCSTHanxu13** [comment]
因为程序会根据entity2id.txt以及relation2id.txt的第一行来开空间存储实体与关系向量的。
如果你设置小了的话，比如设成100。那么程序会认为实体编号不会超过100，但是你数据triple2id.txt或者train2id.txt里面的三元组编号会超过100呀，内存越界就段错误了。。。所以你数据要匹配呀，这样设置底层的C代码是会溢出的

**Comment by wangwangbobo** [comment]
这个问题在前几个月下载的老版本解决了，可以正常运行，但是现在的新版本还是不能运行，显示段错误（核心已转储），这是怎么回事呀？

**Comment by ShulinCao** [comment]
如果你有con.set_triple_classification(True), 数据集里需要有type_constrain这个文件，以及，你可能需要调整Reader.h里head_lef,head_type等几个数组的大小

**Comment by Tomposon** [comment]
@后来你怎么解决的呢？现在我也出现了这个问题 @wangwangbobo

**Comment by wangwangbobo** [comment]
@Tomposon 你说的是数组越界问题还是新旧版本不一致问题呢？

**Comment by Tomposon** [comment]
这个问题我已经解决了，应为我train2id文件的格式出了问题。对于test2id和valid2id的作用和构建是怎样的你知道吗？我很疑惑，看了TransEde Paper还是不知道测试的数据集是怎么构建的？ @wangwangbobo

**Comment by wangwangbobo** [comment]
@Tomposon 这个应该是随机抽取的吧！或者按照某种规则，论文中并没有提及如何划分数据集的吧！

**Comment by Tomposon** [comment]
好的，谢谢你。还有个问题想请教一下你。用TransE等方法进行知识表示学习的话，学习到的模型参数是不是只能表示在训练期间的实体和关系，如果在训练后又添加了一个实体的话，这个实体的向量是不是就表示不了，得对整个知识图谱重新学习啊？ @wangwangbobo

**Comment by wangwangbobo** [comment]
@Tomposon 我是这样理解的，应该得重新学习，要不然不能很好地表示它和其他实体间的关系

**Comment by Tomposon** [comment]
非常感谢 @wangwangbobo
