### ISSUE TITLE
Some question in trans embedding with sparse data?

### ISSUE THREAD

**Issue by caoxu915683474** [thunlp/OpenKE#58]
Thanks for your sharing! 
I have a dataset which contains more about 1w relations and 10w entities ,and the data is unbalanced. And I run this data in your work, but get very poor results.So how can I deal with this sparse data.Do you have some suggestions？

**Comment by THUCSTHanxu13** [comment]
I think that the default hyper-parameters in our examples may not suit for your dataset. Maybe you need to try other hyper-parameters on our models. I am sorry that I also have no idea how to train a great model for your sparse data.
