### ISSUE TITLE
关于运行环境版本以及Test问题的请教

### ISSUE THREAD

**Issue by 37man** [thunlp/OpenKE#59]
您好，非常感谢你们的付出，提供了很好的开源代码。有一些问题还望指教：1.运行环境版本问题，我这边download之后在本地运行有一些问题，我是python3.6+tensorflow1.0,代码不能直接运行，修改了一些地方：比如：print的地方加了（），比如模块导入的地方修改，比如con.set_in_path("./benchmarks/FB15K/")修改...等等，希望能把运行环境贴出来，方便大家运行。（2）在test中如何能获得MR,MRR,Hit@N的值？con.test()之后我这边没有输出MR,MRR,Hit@N。还望指教！谢谢！

**Comment by ShulinCao** [comment]
(1) 运行环境是python2.7+tensorflow1.0或python2.7+pytorch0.3
(2) 需要首先设置con.set_link_prediction(True)，你可以看下README里给出的example

**Comment by 37man** [comment]
好的，非常感谢，之前运行不知什么问题，设置了con.set_link_prediction(True)，但是显示的是nan,刚又调试了一下，又有结果了，再弱弱的问一句，输出中：
r_filter_s: 2
0.425640 0.549644 180.141312 93.602715
这些输出代表啥意思？（小白一枚，还望见谅，再次感谢）

**Comment by XianjingWang** [comment]
Hi Kangkang Li,

Can you share your code with Python3.6 and tensorflow1.0 version? Thank you very much.

regards,
Xianjing

**Comment by THUCSTHanxu13** [comment]
0.425640 0.549644 180.141312 93.602715这四个数分别是预测右侧实体的hit10准确率，hit10准确率（过滤之后的结果），平均排名，平均排名（过滤之后的结果），你可以参详下之前的论文来确认这些指标的意义。另外，现在的版本应该可以在python3上跑了。

**Comment by KAndHisC** [comment]
@THUCSTHanxu13 g++和gcc版本呢？
