### ISSUE TITLE
Test and Evaluation

### ISSUE THREAD

**Issue by asdassZY** [thunlp/OpenKE#6]
Hi friend, how to do the evaluation in OpenKE? I did not see this part in your readme. Thanks

**Comment by icaro56** [comment]
I did not see too. If I find the solution, I will post here

**Comment by JunhengH** [comment]
did you find any and add evaluation by yourself? @icaro56 @asdassZY thanks

**Comment by icaro56** [comment]
So, In the TensorFlow-TransX repository was added a example. See https://github.com/thunlp/TensorFlow-TransX

**Comment by JunhengH** [comment]
@icaro56  Thanks. One more thing to ask: Does it work? Any bugs that need to be fixed? Can it be applied in the code of OpenKE?

**Comment by icaro56** [comment]
@JunhengH , I don't know. I used the C version example presents in the [K2BE ](https://github.com/thunlp/KB2E)repository because the python version example presents in the TensorFlow-TransX had not example. But, now there is a example.

**Comment by JunhengH** [comment]
@icaro56 Did you do modifications on the C-version test example in KB2E to run test and evaluation on OpenKE? Could you please send me the test file if it works on testing OpenKE? Thanks.

**Comment by icaro56** [comment]
I just used the C-version KB2E project. I did not modify anything.

**Comment by THUCSTHanxu13** [comment]
I have add codes for testing, and details can be found in example_train_transe.py and example_test_transe.py.

**Comment by JunhengH** [comment]
Could you please provide the optimal hyperparameter settings if there is? Thanks~ @THUCSTHanxu13

**Comment by JunhengH** [comment]
Thanks @THUCSTHanxu13 ! Could you please provide optimal parameter settings if possible?
