### ISSUE TITLE
what are the functions of n-n.py?

### ISSUE THREAD

**Issue by bagindokemas** [thunlp/OpenKE#60]
Dear OpenKE team,

I check in the latest version of OpenKe, in each folder under benchmarks, you put n-n.py. 

What are the function of this n-n.py?

And does it have to do with the triple classification task? since the previous version did not have this n-n.py.

Thank you,
Kem

**Comment by ShulinCao** [comment]
If you run n-n.py, you can get the file type_constrain.txt, which is used for type constraint in link prediction task and triple classification task.
