### ISSUE TITLE
method for link prediction and triple classification with the embedded matrice?

### ISSUE THREAD

**Issue by leolle** [thunlp/OpenKE#63]
Hi, I want to know if there's a method to predict the link of (e1, ?, e2), and classification (e1, r1, e2)?, assumed that I have the pretrained embedding matrices get from http://openke.thunlp.org/index/toolkits#pretrained-embeddings.

**Comment by pushpankar** [comment]
Did you figure out? I also need to know the same.

**Comment by leolle** [comment]
@pushpankar not yet.

**Comment by pushpankar** [comment]
I wrote this function
`        def test_custom(self, entity, relation):
            test_h = np.array([entity]*self.entTotal)
            test_r = np.array([relation]*self.entTotal)
            test_t = np.array(range(self.entTotal))
            res = self.trainModel.predict(test_h, test_t, test_r).data.numpy().argmax()
            return res
`

But for some reason it return different results every time. And results are very bad.

**Comment by sahisnu** [comment]
Hi,

Just for a clarification, while testing a learned KBE model (DistMult, TransE etc) on a given KB, we evaluate the ranking performance of the model only on a generated candidate set of one positive and a set of negative tail entities or on full entity set of the graph?...... I mean if the KB has say total 14k entities, for each "**test**" query (h, r, ?), we generate 14k candidate triples using each of those 14k entities  {(h, t, e1), (h, t, e2), ....., (h, t, e_pos)......(h, t, e_14k)} and the model has to rank the positive entity "e_pos" higher among all those 14k candidate ones....right ?

**Comment by pushpankar** [comment]
Yes

> Hi,
> 
> Just for a clarification, while testing a learned KBE model (DistMult, TransE etc) on a given KB, we evaluate the ranking performance of the model only on a generated candidate set of one positive and a set of negative tail entities or on full entity set of the graph?...... I mean if the KB has say total 14k entities, for each "**test**" query (h, r, ?), we generate 14k candidate triples using each of those 14k entities {(h, t, e1), (h, t, e2), ....., (h, t, e_pos)......(h, t, e_14k)} and the model has to rank the positive entity "e_pos" higher among all those 14k candidate ones....right ?



> Hi,
> 
> Just for a clarification, while testing a learned KBE model (DistMult, TransE etc) on a given KB, we evaluate the ranking performance of the model only on a generated candidate set of one positive and a set of negative tail entities or on full entity set of the graph?...... I mean if the KB has say total 14k entities, for each "**test**" query (h, r, ?), we generate 14k candidate triples using each of those 14k entities {(h, t, e1), (h, t, e2), ....., (h, t, e_pos)......(h, t, e_14k)} and the model has to rank the positive entity "e_pos" higher among all those 14k candidate ones....right ?

Yes

**Comment by sahisnu** [comment]
Thanks @pushpankar for the prompt response
