### ISSUE TITLE
出现错误：OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by XianjingWang** [thunlp/OpenKE#67]
你好，
我在运行example_train_transe.py时出现一下错误：
OSError: [WinError 193] %1 is not a valid Win32 application

我使用的是windows 7，python3.6。

请问这个错误和windows相关吗？ 我改如何处理这个错误？ 谢谢！

Xianjing

**Comment by THUCSTHanxu13** [comment]
建议你在liunx上跑吧，我们没有尝试过在Win系统上运行。。。
