### ISSUE TITLE
Error: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by XianjingWang** [thunlp/OpenKE#68]
你好，

运行example_train_transe.py时没有错误，并且有输出。

但是，在运行train_transr.py时出现错误如下：
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

请问您知道原因吗？
谢谢！

regards，
Xianjing

**Comment by XianjingWang** [comment]
Thank you. I have solved this problem.

**Comment by RaymondTseng** [comment]
@XianjingWang 你好，请问是怎么解决这个问题的

**Comment by Una-zh** [comment]
我也遇到这个问题了，请问您是怎么处理的哦？

**Comment by FirstDiscoverer** [comment]
@XianjingWang 嗨，请问是怎么解决这个问题的

**Comment by FirstDiscoverer** [comment]
解决了，参考链接 https://issueexplorer.com/issue/thunlp/OpenKE/264

是路径的问题，把：
train_dataloader = TrainDataLoader(
in_path = "./benchmarks/custom/",
nbatches = 100,
threads = 8,
sampling_mode = "normal",
bern_flag = 1,
filter_flag = 1,
neg_ent = 25,
neg_rel = 0)
中的in_path = "./benchmarks/custom/"改为in_path = "../benchmarks/custom/"就可以运行了
