### ISSUE TITLE
关系文件中的/x/y/z/s全部都表示关系吗？

### ISSUE THREAD

**Issue by XianjingWang** [thunlp/OpenKE#72]
你好。
relation2id
关系文件中的/x/y/z/s全部都表示关系吗？ 还是，x表示头，s表示尾，中间的y，z是关系？

比如，下面的例子， user和player是头尾，中间是关系？
/user/szaijan/fantasy_football/position/player

谢谢！

**Comment by ShulinCao** [comment]
全部都表示关系

**Comment by THUCSTHanxu13** [comment]
freebase的关系是有层次性的，每一层都有意义，通常是topic/domain/...，你可以查一下

**Comment by XianjingWang** [comment]
谢谢回复！

regards,
Xianjing
