### ISSUE TITLE
What does valid_neg file present for each row/column? How do we get this negative triple?

### ISSUE THREAD

**Issue by XianjingWang** [thunlp/OpenKE#73]
Hi guys,

Does anyone know that what valid_neg file present?  What are they used for? 

Is the valid_neg present the negative triple for valid2id file? I found that there are 50000 triples in valid2id file, but 100000 records/rows in valid_nag. Are they corresponding to each other?

How do we get this negative triple/data? Do we have code to get the the negative dataset in OpenKE? 

Thanks!
regards,
Xianjing

**Comment by ShulinCao** [comment]
Yes, you are right. This file is used for triple classification task, which is to confirm whether a given triplet (h; r; t) is correct or not. This task needs negative labels. Therefore, each golden triplet is corrupted to get one negative triplet. We construct the negative triplets following the same procedure used for FB13 in NTN.
