### ISSUE TITLE
TransE object has no attribute 'loss'

### ISSUE THREAD

**Issue by sgfin** [thunlp/OpenKE#75]
Thanks for what appears to be a great package.

When I try to run the example script in the PyTorch branch, the data is loaded correctly and then I get the following error:

```
Traceback (most recent call last):
  File "example_train_transe.py", line 26, in <module>
    con.set_model(models.TransE)
  File "OpenKE/config/Config.py", line 271, in set_model
    grads_and_vars = self.optimizer.compute_gradients(self.trainModel.loss)
  File ".conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 366, in __getattr__
    type(self).__name__, name))
AttributeError: 'TransE' object has no attribute 'loss'
```

Anyone else had this issue running the example?  Any ideas what's wrong?

**Comment by THUCSTHanxu13** [comment]
emmm，you run the example code in the tensorflow branch. Maybe, you can try again (https://github.com/thunlp/OpenKE/blob/OpenKE-PyTorch/example_train_transe.py).      grads_and_vars = self.optimizer.compute_gradients(self.trainModel.loss) is the code used in TensorFlow.
