### ISSUE TITLE
IDs for entities/relations and their place in the embedding matrix

### ISSUE THREAD

**Issue by Alekos92** [thunlp/OpenKE#79]
I would like to ask about the ids used for representing entities and relations in training files. 

Reading the provided datasets' files, I see that the indices are in ascending order from 0 to num of entities/relations - 1. Is that a requirement, or could we use some other form of IDs, for example some internal id of the knowledge graph?

Also, as I understand the embedding.vec.json file, the embeddings are provided in the same order as in entity2id.txt and relation2id.txt, is that correct? Would that work in case of random IDs?

**Comment by ShulinCao** [comment]
1. It is a requirement that the indices must be in ascending order from 0 to num of entities/relations - 1.
2. The embeddings are provided in the same order as in entity2id.txt and relation2id.txt. That wouldn't work in case of random IDs.

**Comment by Alekos92** [comment]
Thank you very much for your prompt response!
