### ISSUE TITLE
Freebase 1M dataset

### ISSUE THREAD

**Issue by UditGupta10** [thunlp/OpenKE#81]
The TransE paper mentions running tests on FB1m dataset. Could you include that dataset here, or refer to the resource where it can be found.
Thanks.

**Comment by THUCSTHanxu13** [comment]
Though TransE is tested on FB1M in the paper, however, the author did not release the dataset online. You can find other dataset from https://everest.hds.utc.fr/doku.php?id=en:transe, but, FB1M is not included. Maybe, you can construct the dataset by yourself, with the dump of Freebase https://developers.google.com/freebase/.
