### ISSUE TITLE
请问在embedding时出现的错误， 产生一个巨大的数字，是版本问题吗。

### ISSUE THREAD

**Issue by qinxiaoyu123** [thunlp/OpenKE#82]
InvalidArgumentError (see above for traceback): indices[0,0] = 1438814047995 is not in [0, 14951)
	 [[Node: model/loss/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@model/GradientDescent/update_model/ent_embeddings/ScatterSub"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/ent_embeddings/read, model/input/transpose, model/loss/embedding_lookup/axis)]]

**Comment by qinxiaoyu123** [comment]
是您提供的数据集，fb15k。我把tensorflow升级到了1.4.0也是同样的错误，谢谢您回复。

**Comment by ShulinCao** [comment]
在训练时候？

**Comment by qinxiaoyu123** [comment]
是的，在运行example_train_transe.py文件时。我是在windows系统运行，把make.sh中的命令复制到了命令行运行，是否是这样做出的问题。谢谢您

**Comment by THUCSTHanxu13** [comment]
-pthread 貌似不是windows下的库，编译出来的结果可能出问题，你可以在liunx体系的机器下试试看有没有问题了

**Comment by Subhanandh** [comment]
> -pthread 貌似不是windows下的库，编译出来的结果可能出问题，你可以在liunx体系的机器下试试看有没有问题了

How can I run the same on mac
