### ISSUE TITLE
Disable automatic export of model parameters to json files

### ISSUE THREAD

**Issue by villmow** [thunlp/OpenKE#84]
The Json files can get quite big when training a bigger model. As I save the embeddings in binary format, there is no need to save it as JSON. The model crashes however if I dont specify the outfiles via `con.set_out_files("...")`.

**Comment by THUCSTHanxu13** [comment]
You can find some interfaces in Config.py

	def get_parameters(self, mode = "numpy"):
		res = {}
		lists = self.get_parameter_lists()
		for var_name in lists:
			if mode == "numpy":
				res[var_name] = self.get_parameters_by_name(var_name)
			else:
				res[var_name] = self.get_parameters_by_name(var_name).tolist()
		return res

Use this interface, and you can save all parameters into a numpy array. Then, you can save this numpy array to a text file.

def set_parameters(self, lists):
		for i in lists:
			self.set_parameters_by_name(i, lists[i])
this interface will help you reload the parameters.
