### ISSUE TITLE
How to get the value of Score Function?

### ISSUE THREAD

**Issue by XianjingWang** [thunlp/OpenKE#85]
Hi Cao,

May I know how to get the value of Score Function for each prediction result?

For example, if we have a list of predicted tails (t1, t2, t3,...), how to find out the score function value for each prediction result? 

Which variable represents the score function for each prediction result?

Thank you very much.

regards,
Xianjing

**Comment by THUCSTHanxu13** [comment]
You can find what you want from the Config.py.

	def test_step(self, test_h, test_t, test_r):
		feed_dict = {
			self.trainModel.predict_h: test_h,
			self.trainModel.predict_t: test_t,
			self.trainModel.predict_r: test_r,
		}
		predict = self.sess.run(self.trainModel.predict, feed_dict)
		return predict

Use this function and pass into {(h,r,t1),(h,r,t2)...}, you can then achieve their scores.
