### ISSUE TITLE
关于G(h, r, t) = E(h, r, t) + E(h, P, t),   (2)

### ISSUE THREAD

**Issue by Xiaobenbenben** [thunlp/OpenKE#87]
您好：
        非常感觉您的代码分享。
        论文中有一点我没有很明白，按着公式2中定义的energy function，即G(h, r, t) = E(h, r, t) + E(h, P, t)，在做实体预测的时候G(h,r,t)的值越小，越排在前面，于是存在这样一个疑问。假如实体1与实体2有直接关系，但是没有间接关系，实体1与实体3既有直接关系又有间接关系，那如果给定实体1，来预测它的尾实体，按着这个公式是实体1的G值应该更小吧。求指点，不胜感激。

**Comment by THUCSTHanxu13** [comment]
预测的时候是给(h,r,?)来寻找t吧，并不是直接给1来预测t，任务应该不是这么定义的
