### ISSUE TITLE
problems with indenting of config/Config.py

### ISSUE THREAD

**Issue by bobdc** [thunlp/OpenKE#88]
Python complains about inconsistent indenting in https://github.com/thunlp/OpenKE/blob/master/config/Config.py, so example_train_transe.py won't run. 

Thanks,

Bob

**Comment by dugenkui03** [comment]
you can use this: https://github.com/dugenkui03/OpenKE/blob/dugk/config/Config.py . @bobdc

**Comment by bobdc** [comment]
That works, but then I get indenting errors about models/HolE.py, so I tried to just use the dugenkui03 branch instead of master, and I still got the HolE.py indenting errors.

**Comment by THUCSTHanxu13** [comment]
I have fixed the code, you can have a try again
