### ISSUE TITLE
Inconsistent `keep_dims = True` in `predict_def()`

### ISSUE THREAD

**Issue by tranhungnghiep** [thunlp/OpenKE#90]
I think there is an inconsistency here, in [`predict_def()`](https://github.com/thunlp/OpenKE/blob/master/models/DistMult.py#L45) it uses `keep_dims = True`:

    self.predict = -tf.reduce_sum(self._calc(predict_h_e, predict_t_e, predict_r_e), 1, keep_dims = True)

But in [`loss_def()`](https://github.com/thunlp/OpenKE/blob/master/models/DistMult.py#L33) it use `keep_dims = False`:

    res = tf.reduce_sum(self._calc(e_h, e_t, e_r), 1, keep_dims = False)

How does it affect the logic of [`Config.test()`](https://github.com/thunlp/OpenKE/blob/master/config/Config.py#L332)?  
Is it safe to use `keep_dims=False` in `predict_def()`?

Thanks

**Comment by THUCSTHanxu13** [comment]
res is a numpy array, its array address will be passed to C code. For C code, the shape of res is either (?,1) or (?) has no effect.
