### ISSUE TITLE
Pretrained Freebase embeddings

### ISSUE THREAD

**Issue by uganyasavur** [thunlp/OpenKE#92]
Hi,

I downloaded pre-trained embeddings for freebase. I would like to use it in my project, but I could not figure out how to use entity2vec file. The number of embeddings is not equal to the number of entities in entity2id.txt. 

See the following:
Entities:
There are 86054151 entities according to entity2id file.

vec = np.memmap('entity2vec.bin' , dtype='float32', mode='r')    
numberOfEmbeddings = vec.shape[0]/50
print(numberOfEmbeddings)
//prints 39056179.2

Relations:
When I do the same thing on relations, the number of relations and the number of embeddings are matching.

There are **14824** relations according to relation2id.txt file

relvec = np.memmap('relation2vec.bin' , dtype='float32', mode='r')
numberOfRelations = relvec.shape[0]/50
print(numberOfRelations)
//prints **14824**

I believe I need to access entities by slicing one huge numpy array with embeddings size which is 50. My experience with relations proved my intuition whereas same thing does not work for the entities. I am wondering what I am doing wrong? Any help will be appreciated.

**Comment by qige96** [comment]
I guess it is a bug, because I did the same thing as yours in the Wikidata pre-trained data and got the correct (expected) results.

**Comment by MathildaSu** [comment]
Hi, I used the same code to load the pretrained wikidata model, and got this error: ValueError: Size of available data is not a multiple of the data-type size. Do you know why? Thanks.
