### ISSUE TITLE
求WN18 valid2id.txt内部数据结构说明 

### ISSUE THREAD

**Issue by luoming110** [thunlp/OpenKE#97]
您好，有谁能提供一下关于WN18或者FreeBase子数据集里验证集的内部数据结构细节或者参考资料吗？比如验证集是否全是正例三元组，还是有负例三元组？因为我自己要造数据集，不知如何弄，还望各位大佬帮忙解答一下，万分感谢！！！！

**Comment by THUCSTHanxu13** [comment]
所有的三元组都是正例，负例的构建是基于近似于封闭世界假设的做法。你可以看之前的相关工作，里面有介绍负例的构建

**Comment by luoming110** [comment]
好的，知道了，非常感谢您！

在 2018-11-02 16:48:59，"SillyXu" <notifications@github.com> 写道：


所有的三元组都是正例，负例的构建是基于近似于封闭世界假设的做法。你可以看之前的相关工作，里面有介绍负例的构建
