### ISSUE TITLE
Generating negative samples

### ISSUE THREAD

**Issue by UditGupta10** [thunlp/OpenKE#99]
How do we control the seed for generating negative triples. According to the 'Random.h' file randd depends on 'id' which is the id of the thread. Can we do something else for this to increase randomness?

**Comment by ShulinCao** [comment]
We use randd because it is fast and supports parallel learning. The random function provided by C++ library is also fine but slower.   We can provide some more randomness functions if you want.

**Comment by UditGupta10** [comment]
When we are randomly sampling from the dataset, when can we say one random sampling strategy is better than the other?
![capture](https://user-images.githubusercontent.com/18660215/48327783-a55a2080-e666-11e8-9e9e-66c1b7afec9d.PNG)
What is the significance of these numbers: 25214903917 + 11 ? Why were they chosen?
Will using these numbers produce good random instances for any size of datasets?

**Comment by THUCSTHanxu13** [comment]
The number is an empirical number used in word2vec.c. In fact, this function can be replaced with the rand() in "thread.h". However, rand() in "thread.h" is slower.

**Comment by THUCSTHanxu13** [comment]
If you are interested in how to achieve a random number more randomly, you can the implementation of the random functions in C/C++. These random functions adopt the similar method, using random seeds instead of our fixed magic number.
